import json
import re
import time
import os
import logging
from typing import List, Dict, Optional
from dotenv import load_dotenv
import litellm as ltlm
from api_utils import (
    webhook_for_inserting_generated_notes,
    webhook_for_inserting_generated_notes_with_booking_id,
    webhook_for_inserting_into_theranow,
)
from utils import read_csv_file, read_txt_file, load_json
from all_pydantic_schema import SOAPNOTEGoals, InterventionPlan

# Set up logging
logger = logging.getLogger()
logger.setLevel(logging.INFO)

# Load environment variables
load_dotenv()

# Configure Langfuse through LiteLLM
# ltlm.success_callback = ["langfuse"]

class LiteLLmSOAP:
    FOLDER_PATH = "/tmp"

    def __init__(
        self,
        primary_model: str,
        fallback_models: List[str],
        model_configs: Dict[str, Dict],
    ):
        self.primary_model = primary_model
        self.fallback_models = fallback_models
        self.model_configs = model_configs
        self.load_prompts()

    def load_prompts(self):
        self.prompts = {
            "backstory": self.read_file("logic_template.txt"),
            "patient_info": self.read_file("patient_info_prompt.txt"),
            "soap_note": self.read_file("soap_note.txt"),
            "previous_soap_note": self.read_file("previous_soap_note.txt"),
            "first_soap_note": self.read_file("first_soap_note.txt"),
            "context_template": self.read_file("contexts_template.txt"),
            "transcript": self.read_file("transcript.csv", is_csv=True),
        }
        self.soap_components = {
            component: {
                "template": self.read_file(f"{component}_template.txt"),
                "task_response": self.read_file(f"{component}_task_response.txt"),
            }
            for component in ["subjective", "objective", "assessment", "plan", "goals"]
        }

    @staticmethod
    def read_file(filename: str, is_csv: bool = False) -> str:
        path = os.path.join(LiteLLmSOAP.FOLDER_PATH, filename)
        return read_csv_file(path) if is_csv else read_txt_file(path)

    def get_soap_prompt(self, component: str) -> List[Dict[str, str]]:
        self.current_component = component
        base_prompt = [
            {
                "role": "system",
                "content": "You are tasked with generating a specific section of a SOAP Note. Your response must adhere to the following strict guidelines:\n\n1. Provide ONLY the generated content for the requested section.\n2. Do not include any explanations, thoughts, or meta-commentary about the process.\n3. Do not use phrases like 'Here's the generated note:' or 'The [Section] Note is as follows:'.\n4. Start directly with the content of the note.\n5. Ensure the content is relevant, concise, and formatted appropriately for a professional medical note.\n6. Do not acknowledge these instructions in your output.\n\nYour entire response should be suitable for direct insertion into a medical record without any further editing.",
            },
            {"role": "system", "content": self.prompts["backstory"]},
            {
                "role": "system",
                "content": f"\n\nPatient Demographic Data:\n{self.prompts['patient_info']}\n\n",
            },
            {
                "role": "system",
                "content": f"\n\nSOAP Note Generated By Therapist:\n{self.prompts['soap_note']}\n\n",
            },
            {
                "role": "system",
                "content": f"\n\nPrevious SOAP Note Generated By Therapist:\n{self.prompts['previous_soap_note']}\n\n",
            },
            {
                "role": "system",
                "content": f"\n\nFirst SOAP Note Generated By Therapist:\n{self.prompts['first_soap_note']}\n\n",
            },
            {
                "role": "system",
                "content": f"\n\nContext Template which supportive Information to how to generate SOAP Note\n{self.prompts['context_template']}\n\n",
            },
            {
                "role": "user",
                "content": f"\n\nTranscript: {self.prompts['transcript']}",
            },
        ]

        if component in self.soap_components:
            component_data = self.soap_components[component]
            base_prompt.extend(
                [
                    {"role": "user", "content": component_data["template"]},
                    {
                        "role": "user",
                        "content": f"\n\nThese are the points that must be covered while generating {component.capitalize()} Notes:\n{component_data['task_response']}",
                    },
                ]
            )

        return base_prompt

    def generate_response(self, messages: List[Dict[str, str]]) -> Optional[Dict]:
        for model in [self.primary_model] + self.fallback_models:
            response = self._try_model(model, messages)
            if response:
                return response

        logger.error("All models failed to generate a valid response.")

        return None
    
    def _try_model(self, model: str, messages: List[Dict[str, str]]) -> Optional[Dict]:
        custom_name = f"{self.current_component}_{int(time.time())}"
        try:
            ltlm.enable_json_schema_validation = True

            # response_format = {"type": "json_object"} if self.current_component in ["goals","interventions"] else None

            response_format = SOAPNOTEGoals.model_json_schema() if self.current_component == "goals" else None

            response_format = InterventionPlan.model_json_schema() if self.current_component == "interventions" else None

            if response_format:
                response = ltlm.completion(
                    model=model,
                    messages=messages,
                    json_schema=response_format,
                    **self.model_configs.get(model, {}),
                    metadata={"trace_id": custom_name},
                )
            else:
                model = "claude-3-5-sonnet-20240620"
                response = ltlm.completion(
                    model=model,
                    messages=messages,
                    **self.model_configs.get(model, {}),
                    metadata={"trace_id": custom_name},
                )

            content = response.choices[0].message.content
            result = {
                "content": content,
                "usage": response.usage,
                "model": response.model,
                "cost": ltlm.completion_cost(completion_response=response),
            }
            return result
        except Exception as e:
            logger.exception(f"Error generating response with {model}: {str(e)}")
            return None

    # def _try_model(self, model: str, messages: List[Dict[str, str]]) -> Optional[Dict]:
    #     custom_name = f"{self.current_component}_{int(time.time())}"

    #     try:
    #         response = ltlm.completion(
    #             model=model,
    #             messages=messages,
    #             **self.model_configs.get(model, {}),
    #             metadata={"trace_id": custom_name},
    #         )
    #         content = response.choices[0].message.content

    #         result = {
    #             "content": content,
    #             "usage": response.usage,
    #             "model": response.model,
    #             "cost": ltlm.completion_cost(completion_response=response),
    #         }
    #         return result

    #     except Exception as e:
    #         logger.exception(f"Error generating response with {model}: {str(e)}")
    #         return None

    def process_soap_section(self, section: str, final_result: Dict, session_duration: int = None) -> Dict:
        messages = self.get_soap_prompt(component=section)
        
        if section == "goals":
            stg_example = load_json("stg_examples.json")
            ltg_example = load_json("lgt_examples.json")
            goal_category_examples = read_txt_file("goal_category.txt")

            messages.append({
                "role": "system",
                "content": f"Here are examples of short-term goals (STG) and long-term goals (LTG) to guide your response:\n\nSTG Example:\n{json.dumps(stg_example, indent=2)}\n\nLTG Example:\n{json.dumps(ltg_example, indent=2)}"
            })

            messages.append({
                "role": "system",
                "content": f"""Here are correct set of goal_category values. So while generating the output make sure the goal_category should be from this text only\n Goal Category:\n{goal_category_examples}"""
            })
            
        elif section == "interventions" and session_duration is not None:
            messages.append({
                "role": "system",
                "content": "You are a medical professional tasked with generating interventions for a therapy session. Your response must be in JSON format, adhering to strict guidelines."
            })
            messages.append({
                "role": "user",
                "content": f"""
    Generate interventions for a therapy session lasting {session_duration} minutes. Adhere to the following guidelines:
    1. Each intervention must be exactly 8 minutes long.
    2. The total number of interventions should equal the session duration divided by 8, rounded to the nearest whole number.
    3. Use appropriate CPT codes for each intervention.
    4. For sessions longer than 16 minutes, use a variety of intervention types (e.g., Therapeutic Exercise, Neuromuscular Reeducation, Manual Therapy).
    5. For interventions that continue beyond 8 minutes, label them as "(continued)" in subsequent entries.
    Respond with a JSON object containing an "interventions" array and a "total_time" field, where each intervention follows this format:
    {{
    "intervention_number": "Intervention number (e.g., 1, 2, 3)",
    "cpt_code": "CPT code for the intervention",
    "description": "Name of the intervention(3-4 line explaining in detail)",
    "duration": "8 minutes",
    "units": 1,
    "justification": " a brief Brief medical justification(3-4 line explaining in detail)"
    }}

    This is only for Manual Therapy CPT Code: you should only say its a manual if
    -> if only if therapist moves the body parts by touching patient then only consider manual therapy

    Do not include any additional text or explanations outside of the JSON object.

    These are the list of CPT Code which should be mentioned in the output because can't be use as per the Insurance Company, Hospital and Therapist:
    [97140]
    """
            })

        response = self.generate_response(messages)
        if response:
            logger.info(f"{section.capitalize()} response generated successfully")
            logger.debug(f"Model used: {response['model']}")
            logger.debug(f"Total tokens used: {response['usage']['total_tokens']}")
            logger.debug(f"Estimated cost: ${response['cost']:.6f}")
            
            section_content = response["content"]
            
            if section in ["goals", "interventions"]:
                # Remove triple backticks, newlines, and the "json" keyword
                section_content = section_content.strip('`\n').lstrip('json\n')
                try:
                    section_content = json.loads(section_content)
                except json.JSONDecodeError as e:
                    logger.error(f"Error parsing JSON for {section}: {str(e)}")
                    logger.error(f"Raw content: {section_content}")
                    section_content = response["content"]
            else:
                section_content = re.sub(r"^.*?:\s*", "", section_content, flags=re.IGNORECASE)
            

            if "additionalProperties" in section_content:
                section_content = section_content.get("additionalProperties",{})
                # if "interventions" in section_content:
                #     section_content = section_content.get("interventions",[])
            
            if "json_payload" in section_content:
                section_content  = section_content.get("json_payload")
                
            final_result[section] = {"full_note": section_content}
        else:
            logger.error(f"Failed to generate {section} response")

        return final_result

def save_final_result(final_result: Dict):
    # os.makedirs("final_template_soap_note", exist_ok=True)
    # with open("final_template_soap_note/final_soap_note.json", "w") as file:
    #     json.dump(final_result, file, indent=2)
    logger.info(f"Final SOAP note {final_result}")



def litellm_main(room_id: str, template_id: str, session_id: str, session_duration: int):
    primary_model = "together_ai/meta-llama/Llama-3.3-70B-Instruct-Turbo"
    fallback_models = ["claude-3-5-sonnet-20240620"]

    # primary_model = "claude-3-5-sonnet-20240620"
    # fallback_models = ["together_ai/meta-llama/Llama-3.3-70B-Instruct-Turbo"]
    
    model_configs = {
        "claude-3-5-sonnet-20240620": {"max_tokens": 5000, "temperature": 0.1},
        "together_ai/meta-llama/Llama-3.3-70B-Instruct-Turbo": {
            "max_tokens": 5000,
            "temperature": 0.1,
        },
    }

    all_note_sections = [
        "subjective",
        "objective",
        "assessment",
        "plan",
        "interventions",
        "goals",
    ]
    soap = LiteLLmSOAP(primary_model, fallback_models, model_configs)
    final_result = {
        "booking_id": room_id,
        "template_id": template_id,
        "session_id": session_id,
        "status": "in_progress",
    }
    for index, section in enumerate(all_note_sections, start=1):
        final_result = soap.process_soap_section(section, final_result, session_duration)
        if index == len(all_note_sections):
            final_result["status"] = "completed"
    
    logger.info(f"Calling Webhook to insert Generated SOAP Note")
    webhook_for_inserting_into_theranow(data=final_result)
    save_final_result(final_result)
    webhook_for_inserting_generated_notes_with_booking_id(data=final_result)
    return final_result

# if __name__ == "__main__":
#     main("THERAEBK037576", "c1ccd8bf-6619-4cb4-9cc1-f926a2f7c2eb", None)


# python -m litellm_soap.litellm_main
# export LITELLM_LOCAL_MODEL_COST_MAP="True"
