import { saveAs } from 'file-saver';
import { jsPDF } from 'jspdf';

export async function exportToPdf(noteData: any) {
  try {
    const doc = new jsPDF();
    const lineHeight = 7;
    let yPosition = 15;
    const margin = 20;

    // Set document properties
    doc.setProperties({
      title: `Clinical Note - ${noteData.patientName}`,
      subject: `SOAP Note - ${noteData.dateOfVisit}`,
      creator: 'PhysioAI'
    });

    // Add title
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('PHYSIOTHERAPY CLINICAL NOTE', margin, yPosition);
    yPosition += lineHeight * 2;

    // Patient information section
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('PATIENT INFORMATION', margin, yPosition);
    yPosition += lineHeight;
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    
    doc.text(`Patient Name: ${noteData.patientName}`, margin, yPosition);
    yPosition += lineHeight;
    
    doc.text(`Patient ID: ${noteData.patientId}`, margin, yPosition);
    yPosition += lineHeight;
    
    doc.text(`Date of Birth: ${noteData.dateOfBirth}`, margin, yPosition);
    yPosition += lineHeight;
    
    doc.text(`Date of Visit: ${noteData.dateOfVisit}`, margin, yPosition);
    yPosition += lineHeight * 2;

    // SOAP Note sections
    const addSection = (title: string, content: string) => {
      if (!content) return;
      
      // Add section title
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text(title, margin, yPosition);
      yPosition += lineHeight;
      
      // Add section content with word wrapping
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      
      const textLines = doc.splitTextToSize(content, 170);
      
      // Check if we need a new page
      if (yPosition + (textLines.length * lineHeight) > 280) {
        doc.addPage();
        yPosition = 20;
      }
      
      doc.text(textLines, margin, yPosition);
      yPosition += (textLines.length * lineHeight) + lineHeight;
    };
    
    // Add each SOAP section
    addSection('SUBJECTIVE', noteData.subjective);
    addSection('OBJECTIVE', noteData.objective);
    addSection('ASSESSMENT', noteData.assessment);
    addSection('PLAN', noteData.plan);
    
    // Add footer with timestamp
    const footerText = `Generated by PhysioAI on ${new Date().toLocaleString()}`;
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text(footerText, margin, 290);
    
    // Save the PDF
    doc.save(`SOAP_Note_${noteData.patientName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`);
    
    return true;
  } catch (error) {
    console.error('Error generating PDF:', error);
    return false;
  }
}

export async function exportToText(noteData: any) {
  try {
    // Format the clinical note as text
    let textContent = `PHYSIOTHERAPY CLINICAL NOTE\n\n`;
    textContent += `PATIENT INFORMATION\n`;
    textContent += `Patient Name: ${noteData.patientName}\n`;
    textContent += `Patient ID: ${noteData.patientId}\n`;
    textContent += `Date of Birth: ${noteData.dateOfBirth}\n`;
    textContent += `Date of Visit: ${noteData.dateOfVisit}\n\n`;
    
    // Add SOAP sections
    textContent += `SUBJECTIVE\n${noteData.subjective}\n\n`;
    textContent += `OBJECTIVE\n${noteData.objective}\n\n`;
    textContent += `ASSESSMENT\n${noteData.assessment}\n\n`;
    textContent += `PLAN\n${noteData.plan}\n\n`;
    
    // Add footer
    textContent += `Generated by PhysioAI on ${new Date().toLocaleString()}`;
    
    // Create a blob and save the file
    const blob = new Blob([textContent], { type: 'text/plain;charset=utf-8' });
    saveAs(blob, `SOAP_Note_${noteData.patientName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.txt`);
    
    return true;
  } catch (error) {
    console.error('Error generating text file:', error);
    return false;
  }
}
