import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { useMutation } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { usePlanCart } from "@/lib/planCart";
import { useOrchestratePlan } from "@/lib/orchestratePlanContext";
import type { OrchestratedSessionStep } from "@/components/skeleton/MyPlanRenderBlocks";
import { synthesizeRationaleLocally } from "@/lib/treatmentRationaleLocal";

export interface RationaleClinicalContextInput {
  topHypothesis?: string;
  irritability?: string;
  stage?: string;
  recoveryPhase?: string;
  primaryRegion?: string;
  patientFactors?: string[] | Record<string, unknown>;
  constraints?: string[];
  painMarkers?: {
    count?: number;
    structures?: string[];
    mechanisms?: string[];
    severitySummary?: string;
  };
  slingDrivers?: Array<{ sling: string; role?: string; drivingFinding?: string }>;
  fascialTensions?: {
    activeChains?: string[];
    drivingChains?: string[];
    propagationCount?: number;
  };
  chainIntegrity?: Array<{ chain: string; score: number; issues?: string[] }>;
  compromisedTissues?: Array<{ name: string; status?: string; region?: string }>;
  scarLoad?: { scarCount?: number; adhesionCount?: number; regions?: string[] };
  forceHotspots?: Array<{ joint: string; peakForceN?: number; asymmetryIndex?: number; note?: string }>;
  posturalDeviations?: { summary?: string; severity?: string };
  thoracicStiffness?: string;
  tendonInflammation?: string[];
  naturalProgression?: { window?: string; chronicityRiskPercent?: number; recurrenceRiskPercent?: number };
}

export interface TreatmentRationaleDriver {
  label: string;
  detail: string;
  kind?: string;
  /** IDs of cart items that target this driver. Empty array means
   *  "no item targets this yet" — surfaced as a clinical gap by the UI. */
  addressedItemIds: string[];
}

export interface TreatmentRationaleItem {
  itemId: string;
  itemName: string;
  modality: string;
  why: string;
  addresses: string[];
}

export interface TreatmentRationaleResult {
  clinicalPicture: string;
  drivers: TreatmentRationaleDriver[];
  treatmentRationale: TreatmentRationaleItem[];
  orderingRationale: string;
  generatedAt: string;
}

export type TreatmentRationaleSource = "local" | "ai";

interface TreatmentRationaleContextValue {
  rationale: TreatmentRationaleResult | null;
  /** Whether the displayed rationale was synthesised locally (deterministic
   *  fallback) or generated by the AI endpoint. Lets the UI pip a small
   *  "AI" / "auto" badge so the clinician knows which is which. */
  source: TreatmentRationaleSource;
  /** True when an AI rationale exists in memory but the cart / clinical
   *  context / orchestrated order has changed since it was generated, so
   *  the UI is currently showing the up-to-date local synthesis instead.
   *  Surfaces a "Stale — regenerate" hint on the section header. */
  isStale: boolean;
  isPending: boolean;
  error: Error | null;
  /** In-component trigger (used by the MasterPlanCard "Why this plan?"
   *  Generate / Refresh button). No-op while another request is in flight
   *  or the cart is empty. */
  generate: () => void;
  reset: () => void;
}

const TreatmentRationaleContext = createContext<TreatmentRationaleContextValue | null>(null);

interface TreatmentRationaleProviderProps {
  children: ReactNode;
  clinicalContext: RationaleClinicalContextInput;
  /** When true, automatically (re)generate the rationale every time a new
   *  orchestrated plan lands. Lets the rationale stay in sync with the
   *  AI-organised order without an extra click. Defaults to true. */
  autoOnOrchestrate?: boolean;
}

export function TreatmentRationaleProvider({
  children,
  clinicalContext,
  autoOnOrchestrate = true,
}: TreatmentRationaleProviderProps) {
  const { items } = usePlanCart();
  const { orchestrated } = useOrchestratePlan();
  // The AI-generated rationale is layered ON TOP of the always-on local
  // synthesis. If AI fails, the local result keeps showing, so the
  // clinician is never blocked by an outage. Each AI result is recorded
  // alongside the SIGNATURE of the cart/context/order it was generated
  // against — when that signature drifts, the AI payload becomes stale
  // and we fall back to the up-to-date local synthesis automatically.
  const [aiResult, setAiResult] = useState<{ data: TreatmentRationaleResult; signature: string } | null>(null);

  const itemsRef = useRef(items);
  itemsRef.current = items;
  const ctxRef = useRef(clinicalContext);
  ctxRef.current = clinicalContext;
  const orchestratedRef = useRef<typeof orchestrated>(orchestrated);
  orchestratedRef.current = orchestrated;

  // Stable, content-based signature of everything that should invalidate
  // a previously-generated AI rationale. Order-independent within the
  // cart so reordering items in storage doesn't trigger a false stale.
  const signature = useMemo<string>(() => {
    const itemSig = items
      .map(i =>
        `${i.id}|${i.modality}|${i.name}|${i.dosage ?? ""}|${i.targetStructure ?? ""}|${i.targetFinding ?? ""}|${i.rationale ?? ""}|${i.slingTag ?? ""}|${i.slingRole ?? ""}`
      )
      .sort()
      .join("§");
    let ctxSig = "";
    try {
      ctxSig = JSON.stringify(clinicalContext ?? {});
    } catch {
      ctxSig = "";
    }
    const orderSig = (orchestrated?.sessionOrder ?? [])
      .map(s => `${s.order}:${s.itemId}`)
      .join(",");
    return `${itemSig}@@${ctxSig}@@${orderSig}`;
  }, [items, clinicalContext, orchestrated?.sessionOrder]);

  const signatureRef = useRef(signature);
  signatureRef.current = signature;

  // Deterministic local rationale, recomputed whenever the cart, the
  // clinical context, or the orchestrated session order changes. This is
  // the source-of-truth fallback per the spec and is shown immediately
  // while the AI request (if any) is in-flight or stale.
  const localRationale = useMemo<TreatmentRationaleResult | null>(() => {
    if (items.length === 0) return null;
    return synthesizeRationaleLocally(
      items,
      clinicalContext,
      orchestrated?.sessionOrder,
    );
  }, [items, clinicalContext, orchestrated?.sessionOrder]);

  const generateMutation = useMutation({
    mutationFn: async () => {
      const sessionOrder: OrchestratedSessionStep[] | undefined = orchestratedRef.current?.sessionOrder;
      const result = await apiRequest("/api/treatment-plan/rationale", "POST", {
        items: itemsRef.current,
        clinicalContext: ctxRef.current,
        sessionOrder: sessionOrder && sessionOrder.length > 0 ? sessionOrder : undefined,
      });
      return result as TreatmentRationaleResult;
    },
    // Record the signature CAPTURED AT THE MOMENT THE REQUEST WAS SENT
    // (via signatureRef) so that if anything has drifted since the user
    // hit "Generate", we still know to mark the result stale.
    onSuccess: (data) => setAiResult({ data, signature: signatureRef.current }),
  });

  const generate = useCallback(() => {
    if (generateMutation.isPending) return;
    if (itemsRef.current.length < 1) return;
    generateMutation.mutate();
  }, [generateMutation]);

  const reset = useCallback(() => {
    setAiResult(null);
    generateMutation.reset();
  }, [generateMutation]);

  // Auto-regenerate whenever a fresh orchestrated plan lands (so the AI
  // ordering rationale matches the AI's chosen order).
  const isPending = generateMutation.isPending;
  const mutate = generateMutation.mutate;
  const lastOrchestratedAtRef = useRef<string | null>(null);
  useEffect(() => {
    if (!autoOnOrchestrate) return;
    if (!orchestrated) return;
    if (orchestrated.generatedAt === lastOrchestratedAtRef.current) return;
    if (itemsRef.current.length < 1) return;
    if (isPending) return;
    lastOrchestratedAtRef.current = orchestrated.generatedAt;
    mutate();
  }, [orchestrated, autoOnOrchestrate, isPending, mutate]);

  // Clear AI rationale if the cart is emptied, so we don't show stale text.
  useEffect(() => {
    if (items.length === 0 && aiResult) {
      setAiResult(null);
      lastOrchestratedAtRef.current = null;
    }
  }, [items.length, aiResult]);

  // Decide which rationale to show:
  //   • If the AI result is fresh (signature matches), prefer it AND
  //     fill any per-item gaps from the local synthesis (so newly-added
  //     items still get a "Why?" reveal even if AI hasn't been refreshed
  //     for them yet — defensive against incomplete payloads).
  //   • If the AI result is stale (signature drift since generation),
  //     ignore it entirely and show the up-to-date local synthesis.
  //     The section header surfaces an "AI stale — regenerate" badge.
  //   • If there's no AI result at all, show local.
  const aiFresh = !!aiResult && aiResult.signature === signature;
  const aiStale = !!aiResult && !aiFresh;

  const rationale = useMemo<TreatmentRationaleResult | null>(() => {
    if (!aiFresh) return localRationale;
    if (!aiResult) return localRationale;
    if (!localRationale) return aiResult.data;
    // Merge per-item: AI wins for IDs it covers; local fills the rest.
    const aiIds = new Set(aiResult.data.treatmentRationale.map(r => r.itemId));
    const merged = [...aiResult.data.treatmentRationale];
    for (const r of localRationale.treatmentRationale) {
      if (!aiIds.has(r.itemId)) merged.push(r);
    }
    return { ...aiResult.data, treatmentRationale: merged };
  }, [aiFresh, aiResult, localRationale]);

  const source: TreatmentRationaleSource = aiFresh ? "ai" : "local";

  const value = useMemo<TreatmentRationaleContextValue>(() => ({
    rationale,
    source,
    isStale: aiStale,
    isPending: generateMutation.isPending,
    error: (generateMutation.error as Error | null) ?? null,
    generate,
    reset,
  }), [rationale, source, aiStale, generateMutation.isPending, generateMutation.error, generate, reset]);

  return <TreatmentRationaleContext.Provider value={value}>{children}</TreatmentRationaleContext.Provider>;
}

export function useTreatmentRationale(): TreatmentRationaleContextValue {
  const ctx = useContext(TreatmentRationaleContext);
  if (!ctx) {
    return {
      rationale: null,
      source: "local",
      isStale: false,
      isPending: false,
      error: null,
      generate: () => {},
      reset: () => {},
    };
  }
  return ctx;
}
