import { db } from './db';
import { 
  competitions, 
  competitionParticipants,
  complexCases,
  users,
  type Competition,
  type InsertCompetition,
  type CompetitionParticipant,
  type InsertCompetitionParticipant,
  type ComplexCase
} from '@shared/schema';
import { eq, and, gte, lte, lt, desc, asc, count, isNull } from 'drizzle-orm';

export interface ComplexCaseCompetitionConfig {
  title: string;
  description: string;
  bodyPart?: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  maxParticipants: number;
  timeLimit: number; // Total competition time in minutes
  stageTimeLimit: number; // Time per stage in minutes
  complexCaseId: number;
  registrationWindow: number; // Minutes before start when registration closes
}

export class ComplexCaseCompetitionService {
  
  /**
   * Creates a scheduled complex case competition
   */
  async createComplexCaseCompetition(
    config: ComplexCaseCompetitionConfig,
    startTime: Date,
    createdBy?: number
  ): Promise<Competition> {
    const registrationDeadline = new Date(startTime.getTime() - (config.registrationWindow * 60 * 1000));
    const endTime = new Date(startTime.getTime() + (config.timeLimit * 60 * 1000));
    
    const competition: InsertCompetition = {
      title: config.title,
      description: config.description,
      type: 'complete_clinician',
      status: 'upcoming',
      bodyPart: config.bodyPart as any || null,
      difficulty: config.difficulty,
      timeLimit: config.timeLimit,
      maxParticipants: config.maxParticipants,
      currentParticipants: 0,
      registrationDeadline,
      startTime,
      endTime,
      createdBy,
      caseStudyIds: [], // Empty for complex cases
      complexCaseIds: [config.complexCaseId],
      caseType: 'complex',
      isAutoGenerated: true,
      rules: {
        scoringWeights: {
          accuracy: 40,
          speed: 15,
          reasoning: 25,
          differential: 10,
          treatment: 10
        },
        allowedAttempts: 1,
        showLeaderboard: true,
        revealAnswers: false,
        stageTimeLimit: config.stageTimeLimit,
        enableAntiCheat: false // Will implement later
      }
    };

    const [newCompetition] = await db
      .insert(competitions)
      .values(competition)
      .returning();

    return newCompetition;
  }

  /**
   * Auto-schedules complex case competitions throughout the day
   */
  async scheduleDailyComplexCompetitions(): Promise<Competition[]> {
    const now = new Date();
    const tomorrow = new Date(now.getTime() + 24 * 60 * 60 * 1000);
    
    // Get available complex cases
    const availableComplexCases = await db
      .select()
      .from(complexCases)
      .limit(10);

    if (availableComplexCases.length === 0) {
      throw new Error('No complex cases available for competitions');
    }

    const newCompetitions: Competition[] = [];
    
    // Schedule competitions every 2 hours starting from next hour
    const scheduleStartHour = now.getHours() + 1;
    
    for (let hour = scheduleStartHour; hour < 24; hour += 2) {
      const startTime = new Date();
      startTime.setHours(hour, 0, 0, 0);
      
      // Skip if in the past
      if (startTime <= now) continue;
      
      // Select a random complex case
      const randomCase = availableComplexCases[Math.floor(Math.random() * availableComplexCases.length)];
      
      const config: ComplexCaseCompetitionConfig = {
        title: `${this.getTimeSlotName(hour)} Clinical Challenge`,
        description: `Multi-stage clinical reasoning competition featuring ${randomCase.bodyPart} case study. Test your diagnostic skills and clinical decision-making!`,
        bodyPart: randomCase.bodyPart,
        difficulty: randomCase.complexity as 'beginner' | 'intermediate' | 'advanced',
        maxParticipants: 20,
        timeLimit: 45,
        stageTimeLimit: 5,
        complexCaseId: randomCase.id,
        registrationWindow: 10
      };

      const competition = await this.createComplexCaseCompetition(config, startTime);
      newCompetitions.push(competition);
    }

    return newCompetitions;
  }

  /**
   * Handles user registration for complex case competition
   */
  async joinComplexCaseCompetition(
    competitionId: number, 
    userId: number
  ): Promise<{ success: boolean; message: string; participant?: CompetitionParticipant }> {
    // Get competition details
    const [competition] = await db
      .select()
      .from(competitions)
      .where(eq(competitions.id, competitionId));

    if (!competition) {
      return { success: false, message: 'Competition not found' };
    }

    // Check if registration is still open
    if (competition.registrationDeadline && new Date() > competition.registrationDeadline) {
      return { success: false, message: 'Registration deadline has passed' };
    }

    // Check if competition is full
    if (competition.currentParticipants >= (competition.maxParticipants || 20)) {
      return { success: false, message: 'Competition is full' };
    }

    // Check if user already joined
    const [existingParticipant] = await db
      .select()
      .from(competitionParticipants)
      .where(and(
        eq(competitionParticipants.competitionId, competitionId),
        eq(competitionParticipants.userId, userId)
      ));

    if (existingParticipant) {
      return { success: false, message: 'Already registered for this competition' };
    }

    // Register user
    const participantData: InsertCompetitionParticipant = {
      competitionId,
      userId,
      caseAttempts: []
    };

    const [participant] = await db
      .insert(competitionParticipants)
      .values(participantData)
      .returning();

    // Update participant count
    await db
      .update(competitions)
      .set({ 
        currentParticipants: competition.currentParticipants + 1,
        updatedAt: new Date()
      })
      .where(eq(competitions.id, competitionId));

    return { 
      success: true, 
      message: 'Successfully registered for competition',
      participant 
    };
  }

  /**
   * Gets upcoming complex case competitions
   */
  async getUpcomingComplexCompetitions(limit: number = 10): Promise<Competition[]> {
    const now = new Date();
    
    return await db
      .select()
      .from(competitions)
      .where(and(
        eq(competitions.caseType, 'complex'),
        eq(competitions.status, 'upcoming'),
        gte(competitions.startTime, now)
      ))
      .orderBy(asc(competitions.startTime))
      .limit(limit);
  }

  /**
   * Gets active complex case competitions
   */
  async getActiveComplexCompetitions(): Promise<Competition[]> {
    const now = new Date();
    
    return await db
      .select()
      .from(competitions)
      .where(and(
        eq(competitions.caseType, 'complex'),
        eq(competitions.status, 'active'),
        lte(competitions.startTime, now),
        gte(competitions.endTime, now)
      ))
      .orderBy(asc(competitions.startTime));
  }

  /**
   * Starts competitions that should be active
   */
  async startScheduledCompetitions(): Promise<Competition[]> {
    const now = new Date();
    
    // Find competitions that should start now
    const competitionsToStart = await db
      .select()
      .from(competitions)
      .where(and(
        eq(competitions.status, 'upcoming'),
        lte(competitions.startTime, now),
        gte(competitions.endTime, now)
      ));

    const startedCompetitions: Competition[] = [];

    for (const competition of competitionsToStart) {
      const [updated] = await db
        .update(competitions)
        .set({ 
          status: 'active',
          updatedAt: new Date()
        })
        .where(eq(competitions.id, competition.id))
        .returning();
      
      startedCompetitions.push(updated);
    }

    return startedCompetitions;
  }

  /**
   * Ends competitions that should be finished
   */
  async endFinishedCompetitions(): Promise<Competition[]> {
    const now = new Date();
    
    // Find competitions that should end now
    const competitionsToEnd = await db
      .select()
      .from(competitions)
      .where(and(
        eq(competitions.status, 'active'),
        lt(competitions.endTime, now)
      ));

    const endedCompetitions: Competition[] = [];

    for (const competition of competitionsToEnd) {
      // Calculate final rankings
      await this.calculateFinalRankings(competition.id);
      
      const [updated] = await db
        .update(competitions)
        .set({ 
          status: 'completed',
          updatedAt: new Date()
        })
        .where(eq(competitions.id, competition.id))
        .returning();
      
      endedCompetitions.push(updated);
    }

    return endedCompetitions;
  }

  /**
   * Gets competition participants with their current status
   */
  async getCompetitionParticipants(competitionId: number): Promise<any[]> {
    const participants = await db
      .select({
        id: competitionParticipants.id,
        userId: competitionParticipants.userId,
        username: users.username,
        fullName: users.fullName,
        joinedAt: competitionParticipants.joinedAt,
        startedAt: competitionParticipants.startedAt,
        completedAt: competitionParticipants.completedAt,
        totalScore: competitionParticipants.totalScore,
        rank: competitionParticipants.rank,
        timeSpent: competitionParticipants.timeSpent
      })
      .from(competitionParticipants)
      .leftJoin(users, eq(competitionParticipants.userId, users.id))
      .where(eq(competitionParticipants.competitionId, competitionId))
      .orderBy(desc(competitionParticipants.totalScore));

    return participants;
  }

  /**
   * Runs the competition management system
   */
  async manageCompetitions(): Promise<void> {
    try {
      // Start competitions that should be active
      const started = await this.startScheduledCompetitions();
      if (started.length > 0) {
        console.log(`Started ${started.length} competitions`);
      }

      // End competitions that should be finished
      const ended = await this.endFinishedCompetitions();
      if (ended.length > 0) {
        console.log(`Ended ${ended.length} competitions`);
      }

      // Check if we need to schedule new competitions
      const upcomingCount = await db
        .select({ count: count() })
        .from(competitions)
        .where(and(
          eq(competitions.caseType, 'complex'),
          eq(competitions.status, 'upcoming'),
          gte(competitions.startTime, new Date())
        ));

      // If less than 5 upcoming competitions, schedule more
      if (upcomingCount[0].count < 5) {
        const newCompetitions = await this.scheduleDailyComplexCompetitions();
        console.log(`Scheduled ${newCompetitions.length} new complex case competitions`);
      }

    } catch (error) {
      console.error('Error managing competitions:', error);
    }
  }

  private async calculateFinalRankings(competitionId: number): Promise<void> {
    // Get all participants sorted by score
    const participants = await db
      .select()
      .from(competitionParticipants)
      .where(eq(competitionParticipants.competitionId, competitionId))
      .orderBy(desc(competitionParticipants.totalScore));

    // Update rankings
    for (let i = 0; i < participants.length; i++) {
      await db
        .update(competitionParticipants)
        .set({ rank: i + 1 })
        .where(eq(competitionParticipants.id, participants[i].id));
    }
  }

  private getTimeSlotName(hour: number): string {
    if (hour >= 6 && hour < 12) return 'Morning';
    if (hour >= 12 && hour < 17) return 'Afternoon';
    if (hour >= 17 && hour < 21) return 'Evening';
    return 'Night';
  }
}

export const complexCaseCompetitionService = new ComplexCaseCompetitionService();