import { OpenAI } from "openai";
import { storage } from "./storage";
import { nanoid } from "nanoid";
import type { SoapNote, InsertSoapNote } from "../shared/schema";

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

interface TranscriptionResult {
  text: string;
  duration?: number;
}

interface SoapNoteAnalysis {
  subjective: string;
  objective: string;
  assessment: string;
  plan: string;
  patientInfo?: {
    name?: string;
    id?: string;
    dob?: string;
  };
  confidence: number;
}

interface PatientSwitchAnalysis {
  patientSwitchDetected: boolean;
  newPatientName?: string;
  confidence: number;
}

export class SoapNotesService {
  /**
   * Creates a new SOAP notes session
   */
  async createSession(userId: number): Promise<SoapNote> {
    const sessionId = nanoid();
    const today = new Date().toISOString().split('T')[0];
    
    const soapNote: InsertSoapNote = {
      userId,
      sessionId,
      dateOfVisit: today,
      sessionStatus: "draft",
      isAutoGenerated: true,
      patientSwitchDetected: false,
      confidence: 0,
    };

    return await storage.createSoapNote(soapNote);
  }

  /**
   * Transcribes audio file using OpenAI Whisper
   */
  async transcribeAudio(audioFile: Buffer, fileName: string): Promise<TranscriptionResult> {
    try {
      // Create a temporary file for OpenAI API
      const fs = await import('fs');
      const path = await import('path');
      const tempPath = path.join('/tmp', `audio_${Date.now()}_${fileName}`);
      
      fs.writeFileSync(tempPath, audioFile);
      
      const transcription = await openai.audio.transcriptions.create({
        file: fs.createReadStream(tempPath),
        model: "whisper-1",
        language: "en",
      });

      // Clean up temp file
      fs.unlinkSync(tempPath);

      return {
        text: transcription.text,
        duration: transcription.duration || 0,
      };
    } catch (error) {
      console.error("Error transcribing audio:", error);
      throw new Error(`Failed to transcribe audio: ${error.message}`);
    }
  }

  /**
   * Analyzes transcription text to detect patient switching
   */
  async analyzePatientSwitch(
    transcriptionText: string,
    currentPatientName?: string
  ): Promise<PatientSwitchAnalysis> {
    try {
      const prompt = `
Analyze this medical conversation transcript to determine if there's a patient switch (when the healthcare provider starts discussing a different patient).

Current patient: ${currentPatientName || "Unknown"}
Transcript: "${transcriptionText}"

Look for indicators such as:
- "Next patient is..."
- "Now seeing [patient name]"
- "Moving on to [patient name]"
- Introduction of a new patient
- Clear context switches

Respond with JSON in this format:
{
  "patientSwitchDetected": boolean,
  "newPatientName": "string or null",
  "confidence": number (0-100)
}
`;

      const response = await openai.chat.completions.create({
        model: "gpt-4o",
        messages: [
          {
            role: "system",
            content: "You are a medical AI assistant that analyzes healthcare conversations to detect when providers switch between patients. Be accurate and conservative in your detection."
          },
          {
            role: "user",
            content: prompt
          }
        ],
        response_format: { type: "json_object" }
      });

      const content = response.choices[0].message.content;
      if (!content) {
        throw new Error("OpenAI returned empty response");
      }

      const result = JSON.parse(content);
      return {
        patientSwitchDetected: result.patientSwitchDetected || false,
        newPatientName: result.newPatientName || undefined,
        confidence: Math.min(100, Math.max(0, result.confidence || 0)),
      };
    } catch (error) {
      console.error("Error analyzing patient switch:", error);
      return {
        patientSwitchDetected: false,
        confidence: 0,
      };
    }
  }

  /**
   * Generates SOAP note sections from transcription
   */
  async generateSoapFromTranscription(
    transcriptionText: string,
    patientName?: string,
    existingNote?: Partial<SoapNote>
  ): Promise<SoapNoteAnalysis> {
    try {
      const prompt = `
Create a professional SOAP note from this medical conversation transcript.

Patient: ${patientName || "Patient"}
Transcript: "${transcriptionText}"

Generate a comprehensive SOAP note with these sections:
- Subjective: Patient's reported symptoms, concerns, and history
- Objective: Observable findings, measurements, tests
- Assessment: Clinical analysis and differential diagnosis
- Plan: Treatment plan, follow-up, recommendations

${existingNote ? `
Previous note content to build upon:
Subjective: ${existingNote.subjective || ""}
Objective: ${existingNote.objective || ""}
Assessment: ${existingNote.assessment || ""}
Plan: ${existingNote.plan || ""}
` : ""}

Respond with JSON in this format:
{
  "subjective": "detailed subjective findings",
  "objective": "detailed objective findings", 
  "assessment": "clinical assessment and diagnosis",
  "plan": "treatment plan and recommendations",
  "patientInfo": {
    "name": "extracted patient name if mentioned",
    "id": "patient ID if mentioned",
    "dob": "date of birth if mentioned"
  },
  "confidence": number (0-100 based on transcript quality)
}
`;

      const response = await openai.chat.completions.create({
        model: "gpt-4o",
        messages: [
          {
            role: "system",
            content: "You are an expert physiotherapist with extensive experience in writing detailed SOAP notes. Create professional, comprehensive clinical notes from conversation transcripts."
          },
          {
            role: "user",
            content: prompt
          }
        ],
        response_format: { type: "json_object" }
      });

      const content = response.choices[0].message.content;
      if (!content) {
        throw new Error("OpenAI returned empty response");
      }

      const result = JSON.parse(content);
      return {
        subjective: result.subjective || "",
        objective: result.objective || "",
        assessment: result.assessment || "",
        plan: result.plan || "",
        patientInfo: result.patientInfo || {},
        confidence: Math.min(100, Math.max(0, result.confidence || 75)),
      };
    } catch (error) {
      console.error("Error generating SOAP note:", error);
      throw new Error(`Failed to generate SOAP note: ${error.message}`);
    }
  }

  /**
   * Processes audio and updates SOAP note session
   */
  async processAudioForSession(
    sessionId: string,
    audioFile: Buffer,
    fileName: string
  ): Promise<SoapNote> {
    try {
      // Get existing session
      const existingNote = await storage.getSoapNoteBySessionId(sessionId);
      if (!existingNote) {
        throw new Error("Session not found");
      }

      // Update status to processing
      await storage.updateSoapNote(existingNote.id, {
        sessionStatus: "processing",
      });

      // Transcribe audio
      const transcription = await this.transcribeAudio(audioFile, fileName);
      
      // Combine with existing transcription
      const fullTranscription = existingNote.fullTranscription 
        ? `${existingNote.fullTranscription}\n\n${transcription.text}`
        : transcription.text;

      // Check for patient switch
      const patientSwitch = await this.analyzePatientSwitch(
        transcription.text,
        existingNote.patientName || undefined
      );

      // Generate/update SOAP note
      const soapAnalysis = await this.generateSoapFromTranscription(
        fullTranscription,
        patientSwitch.newPatientName || existingNote.patientName || undefined,
        existingNote
      );

      // Update patient info if detected
      const patientName = soapAnalysis.patientInfo?.name || 
                         patientSwitch.newPatientName || 
                         existingNote.patientName;
      
      const patientId = soapAnalysis.patientInfo?.id || existingNote.patientId;
      const dateOfBirth = soapAnalysis.patientInfo?.dob || existingNote.dateOfBirth;

      // Update the note
      const updatedNote = await storage.updateSoapNote(existingNote.id, {
        fullTranscription,
        patientName,
        patientId,
        dateOfBirth,
        subjective: soapAnalysis.subjective,
        objective: soapAnalysis.objective,
        assessment: soapAnalysis.assessment,
        plan: soapAnalysis.plan,
        patientSwitchDetected: patientSwitch.patientSwitchDetected,
        recordingDuration: (existingNote.recordingDuration || 0) + (transcription.duration || 0),
        confidence: Math.round((soapAnalysis.confidence + patientSwitch.confidence) / 2),
        sessionStatus: "completed",
        completedAt: new Date(),
      });

      return updatedNote;
    } catch (error) {
      console.error("Error processing audio for session:", error);
      throw error;
    }
  }

  /**
   * Gets active session for user or creates new one if patient switch detected
   */
  async getOrCreateActiveSession(
    userId: number,
    audioText?: string
  ): Promise<SoapNote> {
    try {
      const activeSession = await storage.getActiveSoapSession(userId);
      
      if (!activeSession) {
        return await this.createSession(userId);
      }

      // If audio provided, check for patient switch
      if (audioText) {
        const patientSwitch = await this.analyzePatientSwitch(
          audioText,
          activeSession.patientName || undefined
        );

        if (patientSwitch.patientSwitchDetected && patientSwitch.confidence > 70) {
          // Mark current session as completed and create new one
          await storage.updateSoapNote(activeSession.id, {
            sessionStatus: "completed",
            completedAt: new Date(),
          });
          
          return await this.createSession(userId);
        }
      }

      return activeSession;
    } catch (error) {
      console.error("Error getting/creating active session:", error);
      throw error;
    }
  }

  /**
   * Gets all SOAP notes for a user
   */
  async getUserSoapNotes(userId: number): Promise<SoapNote[]> {
    return await storage.getSoapNotes(userId);
  }

  /**
   * Gets a specific SOAP note
   */
  async getSoapNote(id: number): Promise<SoapNote | undefined> {
    return await storage.getSoapNote(id);
  }

  /**
   * Manually marks patient switch for session
   */
  async markPatientSwitch(sessionId: string): Promise<SoapNote> {
    return await storage.markPatientSwitch(sessionId);
  }
}

export const soapNotesService = new SoapNotesService();