import { OpenAI } from "openai";
import { storage } from "./storage";
import { nanoid } from "nanoid";
import { aiPaperworkService, type PaperworkGenerationResult } from "./aiPaperworkService";
import type { SoapNote, InsertSoapNote } from "../shared/schema";

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

interface TranscriptionResult {
  text: string;
  duration?: number;
}

interface SoapNoteAnalysis {
  subjective: string;
  objective: string;
  assessment: string;
  plan: string;
  patientInfo?: {
    name?: string;
    id?: string;
    dob?: string;
  };
  confidence: number;
}

interface PatientSwitchAnalysis {
  patientSwitchDetected: boolean;
  newPatientName?: string;
  confidence: number;
}

export class SoapNotesService {
  /**
   * Creates a new SOAP notes session
   */
  async createSession(userId: number): Promise<SoapNote> {
    const sessionId = nanoid();
    const today = new Date().toISOString().split('T')[0];
    
    const soapNote: InsertSoapNote = {
      userId,
      sessionId,
      dateOfVisit: today,
      sessionStatus: "draft",
      isAutoGenerated: true,
      patientSwitchDetected: false,
      confidence: 0,
      // Provide default values for required fields
      subjective: "Recording in progress...",
      objective: "",
      assessment: "",
      plan: ""
    };

    return await storage.createSoapNote(soapNote);
  }

  /**
   * Transcribes audio file using OpenAI Whisper
   */
  async transcribeAudio(audioFile: Buffer, fileName: string): Promise<TranscriptionResult> {
    try {
      // Create a temporary file for OpenAI API
      const fs = await import('fs');
      const path = await import('path');
      const tempPath = path.join('/tmp', `audio_${Date.now()}_${fileName}`);
      
      fs.writeFileSync(tempPath, audioFile);
      
      const transcription = await openai.audio.transcriptions.create({
        file: fs.createReadStream(tempPath),
        model: "whisper-1",
        language: "en",
      });

      // Clean up temp file
      fs.unlinkSync(tempPath);

      return {
        text: transcription.text,
        duration: transcription.duration || 0,
      };
    } catch (error) {
      console.error("Error transcribing audio:", error);
      throw new Error(`Failed to transcribe audio: ${error.message}`);
    }
  }

  /**
   * Analyzes transcription text to detect patient switching
   */
  async analyzePatientSwitch(
    transcriptionText: string,
    currentPatientName?: string
  ): Promise<PatientSwitchAnalysis> {
    try {
      const prompt = `
Analyze this medical conversation transcript to determine if there's a patient switch (when the healthcare provider starts discussing a different patient).

Current patient: ${currentPatientName || "Unknown"}
Transcript: "${transcriptionText}"

Look for indicators such as:
- "Next patient is..."
- "Now seeing [patient name]"
- "Moving on to [patient name]"
- Introduction of a new patient
- Clear context switches

Respond with JSON in this format:
{
  "patientSwitchDetected": boolean,
  "newPatientName": "string or null",
  "confidence": number (0-100)
}
`;

      const response = await openai.chat.completions.create({
        model: "gpt-4o",
        messages: [
          {
            role: "system",
            content: "You are a medical AI assistant that analyzes healthcare conversations to detect when providers switch between patients. Be accurate and conservative in your detection."
          },
          {
            role: "user",
            content: prompt
          }
        ],
        response_format: { type: "json_object" }
      });

      const content = response.choices[0].message.content;
      if (!content) {
        throw new Error("OpenAI returned empty response");
      }

      const result = JSON.parse(content);
      return {
        patientSwitchDetected: result.patientSwitchDetected || false,
        newPatientName: result.newPatientName || undefined,
        confidence: Math.min(100, Math.max(0, result.confidence || 0)),
      };
    } catch (error) {
      console.error("Error analyzing patient switch:", error);
      return {
        patientSwitchDetected: false,
        confidence: 0,
      };
    }
  }

  /**
   * Generates SOAP note sections from transcription
   */
  async generateSoapFromTranscription(
    transcriptionText: string,
    patientName?: string,
    existingNote?: Partial<SoapNote>
  ): Promise<SoapNoteAnalysis> {
    try {
      const prompt = `
Create a professional SOAP note from this medical conversation transcript.

Patient: ${patientName || "Patient"}
Transcript: "${transcriptionText}"

Generate a comprehensive SOAP note with these sections:
- Subjective: Patient's reported symptoms, concerns, and history
- Objective: Observable findings, measurements, tests
- Assessment: Clinical analysis and differential diagnosis
- Plan: Treatment plan, follow-up, recommendations

${existingNote ? `
Previous note content to build upon:
Subjective: ${existingNote.subjective || ""}
Objective: ${existingNote.objective || ""}
Assessment: ${existingNote.assessment || ""}
Plan: ${existingNote.plan || ""}
` : ""}

Respond with JSON in this format:
{
  "subjective": "detailed subjective findings",
  "objective": "detailed objective findings", 
  "assessment": "clinical assessment and diagnosis",
  "plan": "treatment plan and recommendations",
  "patientInfo": {
    "name": "extracted patient name if mentioned",
    "id": "patient ID if mentioned",
    "dob": "date of birth if mentioned"
  },
  "confidence": number (0-100 based on transcript quality)
}
`;

      const response = await openai.chat.completions.create({
        model: "gpt-4o",
        messages: [
          {
            role: "system",
            content: "You are an expert physiotherapist with extensive experience in writing detailed SOAP notes. Create professional, comprehensive clinical notes from conversation transcripts."
          },
          {
            role: "user",
            content: prompt
          }
        ],
        response_format: { type: "json_object" }
      });

      const content = response.choices[0].message.content;
      if (!content) {
        throw new Error("OpenAI returned empty response");
      }

      const result = JSON.parse(content);
      return {
        subjective: result.subjective || "",
        objective: result.objective || "",
        assessment: result.assessment || "",
        plan: result.plan || "",
        patientInfo: result.patientInfo || {},
        confidence: Math.min(100, Math.max(0, result.confidence || 75)),
      };
    } catch (error) {
      console.error("Error generating SOAP note:", error);
      throw new Error(`Failed to generate SOAP note: ${error.message}`);
    }
  }

  /**
   * Processes audio and updates SOAP note session
   */
  async processAudioForSession(
    sessionId: string,
    audioFile: Buffer,
    fileName: string
  ): Promise<SoapNote> {
    try {
      // Get existing session
      const existingNote = await storage.getSoapNoteBySessionId(sessionId);
      if (!existingNote) {
        throw new Error("Session not found");
      }

      // Update status to processing
      await storage.updateSoapNote(existingNote.id, {
        sessionStatus: "processing",
      });

      // Transcribe audio
      const transcription = await this.transcribeAudio(audioFile, fileName);
      
      // Combine with existing transcription
      const fullTranscription = existingNote.fullTranscription 
        ? `${existingNote.fullTranscription}\n\n${transcription.text}`
        : transcription.text;

      // Check for patient switch
      const patientSwitch = await this.analyzePatientSwitch(
        transcription.text,
        existingNote.patientName || undefined
      );

      // Generate/update SOAP note
      const soapAnalysis = await this.generateSoapFromTranscription(
        fullTranscription,
        patientSwitch.newPatientName || existingNote.patientName || undefined,
        existingNote
      );

      // Update patient info if detected
      const patientName = soapAnalysis.patientInfo?.name || 
                         patientSwitch.newPatientName || 
                         existingNote.patientName;
      
      const patientId = soapAnalysis.patientInfo?.id || existingNote.patientId;
      const dateOfBirth = soapAnalysis.patientInfo?.dob || existingNote.dateOfBirth;

      // Update the note
      const updatedNote = await storage.updateSoapNote(existingNote.id, {
        fullTranscription,
        patientName,
        patientId,
        dateOfBirth,
        subjective: soapAnalysis.subjective,
        objective: soapAnalysis.objective,
        assessment: soapAnalysis.assessment,
        plan: soapAnalysis.plan,
        patientSwitchDetected: patientSwitch.patientSwitchDetected,
        recordingDuration: (existingNote.recordingDuration || 0) + (transcription.duration || 0),
        confidence: Math.round((soapAnalysis.confidence + patientSwitch.confidence) / 2),
        sessionStatus: "completed",
        completedAt: new Date(),
      });

      return updatedNote;
    } catch (error) {
      console.error("Error processing audio for session:", error);
      throw error;
    }
  }

  /**
   * Gets active session for user or creates new one if patient switch detected
   */
  async getOrCreateActiveSession(
    userId: number,
    audioText?: string
  ): Promise<SoapNote> {
    try {
      const activeSession = await storage.getActiveSoapSession(userId);
      
      if (!activeSession) {
        return await this.createSession(userId);
      }

      // If audio provided, check for patient switch
      if (audioText) {
        const patientSwitch = await this.analyzePatientSwitch(
          audioText,
          activeSession.patientName || undefined
        );

        if (patientSwitch.patientSwitchDetected && patientSwitch.confidence > 70) {
          // Mark current session as completed and create new one
          await storage.updateSoapNote(activeSession.id, {
            sessionStatus: "completed",
            completedAt: new Date(),
          });
          
          return await this.createSession(userId);
        }
      }

      return activeSession;
    } catch (error) {
      console.error("Error getting/creating active session:", error);
      throw error;
    }
  }

  /**
   * Gets all SOAP notes for a user
   */
  async getUserSoapNotes(userId: number): Promise<SoapNote[]> {
    return await storage.getSoapNotes(userId);
  }

  /**
   * Gets a specific SOAP note
   */
  async getSoapNote(id: number): Promise<SoapNote | undefined> {
    return await storage.getSoapNote(id);
  }

  /**
   * Manually marks patient switch for session
   */
  async markPatientSwitch(sessionId: string): Promise<SoapNote> {
    return await storage.markPatientSwitch(sessionId);
  }

  /**
   * Generates progressive SOAP sections for real-time updates
   */
  async generateProgressiveSoapSections(
    recentContext: string,
    newChunk: string
  ): Promise<{
    subjective: string;
    objective: string;
    assessment: string;
    plan: string;
  }> {
    try {
      const prompt = `
You are analyzing a real-time physiotherapy consultation. Based on the recent conversation context and the latest chunk, progressively update the SOAP note sections.

Recent Context (last 5 minutes):
"${recentContext}"

New Information:
"${newChunk}"

Generate updated SOAP sections incorporating the new information. Be concise but comprehensive.
Focus on clinically relevant information and maintain professional medical documentation standards.

Respond with JSON in this format:
{
  "subjective": "Patient's reported symptoms, history, and concerns",
  "objective": "Observable findings, measurements, and test results",
  "assessment": "Clinical analysis and diagnosis",
  "plan": "Treatment plan and recommendations"
}
`;

      const response = await openai.chat.completions.create({
        model: "gpt-4o",
        messages: [
          {
            role: "system",
            content: "You are an expert physiotherapist creating progressive SOAP notes during a live consultation. Update sections as new information becomes available."
          },
          {
            role: "user",
            content: prompt
          }
        ],
        response_format: { type: "json_object" },
        temperature: 0.3,
        max_tokens: 1000
      });

      const result = JSON.parse(response.choices[0].message.content || '{}');
      
      return {
        subjective: result.subjective || '',
        objective: result.objective || '',
        assessment: result.assessment || '',
        plan: result.plan || ''
      };
    } catch (error) {
      console.error("Error generating progressive SOAP sections:", error);
      return {
        subjective: '',
        objective: '',
        assessment: '',
        plan: ''
      };
    }
  }

  /**
   * Generates AI suggestions for real-time assistance
   */
  async generateAISuggestions(context: string): Promise<any[]> {
    try {
      const prompt = `
Based on this physiotherapy consultation context, provide 3-5 clinical suggestions or considerations.

Context:
"${context}"

Focus on:
1. Potential red flags or safety concerns
2. Differential diagnoses to consider
3. Assessment techniques or tests to perform
4. Treatment options or modifications
5. Documentation reminders

Respond with JSON array of suggestions in this format:
[
  {
    "id": "unique_id",
    "type": "assessment|differential|treatment|red-flag|documentation",
    "suggestion": "The specific suggestion",
    "reasoning": "Brief clinical reasoning",
    "priority": "high|normal"
  }
]
`;

      const response = await openai.chat.completions.create({
        model: "gpt-4o",
        messages: [
          {
            role: "system",
            content: "You are an expert physiotherapist providing real-time clinical decision support."
          },
          {
            role: "user",
            content: prompt
          }
        ],
        response_format: { type: "json_object" },
        temperature: 0.4,
        max_tokens: 800
      });

      const result = JSON.parse(response.choices[0].message.content || '{"suggestions":[]}');
      return result.suggestions || [];
    } catch (error) {
      console.error("Error generating AI suggestions:", error);
      return [];
    }
  }

  /**
   * Generates automatic paperwork for a SOAP note using AI
   */
  async generateAutomaticPaperwork(soapNoteId: number): Promise<SoapNote> {
    const soapNote = await storage.getSoapNote(soapNoteId);
    if (!soapNote) {
      throw new Error("SOAP note not found");
    }

    if (soapNote.paperworkGenerated) {
      console.log("Paperwork already generated for this SOAP note");
      return soapNote;
    }

    try {
      // Generate comprehensive paperwork using AI
      const paperwork = await aiPaperworkService.generateAutomaticPaperwork(soapNote);

      // Update the SOAP note with generated paperwork
      const updatedSoapNote = await storage.updateSoapNote(soapNoteId, {
        treatmentSummary: paperwork.treatmentSummary,
        progressNotes: paperwork.progressNotes,
        dischargeSummary: paperwork.dischargeSummary,
        progressReport: paperwork.progressReport,
        imagingReferral: paperwork.imagingReferral,
        specialistReferral: paperwork.specialistReferral,
        returnToWorkCertificate: paperwork.returnToWorkCertificate,
        timeOffWorkCertificate: paperwork.timeOffWorkCertificate,
        insuranceDocumentation: paperwork.insuranceDocumentation,
        homeExerciseProgram: paperwork.homeExerciseProgram,
        workCapacityAssessment: paperwork.workCapacityAssessment,
        functionalOutcomes: paperwork.functionalOutcomes,
        paperworkGenerated: true,
        paperworkGeneratedAt: new Date(),
      });

      return updatedSoapNote;
    } catch (error) {
      console.error("Error generating automatic paperwork:", error);
      throw new Error("Failed to generate automatic paperwork");
    }
  }

  /**
   * Generates a referral letter for a patient
   */
  async generateReferralLetter(
    soapNoteId: number, 
    specialtyType: string, 
    reason: string, 
    urgency: 'routine' | 'urgent' | 'stat',
    clinicalFindings: string
  ): Promise<SoapNote> {
    const soapNote = await storage.getSoapNote(soapNoteId);
    if (!soapNote) {
      throw new Error("SOAP note not found");
    }

    try {
      const referralLetter = await aiPaperworkService.generateReferralLetter(soapNote, {
        specialtyType,
        reason,
        urgency,
        clinicalFindings
      });

      const updatedSoapNote = await storage.updateSoapNote(soapNoteId, {
        referralLetter: referralLetter,
      });

      return updatedSoapNote;
    } catch (error) {
      console.error("Error generating referral letter:", error);
      throw new Error("Failed to generate referral letter");
    }
  }

  /**
   * Generates insurance documentation for a patient
   */
  async generateInsuranceDocumentation(
    soapNoteId: number,
    sessionCount: number = 1
  ): Promise<SoapNote> {
    const soapNote = await storage.getSoapNote(soapNoteId);
    if (!soapNote) {
      throw new Error("SOAP note not found");
    }

    try {
      const insuranceData = await aiPaperworkService.generateInsuranceDocumentation(soapNote, sessionCount);

      const updatedSoapNote = await storage.updateSoapNote(soapNoteId, {
        insuranceDocumentation: `Primary Diagnosis: ${insuranceData.primaryDiagnosis}\n\nSecondary Diagnoses: ${insuranceData.secondaryDiagnoses.join(', ')}\n\nTreatment Codes: ${insuranceData.treatmentCodes.join(', ')}\n\nFunctional Improvements: ${insuranceData.functionalImprovements.join(', ')}\n\nMedical Necessity: ${insuranceData.medicalNecessity}`,
        billingCodes: insuranceData.treatmentCodes,
      });

      return updatedSoapNote;
    } catch (error) {
      console.error("Error generating insurance documentation:", error);
      throw new Error("Failed to generate insurance documentation");
    }
  }

  /**
   * Generates discharge summary for a patient
   */
  async generateDischargeSummary(userId: number, patientName?: string): Promise<string> {
    const allNotes = await storage.getSoapNotes(userId);
    const patientNotes = patientName 
      ? allNotes.filter(note => note.patientName === patientName)
      : allNotes;

    if (patientNotes.length === 0) {
      throw new Error("No SOAP notes found for discharge summary");
    }

    try {
      return await aiPaperworkService.generateDischargeSummary(patientNotes);
    } catch (error) {
      console.error("Error generating discharge summary:", error);
      throw new Error("Failed to generate discharge summary");
    }
  }

  /**
   * Generates progress report for a patient
   */
  async generateProgressReport(
    userId: number,
    reportingPeriod: { start: string; end: string },
    patientName?: string
  ): Promise<string> {
    const allNotes = await storage.getSoapNotes(userId);
    const patientNotes = patientName 
      ? allNotes.filter(note => note.patientName === patientName)
      : allNotes;

    if (patientNotes.length === 0) {
      throw new Error("No SOAP notes found for progress report");
    }

    try {
      return await aiPaperworkService.generateProgressReport(patientNotes, reportingPeriod);
    } catch (error) {
      console.error("Error generating progress report:", error);
      throw new Error("Failed to generate progress report");
    }
  }

  /**
   * Automatically generates paperwork for completed SOAP notes
   */
  async autoGeneratePaperworkForCompletedNotes(userId: number): Promise<void> {
    const soapNotes = await storage.getSoapNotes(userId);
    const completedNotes = soapNotes.filter(note => 
      note.sessionStatus === 'completed' && 
      !note.paperworkGenerated &&
      note.subjective && 
      note.assessment
    );

    for (const note of completedNotes) {
      try {
        await this.generateAutomaticPaperwork(note.id);
        console.log(`Auto-generated paperwork for SOAP note ${note.id}`);
      } catch (error) {
        console.error(`Failed to auto-generate paperwork for SOAP note ${note.id}:`, error);
      }
    }
  }
}

export const soapNotesService = new SoapNotesService();