/**
 * Active Movement Mode
 *
 * One-sentence-per-movement findings stream. Replaces the static-posture
 * Clinical Reasoning panel while in Movement Mode. Each finding is
 * generated by POST /api/movement-findings/summarise and pushed to the
 * top of this list with a fade-in.
 *
 * Drag-to-move (Task #358) reuses the SFV DraggableShell pattern:
 * viewer-relative absolute positioning with offsetParent-bounded
 * clamping, header-only drag (e.target === e.currentTarget so inner
 * controls keep working), and double-click on the empty header area
 * resets to the default top-right slot.
 */
import { useEffect, useRef, useState, useCallback } from 'react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Activity, Trash2, ChevronDown, ChevronUp, GripVertical } from 'lucide-react';

export interface MovementFinding {
  id: string;
  timestamp: number;
  joint: string;
  movement: string;
  achievedAngle: number;
  inPainfulArc: boolean;
  exceededActiveLimit: boolean;
  sentence: string;
  loading?: boolean;
}

interface DragHandlers {
  onMouseDown: (e: React.MouseEvent<HTMLDivElement>) => void;
  onDoubleClick: (e: React.MouseEvent<HTMLDivElement>) => void;
}

interface Props {
  findings: MovementFinding[];
  onClear: () => void;
  className?: string;
  /** Controlled drag position (viewer-relative px, i.e. relative to the
   *  panel's offsetParent). Lifted to the parent so the panel keeps its
   *  position across re-mounts within a session. Pass `null` for the
   *  default top-right slot. */
  position?: { left: number; top: number } | null;
  onPositionChange?: (p: { left: number; top: number } | null) => void;
}

const JOINT_LABEL: Record<string, string> = {
  leftShoulder: 'L Shoulder', rightShoulder: 'R Shoulder',
  leftHip: 'L Hip', rightHip: 'R Hip',
  leftKnee: 'L Knee', rightKnee: 'R Knee',
  leftAnkle: 'L Ankle', rightAnkle: 'R Ankle',
  lumbar_spine: 'Lumbar', cervical_spine: 'Cervical', thoracic_spine: 'Thoracic',
  leftElbow: 'L Elbow', rightElbow: 'R Elbow',
};

export default function MovementFindingsStream({ findings, onClear, className = '', position, onPositionChange }: Props) {
  const [now, setNow] = useState(Date.now());
  const intervalRef = useRef<number>();
  useEffect(() => {
    intervalRef.current = window.setInterval(() => setNow(Date.now()), 5000);
    return () => { if (intervalRef.current) clearInterval(intervalRef.current); };
  }, []);

  // Collapsible UI (Task #320). The panel defaults to collapsed when there
  // are no findings yet so an empty Movement Mode session doesn't visually
  // dominate the 3D skeleton viewer. If findings already exist on mount it
  // starts expanded. After mount it auto-expands exactly once when the
  // first finding arrives, and from there the clinician's manual toggle
  // is the source of truth.
  const [collapsed, setCollapsed] = useState(() => findings.length === 0);
  const userToggledRef = useRef(false);
  const lastCountRef = useRef(findings.length);
  useEffect(() => {
    const prev = lastCountRef.current;
    lastCountRef.current = findings.length;
    if (!userToggledRef.current && prev === 0 && findings.length > 0) {
      setCollapsed(false);
    }
  }, [findings.length]);
  const toggleCollapsed = () => {
    userToggledRef.current = true;
    setCollapsed(c => !c);
  };
  const ChevIcon = collapsed ? ChevronDown : ChevronUp;

  return (
    <DraggableShell position={position ?? null} onPositionChange={onPositionChange} className={className}>
      {(dragHandlers, isDragging) => (
        <Card className="bg-emerald-950/50 border-emerald-700/50 text-emerald-50 flex flex-col overflow-hidden h-full">
          {/* Header background = drag area (only fires when the user
              clicks the bare header, not on any inner control). Collapse
              moved to a dedicated chevron button so drag and click don't
              fight. */}
          <div
            className={`shrink-0 w-full flex items-center justify-between p-3 select-none hover:bg-emerald-900/40 transition-colors ${collapsed ? '' : 'border-b border-emerald-700/40'} ${isDragging ? 'cursor-grabbing' : 'cursor-grab'}`}
            onMouseDown={dragHandlers.onMouseDown}
            onDoubleClick={dragHandlers.onDoubleClick}
            title={position ? 'Drag to move (double-click to reset)' : 'Drag to move'}
            data-testid="movement-findings-toggle"
          >
            <div className="flex items-center gap-2 pointer-events-none">
              <GripVertical className="h-3 w-3 text-emerald-400/70" />
              <Activity className="h-3.5 w-3.5 text-emerald-300" />
              <div className="text-xs font-semibold uppercase tracking-wider text-emerald-200">Movement Findings</div>
              <span className="text-[10px] text-emerald-300/80" data-testid="movement-findings-count">{findings.length}</span>
            </div>
            <div className="flex items-center gap-1">
              {!collapsed && findings.length > 0 && (
                <Button
                  size="sm"
                  variant="ghost"
                  className="h-6 text-[10px] text-emerald-200 hover:bg-emerald-800/40"
                  onMouseDown={(e) => e.stopPropagation()}
                  onClick={(e) => { e.stopPropagation(); onClear(); }}
                  data-testid="clear-movement-findings"
                >
                  <Trash2 className="h-3 w-3 mr-1" />
                  Clear
                </Button>
              )}
              <button
                type="button"
                onMouseDown={(e) => e.stopPropagation()}
                onClick={(e) => { e.stopPropagation(); toggleCollapsed(); }}
                className="rounded p-0.5 hover:bg-emerald-800/60 focus:outline-none focus-visible:ring-2 focus-visible:ring-emerald-400 cursor-pointer"
                aria-expanded={!collapsed}
                aria-label={collapsed ? 'Expand Movement Findings' : 'Collapse Movement Findings'}
                data-testid="movement-findings-collapse-toggle"
                title={collapsed ? 'Expand' : 'Collapse'}
              >
                <ChevIcon className="h-3.5 w-3.5 text-emerald-300" />
              </button>
            </div>
          </div>
          {!collapsed && (
            <ScrollArea className="max-h-[260px]" data-testid="movement-findings-body">
              <div className="p-2 space-y-1.5">
                {findings.length === 0 && (
                  <div className="text-[11px] text-emerald-100/70 italic px-2 py-3 text-center">
                    Drag a joint arrow to record an active movement attempt.
                  </div>
                )}
                {findings.map(f => {
                  const ago = Math.max(0, Math.round((now - f.timestamp) / 1000));
                  const tagColor = f.exceededActiveLimit
                    ? 'bg-rose-500/30 text-rose-200 border-rose-400/40'
                    : f.inPainfulArc
                    ? 'bg-amber-500/30 text-amber-200 border-amber-400/40'
                    : 'bg-emerald-500/20 text-emerald-200 border-emerald-400/30';
                  return (
                    <div
                      key={f.id}
                      className="rounded border border-emerald-800/50 bg-emerald-900/40 px-2 py-1.5 text-[11px] animate-in fade-in slide-in-from-top-1 duration-200"
                      data-testid={`finding-${f.id}`}
                    >
                      <div className="flex items-center justify-between gap-2 mb-1">
                        <span className={`text-[9px] uppercase tracking-wide rounded border px-1 py-0.5 ${tagColor}`}>
                          {(JOINT_LABEL[f.joint] ?? f.joint)} · {f.movement} · {Math.round(f.achievedAngle)}°
                        </span>
                        <span className="text-[9px] text-emerald-300/70">{ago}s ago</span>
                      </div>
                      <div className="text-emerald-50">
                        {f.loading ? (
                          <span className="text-emerald-200/70 italic">Summarising…</span>
                        ) : (
                          f.sentence
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            </ScrollArea>
          )}
        </Card>
      )}
    </DraggableShell>
  );
}

interface DraggableShellProps {
  position: { left: number; top: number } | null;
  onPositionChange?: (p: { left: number; top: number } | null) => void;
  className?: string;
  children: (h: DragHandlers, isDragging: boolean) => React.ReactNode;
}

/**
 * Mirrors the SFV panel's DraggableShell exactly: viewer-relative
 * absolute positioning so the panel can never leave the viewer (offset-
 * parent based clamping), header-only drag (e.target === e.currentTarget
 * gate), and double-click on the empty header area resets to default.
 */
function DraggableShell({ position, onPositionChange, className = '', children }: DraggableShellProps) {
  const [dragging, setDragging] = useState(false);
  const dragStateRef = useRef<{
    pointerStartX: number;
    pointerStartY: number;
    panelStartLeft: number;
    panelStartTop: number;
    container: HTMLElement | null;
  } | null>(null);
  const panelRef = useRef<HTMLDivElement | null>(null);

  const onMouseDown = useCallback((e: React.MouseEvent<HTMLDivElement>) => {
    if (e.target !== e.currentTarget) return;
    if (e.button !== 0) return;
    const panel = panelRef.current;
    if (!panel) return;
    const rect = panel.getBoundingClientRect();
    const container = (panel.offsetParent as HTMLElement | null) ?? null;
    const containerRect = container?.getBoundingClientRect();
    dragStateRef.current = {
      pointerStartX: e.clientX,
      pointerStartY: e.clientY,
      panelStartLeft: rect.left - (containerRect?.left ?? 0),
      panelStartTop: rect.top - (containerRect?.top ?? 0),
      container,
    };
    setDragging(true);
    e.preventDefault();
  }, []);

  const onDoubleClick = useCallback((e: React.MouseEvent<HTMLDivElement>) => {
    if (e.target !== e.currentTarget) return;
    onPositionChange?.(null);
  }, [onPositionChange]);

  useEffect(() => {
    if (!dragging) return;
    const handleMove = (ev: MouseEvent) => {
      const ds = dragStateRef.current;
      if (!ds) return;
      const dx = ev.clientX - ds.pointerStartX;
      const dy = ev.clientY - ds.pointerStartY;
      const panel = panelRef.current;
      const w = panel?.offsetWidth ?? 340;
      const h = panel?.offsetHeight ?? 200;
      const containerRect = ds.container?.getBoundingClientRect();
      const containerW = containerRect?.width ?? window.innerWidth;
      const containerH = containerRect?.height ?? window.innerHeight;
      const minX = 4;
      const minY = 4;
      const maxX = Math.max(minX, containerW - w - 4);
      const maxY = Math.max(minY, containerH - h - 4);
      const nextLeft = Math.max(minX, Math.min(maxX, ds.panelStartLeft + dx));
      const nextTop = Math.max(minY, Math.min(maxY, ds.panelStartTop + dy));
      onPositionChange?.({ left: nextLeft, top: nextTop });
      if (!onPositionChange && panel) {
        panel.style.left = `${nextLeft}px`;
        panel.style.top = `${nextTop}px`;
        panel.style.right = 'auto';
      }
    };
    const handleUp = () => {
      setDragging(false);
      dragStateRef.current = null;
    };
    window.addEventListener('mousemove', handleMove);
    window.addEventListener('mouseup', handleUp);
    return () => {
      window.removeEventListener('mousemove', handleMove);
      window.removeEventListener('mouseup', handleUp);
    };
  }, [dragging, onPositionChange]);

  // Default placement matches the original right-rail slot: the green
  // Movement Findings card sat directly under the (collapsed) Movement
  // AI Simulator panel, ~5.5rem from the top of the viewer frame.
  const style: React.CSSProperties = position
    ? { left: position.left, top: position.top }
    : { top: '5.5rem', right: '0.5rem' };

  return (
    <div
      ref={panelRef}
      className={`absolute z-30 w-[340px] rounded-xl ${dragging ? 'shadow-emerald-500/30 ring-1 ring-emerald-500/40 shadow-2xl' : ''} ${className}`}
      style={style}
      data-testid="movement-findings-panel"
    >
      {children({ onMouseDown, onDoubleClick }, dragging)}
    </div>
  );
}
