/**
 * Task #301 — Active Movement Mode
 *
 * One-sentence-per-movement findings stream. Replaces the static-posture
 * Clinical Reasoning panel while in Movement Mode. Each finding is
 * generated by POST /api/movement-findings/summarise and pushed to the
 * top of this list with a fade-in.
 */
import { useEffect, useRef, useState } from 'react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Activity, Trash2 } from 'lucide-react';

export interface MovementFinding {
  id: string;
  timestamp: number;
  joint: string;
  movement: string;
  achievedAngle: number;
  inPainfulArc: boolean;
  exceededActiveLimit: boolean;
  sentence: string;
  loading?: boolean;
}

interface Props {
  findings: MovementFinding[];
  onClear: () => void;
  className?: string;
}

const JOINT_LABEL: Record<string, string> = {
  leftShoulder: 'L Shoulder', rightShoulder: 'R Shoulder',
  leftHip: 'L Hip', rightHip: 'R Hip',
  leftKnee: 'L Knee', rightKnee: 'R Knee',
  leftAnkle: 'L Ankle', rightAnkle: 'R Ankle',
  lumbar_spine: 'Lumbar', cervical_spine: 'Cervical', thoracic_spine: 'Thoracic',
  leftElbow: 'L Elbow', rightElbow: 'R Elbow',
};

export default function MovementFindingsStream({ findings, onClear, className = '' }: Props) {
  const [now, setNow] = useState(Date.now());
  const intervalRef = useRef<number>();
  useEffect(() => {
    intervalRef.current = window.setInterval(() => setNow(Date.now()), 5000);
    return () => { if (intervalRef.current) clearInterval(intervalRef.current); };
  }, []);

  return (
    <Card className={`bg-emerald-950/50 border-emerald-700/50 text-emerald-50 ${className}`}>
      <div className="flex items-center justify-between p-3 border-b border-emerald-700/40">
        <div className="flex items-center gap-2">
          <Activity className="h-3.5 w-3.5 text-emerald-300" />
          <div className="text-xs font-semibold uppercase tracking-wider text-emerald-200">Movement Findings</div>
          <span className="text-[10px] text-emerald-300/80">{findings.length}</span>
        </div>
        {findings.length > 0 && (
          <Button
            size="sm"
            variant="ghost"
            className="h-6 text-[10px] text-emerald-200 hover:bg-emerald-800/40"
            onClick={onClear}
            data-testid="clear-movement-findings"
          >
            <Trash2 className="h-3 w-3 mr-1" />
            Clear
          </Button>
        )}
      </div>
      <ScrollArea className="max-h-[260px]">
        <div className="p-2 space-y-1.5">
          {findings.length === 0 && (
            <div className="text-[11px] text-emerald-100/70 italic px-2 py-3 text-center">
              Drag a joint arrow to record an active movement attempt.
            </div>
          )}
          {findings.map(f => {
            const ago = Math.max(0, Math.round((now - f.timestamp) / 1000));
            const tagColor = f.exceededActiveLimit
              ? 'bg-rose-500/30 text-rose-200 border-rose-400/40'
              : f.inPainfulArc
              ? 'bg-amber-500/30 text-amber-200 border-amber-400/40'
              : 'bg-emerald-500/20 text-emerald-200 border-emerald-400/30';
            return (
              <div
                key={f.id}
                className="rounded border border-emerald-800/50 bg-emerald-900/40 px-2 py-1.5 text-[11px] animate-in fade-in slide-in-from-top-1 duration-200"
                data-testid={`finding-${f.id}`}
              >
                <div className="flex items-center justify-between gap-2 mb-1">
                  <span className={`text-[9px] uppercase tracking-wide rounded border px-1 py-0.5 ${tagColor}`}>
                    {(JOINT_LABEL[f.joint] ?? f.joint)} · {f.movement} · {Math.round(f.achievedAngle)}°
                  </span>
                  <span className="text-[9px] text-emerald-300/70">{ago}s ago</span>
                </div>
                <div className="text-emerald-50">
                  {f.loading ? (
                    <span className="text-emerald-200/70 italic">Summarising…</span>
                  ) : (
                    f.sentence
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </ScrollArea>
    </Card>
  );
}
