/**
 * Active Movement Mode
 *
 * One-sentence-per-movement findings stream. Replaces the static-posture
 * Clinical Reasoning panel while in Movement Mode. Each finding is
 * generated by POST /api/movement-findings/summarise and pushed to the
 * top of this list with a fade-in.
 */
import { useEffect, useRef, useState, useCallback } from 'react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Activity, Trash2, ChevronDown, ChevronUp, GripVertical } from 'lucide-react';

export interface MovementFinding {
  id: string;
  timestamp: number;
  joint: string;
  movement: string;
  achievedAngle: number;
  inPainfulArc: boolean;
  exceededActiveLimit: boolean;
  sentence: string;
  loading?: boolean;
}

interface Props {
  findings: MovementFinding[];
  onClear: () => void;
  className?: string;
  /** Controlled drag position (viewport-fixed px). Lifted to the parent so
   *  the panel keeps its position across re-mounts (e.g. toggling skeleton
   *  modes) within a session. Pass `null` for the default rail slot. */
  position?: { left: number; top: number } | null;
  onPositionChange?: (p: { left: number; top: number } | null) => void;
}

const JOINT_LABEL: Record<string, string> = {
  leftShoulder: 'L Shoulder', rightShoulder: 'R Shoulder',
  leftHip: 'L Hip', rightHip: 'R Hip',
  leftKnee: 'L Knee', rightKnee: 'R Knee',
  leftAnkle: 'L Ankle', rightAnkle: 'R Ankle',
  lumbar_spine: 'Lumbar', cervical_spine: 'Cervical', thoracic_spine: 'Thoracic',
  leftElbow: 'L Elbow', rightElbow: 'R Elbow',
};

const PANEL_W = 340;

export default function MovementFindingsStream({ findings, onClear, className = '', position, onPositionChange }: Props) {
  const [now, setNow] = useState(Date.now());
  const intervalRef = useRef<number>();
  useEffect(() => {
    intervalRef.current = window.setInterval(() => setNow(Date.now()), 5000);
    return () => { if (intervalRef.current) clearInterval(intervalRef.current); };
  }, []);

  // Collapsible UI (Task #320). The panel defaults to collapsed when there
  // are no findings yet so an empty Movement Mode session doesn't visually
  // dominate the 3D skeleton viewer. If findings already exist on mount
  // (e.g. a previous session restored them) it starts expanded. After mount
  // it auto-expands exactly once when the first finding arrives, and from
  // there the clinician's manual toggle is the source of truth. State is
  // per-mount, so leaving and re-entering Movement Mode resets the default.
  const [collapsed, setCollapsed] = useState(() => findings.length === 0);
  const userToggledRef = useRef(false);
  const lastCountRef = useRef(findings.length);
  useEffect(() => {
    const prev = lastCountRef.current;
    lastCountRef.current = findings.length;
    if (!userToggledRef.current && prev === 0 && findings.length > 0) {
      setCollapsed(false);
    }
  }, [findings.length]);
  const toggleCollapsed = () => {
    userToggledRef.current = true;
    setCollapsed(c => !c);
  };
  const ChevIcon = collapsed ? ChevronDown : ChevronUp;

  // Drag-to-move (Task #358). Mirrors MovementAiSimulatorPanel pattern:
  // default state is a regular flow child of the right rail; once the user
  // grabs the header, switches to position:fixed and the user can place
  // the panel anywhere within the viewport. Position is lifted to the
  // parent so it survives skeleton-mode re-mounts within a session. Double-
  // click on the header (away from buttons) resets to the default rail slot.
  const rootRef = useRef<HTMLDivElement | null>(null);
  const [isDragging, setIsDragging] = useState(false);
  const dragOffset = useRef({ x: 0, y: 0 });
  const dragMovedRef = useRef(false);

  const handleDragStart = useCallback((e: React.MouseEvent) => {
    // Skip drag if the user clicked on an interactive control inside the
    // header (e.g. the chevron collapse/expand button or the Clear button).
    if ((e.target as HTMLElement).closest('button, a, input, textarea, select, [data-no-drag="true"]')) return;
    if (e.button !== 0) return;
    e.preventDefault();
    const panelEl = rootRef.current;
    if (!panelEl) return;
    const rect = panelEl.getBoundingClientRect();
    dragOffset.current = { x: e.clientX - rect.left, y: e.clientY - rect.top };
    dragMovedRef.current = false;
    // Seed position with the panel's current viewport position so the first
    // mousemove doesn't jump it across the screen.
    onPositionChange?.({ left: rect.left, top: rect.top });
    setIsDragging(true);
  }, [onPositionChange]);

  useEffect(() => {
    if (!isDragging) return;
    const handleMove = (e: MouseEvent) => {
      let left = e.clientX - dragOffset.current.x;
      let top = e.clientY - dragOffset.current.y;
      // Clamp so the panel stays on-screen and below the top app bar (~64px).
      left = Math.max(8, Math.min(left, window.innerWidth - PANEL_W - 8));
      top = Math.max(64, Math.min(top, window.innerHeight - 80));
      dragMovedRef.current = true;
      onPositionChange?.({ left, top });
    };
    const handleUp = () => setIsDragging(false);
    document.addEventListener('mousemove', handleMove);
    document.addEventListener('mouseup', handleUp);
    return () => {
      document.removeEventListener('mousemove', handleMove);
      document.removeEventListener('mouseup', handleUp);
    };
  }, [isDragging, onPositionChange]);

  const handleHeaderDoubleClick = useCallback((e: React.MouseEvent) => {
    if ((e.target as HTMLElement).closest('button, a, input, textarea, select, [data-no-drag="true"]')) return;
    onPositionChange?.(null);
  }, [onPositionChange]);

  const panelStyle: React.CSSProperties = position
    ? {
        position: 'fixed',
        left: position.left,
        top: position.top,
        right: 'auto',
        width: PANEL_W,
        zIndex: 50,
        maxHeight: `calc(100vh - ${position.top + 16}px)`,
      }
    : {};

  return (
    <Card
      ref={rootRef}
      className={`bg-emerald-950/50 border-emerald-700/50 text-emerald-50 flex flex-col overflow-hidden ${className}`}
      style={panelStyle}
      data-testid="movement-findings-panel"
    >
      {/* Header doubles as drag handle (mousedown) — collapse is moved off
          the header onClick onto a dedicated chevron button so drag and
          click don't fight. Same pattern as MovementAiSimulatorPanel. */}
      <div
        className={`shrink-0 w-full flex items-center justify-between p-3 select-none hover:bg-emerald-900/40 transition-colors ${collapsed ? '' : 'border-b border-emerald-700/40'} ${isDragging ? 'cursor-grabbing' : 'cursor-grab'}`}
        onMouseDown={handleDragStart}
        onDoubleClick={handleHeaderDoubleClick}
        title={position ? 'Drag to move (double-click to reset)' : 'Drag to move'}
        data-testid="movement-findings-toggle"
      >
        <div className="flex items-center gap-2">
          <GripVertical className="h-3 w-3 text-emerald-400/70" />
          <Activity className="h-3.5 w-3.5 text-emerald-300" />
          <div className="text-xs font-semibold uppercase tracking-wider text-emerald-200">Movement Findings</div>
          <span className="text-[10px] text-emerald-300/80" data-testid="movement-findings-count">{findings.length}</span>
        </div>
        <div className="flex items-center gap-1" data-no-drag="true">
          {!collapsed && findings.length > 0 && (
            <Button
              size="sm"
              variant="ghost"
              className="h-6 text-[10px] text-emerald-200 hover:bg-emerald-800/40"
              onMouseDown={(e) => e.stopPropagation()}
              onClick={(e) => { e.stopPropagation(); onClear(); }}
              data-testid="clear-movement-findings"
            >
              <Trash2 className="h-3 w-3 mr-1" />
              Clear
            </Button>
          )}
          <button
            type="button"
            onMouseDown={(e) => e.stopPropagation()}
            onClick={(e) => { e.stopPropagation(); toggleCollapsed(); }}
            className="rounded p-0.5 hover:bg-emerald-800/60 focus:outline-none focus-visible:ring-2 focus-visible:ring-emerald-400 cursor-pointer"
            aria-expanded={!collapsed}
            aria-label={collapsed ? 'Expand Movement Findings' : 'Collapse Movement Findings'}
            data-testid="movement-findings-collapse-toggle"
            title={collapsed ? 'Expand' : 'Collapse'}
          >
            <ChevIcon className="h-3.5 w-3.5 text-emerald-300" />
          </button>
        </div>
      </div>
      {!collapsed && (
      <ScrollArea className="max-h-[260px]" data-testid="movement-findings-body">
        <div className="p-2 space-y-1.5">
          {findings.length === 0 && (
            <div className="text-[11px] text-emerald-100/70 italic px-2 py-3 text-center">
              Drag a joint arrow to record an active movement attempt.
            </div>
          )}
          {findings.map(f => {
            const ago = Math.max(0, Math.round((now - f.timestamp) / 1000));
            const tagColor = f.exceededActiveLimit
              ? 'bg-rose-500/30 text-rose-200 border-rose-400/40'
              : f.inPainfulArc
              ? 'bg-amber-500/30 text-amber-200 border-amber-400/40'
              : 'bg-emerald-500/20 text-emerald-200 border-emerald-400/30';
            return (
              <div
                key={f.id}
                className="rounded border border-emerald-800/50 bg-emerald-900/40 px-2 py-1.5 text-[11px] animate-in fade-in slide-in-from-top-1 duration-200"
                data-testid={`finding-${f.id}`}
              >
                <div className="flex items-center justify-between gap-2 mb-1">
                  <span className={`text-[9px] uppercase tracking-wide rounded border px-1 py-0.5 ${tagColor}`}>
                    {(JOINT_LABEL[f.joint] ?? f.joint)} · {f.movement} · {Math.round(f.achievedAngle)}°
                  </span>
                  <span className="text-[9px] text-emerald-300/70">{ago}s ago</span>
                </div>
                <div className="text-emerald-50">
                  {f.loading ? (
                    <span className="text-emerald-200/70 italic">Summarising…</span>
                  ) : (
                    f.sentence
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </ScrollArea>
      )}
    </Card>
  );
}
