import { db } from "../db";
import { competitions, gameContent } from "../../shared/schema";

async function addGameCompetitions() {
  console.log('Adding lightning diagnosis and mystery patient competitions...');

  // Lightning Diagnosis Games
  const lightningDiagnosisGames = [
    {
      title: "Lightning Diagnosis: Shoulder Pain Challenge",
      description: "Rapid 30-second diagnosis challenges for shoulder conditions",
      gameType: "lightning_diagnosis",
      bodyPart: "shoulder",
      difficulty: "intermediate",
      timeLimit: 300, // 5 minutes
      maxParticipants: 100,
      status: "active"
    },
    {
      title: "Lightning Diagnosis: Knee Pain Sprint",
      description: "Quick-fire knee pain diagnostic scenarios under time pressure",
      gameType: "lightning_diagnosis", 
      bodyPart: "knee",
      difficulty: "advanced",
      timeLimit: 240, // 4 minutes
      maxParticipants: 100,
      status: "active"
    },
    {
      title: "Lightning Diagnosis: Back Pain Blitz",
      description: "Rapid-fire back pain diagnosis challenges for all levels",
      gameType: "lightning_diagnosis",
      bodyPart: "back", 
      difficulty: "intermediate",
      timeLimit: 360, // 6 minutes
      maxParticipants: 100,
      status: "active"
    },
    {
      title: "Lightning Diagnosis: Neck Pain Express",
      description: "Speed diagnosis challenges for cervical spine conditions",
      gameType: "lightning_diagnosis",
      bodyPart: "neck",
      difficulty: "beginner", 
      timeLimit: 300, // 5 minutes
      maxParticipants: 100,
      status: "active"
    },
    {
      title: "Lightning Diagnosis: Hip Pain Rush",
      description: "Fast-paced hip pathology identification under pressure",
      gameType: "lightning_diagnosis",
      bodyPart: "hip",
      difficulty: "advanced",
      timeLimit: 420, // 7 minutes  
      maxParticipants: 100,
      status: "active"
    }
  ];

  // Mystery Patient Games  
  const mysteryPatientGames = [
    {
      title: "Mystery Patient: The Overhead Athlete",
      description: "Solve complex shoulder case with gradually revealed clues",
      gameType: "mystery_patient",
      bodyPart: "shoulder", 
      difficulty: "advanced",
      timeLimit: 900, // 15 minutes
      maxParticipants: 50,
      status: "active"
    },
    {
      title: "Mystery Patient: The Weekend Warrior",
      description: "Uncover the diagnosis in this recreational athlete's knee injury",
      gameType: "mystery_patient",
      bodyPart: "knee",
      difficulty: "intermediate",
      timeLimit: 720, // 12 minutes
      maxParticipants: 50, 
      status: "active"
    },
    {
      title: "Mystery Patient: The Office Worker",
      description: "Progressive clue revelation for chronic back pain case",
      gameType: "mystery_patient", 
      bodyPart: "back",
      difficulty: "intermediate",
      timeLimit: 600, // 10 minutes
      maxParticipants: 50,
      status: "active"
    },
    {
      title: "Mystery Patient: The Construction Worker", 
      description: "Multi-site injury mystery requiring careful analysis",
      gameType: "mystery_patient",
      bodyPart: "general",
      difficulty: "advanced", 
      timeLimit: 1080, // 18 minutes
      maxParticipants: 50,
      status: "active"
    },
    {
      title: "Mystery Patient: The Elderly Fall",
      description: "Complex geriatric case with multiple differential diagnoses",
      gameType: "mystery_patient",
      bodyPart: "hip",
      difficulty: "advanced",
      timeLimit: 900, // 15 minutes
      maxParticipants: 30,
      status: "active"
    }
  ];

  try {
    // Insert Lightning Diagnosis competitions
    for (const game of lightningDiagnosisGames) {
      const [competition] = await db.insert(competitions).values({
        title: game.title,
        description: game.description,
        type: "daily_challenge",
        gameType: game.gameType,
        status: game.status,
        bodyPart: game.bodyPart as any,
        difficulty: game.difficulty as any,
        timeLimit: game.timeLimit,
        maxParticipants: game.maxParticipants,
        currentParticipants: 0,
        entryFee: 0,
        prizePool: 0,
        startTime: new Date(),
        endTime: new Date(Date.now() + 24 * 60 * 60 * 1000), // 24 hours from now
        caseStudyIds: [],
        caseType: "simple",
        isAutoGenerated: true,
        rules: {}
      }).returning();

      console.log(`Created Lightning Diagnosis competition: ${competition.title}`);
    }

    // Insert Mystery Patient competitions  
    for (const game of mysteryPatientGames) {
      const [competition] = await db.insert(competitions).values({
        title: game.title,
        description: game.description, 
        type: "specialty_league",
        gameType: game.gameType,
        status: game.status,
        bodyPart: game.bodyPart as any,
        difficulty: game.difficulty as any,
        timeLimit: game.timeLimit,
        maxParticipants: game.maxParticipants,
        currentParticipants: 0,
        entryFee: 0,
        prizePool: 0,
        startTime: new Date(),
        endTime: new Date(Date.now() + 24 * 60 * 60 * 1000), // 24 hours from now
        caseStudyIds: [],
        caseType: "simple", 
        isAutoGenerated: true,
        rules: {}
      }).returning();

      console.log(`Created Mystery Patient competition: ${competition.title}`);
    }

    console.log('✓ Successfully added all game competitions');
    
  } catch (error) {
    console.error('Error adding game competitions:', error);
    throw error;
  }
}

// Run the function
addGameCompetitions()
  .then(() => {
    console.log('Game competitions setup complete');
  })
  .catch((error) => {
    console.error('Failed to setup game competitions:', error);
  });

export { addGameCompetitions };