import { db } from '../db';
import { competitions, gameContent } from '../../shared/schema';
import { gameContentGenerator } from '../gameContentGenerator';

/**
 * Add Manual Therapy and Exercise Prescription competitions
 */

const manualTherapyCompetitions = [
  {
    title: 'Manual Therapy Mastery: Spine Specialists',
    description: 'Advanced manual therapy decision-making for complex spinal conditions',
    gameType: 'manual_therapy_mastery',
    bodyPart: 'back',
    difficulty: 'advanced',
    timeLimit: 20,
    maxParticipants: 15
  },
  {
    title: 'Manual Therapy Mastery: Shoulder Complex',
    description: 'Elite manual therapy techniques for shoulder and upper extremity conditions',
    gameType: 'manual_therapy_mastery',
    bodyPart: 'shoulder',
    difficulty: 'advanced',
    timeLimit: 18,
    maxParticipants: 15
  },
  {
    title: 'Manual Therapy Mastery: Cervical Spine',
    description: 'Expert-level cervical spine manual therapy with safety considerations',
    gameType: 'manual_therapy_mastery',
    bodyPart: 'neck',
    difficulty: 'advanced',
    timeLimit: 15,
    maxParticipants: 12
  },
  {
    title: 'Manual Therapy Mastery: Lower Extremity',
    description: 'Advanced manual therapy for hip, knee, and ankle complex conditions',
    gameType: 'manual_therapy_mastery',
    bodyPart: 'hip',
    difficulty: 'advanced',
    timeLimit: 22,
    maxParticipants: 15
  }
];

const exercisePrescriptionCompetitions = [
  {
    title: 'Exercise Prescription Expert: Athletic Recovery',
    description: 'Advanced exercise prescription for return-to-sport scenarios',
    gameType: 'exercise_prescription_expert',
    bodyPart: 'knee',
    difficulty: 'advanced',
    timeLimit: 25,
    maxParticipants: 20
  },
  {
    title: 'Exercise Prescription Expert: Chronic Pain Management',
    description: 'Evidence-based exercise prescription for complex chronic conditions',
    gameType: 'exercise_prescription_expert',
    bodyPart: 'back',
    difficulty: 'advanced',
    timeLimit: 30,
    maxParticipants: 20
  },
  {
    title: 'Exercise Prescription Expert: Geriatric Rehabilitation',
    description: 'Specialized exercise programming for older adult populations',
    gameType: 'exercise_prescription_expert',
    bodyPart: 'general',
    difficulty: 'advanced',
    timeLimit: 25,
    maxParticipants: 18
  },
  {
    title: 'Exercise Prescription Expert: Post-Surgical Protocols',
    description: 'Progressive exercise design for post-operative rehabilitation',
    gameType: 'exercise_prescription_expert',
    bodyPart: 'shoulder',
    difficulty: 'advanced',
    timeLimit: 28,
    maxParticipants: 16
  }
];

async function addManualTherapyCompetitions() {
  console.log('🏆 Adding Manual Therapy Mastery competitions...');
  
  try {
    // Add Manual Therapy competitions
    for (const comp of manualTherapyCompetitions) {
      console.log(`\n📝 Creating: ${comp.title}`);
      
      // Create competition
      const [newCompetition] = await db.insert(competitions).values({
        title: comp.title,
        description: comp.description,
        type: "daily_challenge",
        gameType: comp.gameType as any,
        status: "active",
        bodyPart: comp.bodyPart as any,
        difficulty: comp.difficulty as any,
        timeLimit: comp.timeLimit,
        maxParticipants: comp.maxParticipants,
        currentParticipants: 0,
        entryFee: 0,
        prizePool: 0,
        startTime: new Date(),
        endTime: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000), // 14 days from now
        caseStudyIds: [],
        caseType: "simple",
        isAutoGenerated: false,
        rules: {}
      }).returning();

      // Generate content using AI
      const content = await gameContentGenerator.generateGameContent({
        gameType: comp.gameType,
        bodyPart: comp.bodyPart,
        difficulty: comp.difficulty
      });

      // Create game content
      await db.insert(gameContent).values({
        competitionId: newCompetition.id,
        gameType: comp.gameType as any,
        content: content,
        createdAt: new Date(),
        updatedAt: new Date()
      });

      console.log(`✅ Created Manual Therapy competition: ${comp.title}`);
    }

    console.log('\n🏃‍♂️ Adding Exercise Prescription Expert competitions...');
    
    // Add Exercise Prescription competitions
    for (const comp of exercisePrescriptionCompetitions) {
      console.log(`\n📝 Creating: ${comp.title}`);
      
      // Create competition
      const [newCompetition] = await db.insert(competitions).values({
        title: comp.title,
        description: comp.description,
        type: "daily_challenge",
        gameType: comp.gameType as any,
        status: "active",
        bodyPart: comp.bodyPart as any,
        difficulty: comp.difficulty as any,
        timeLimit: comp.timeLimit,
        maxParticipants: comp.maxParticipants,
        currentParticipants: 0,
        entryFee: 0,
        prizePool: 0,
        startTime: new Date(),
        endTime: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000), // 14 days from now
        caseStudyIds: [],
        caseType: "simple",
        isAutoGenerated: false,
        rules: {}
      }).returning();

      // Generate content using AI
      const content = await gameContentGenerator.generateGameContent({
        gameType: comp.gameType,
        bodyPart: comp.bodyPart,
        difficulty: comp.difficulty
      });

      // Create game content
      await db.insert(gameContent).values({
        competitionId: newCompetition.id,
        gameType: comp.gameType as any,
        content: content,
        createdAt: new Date(),
        updatedAt: new Date()
      });

      console.log(`✅ Created Exercise Prescription competition: ${comp.title}`);
    }

    console.log('\n🎯 Summary:');
    console.log(`✅ Added ${manualTherapyCompetitions.length} Manual Therapy Mastery competitions`);
    console.log(`✅ Added ${exercisePrescriptionCompetitions.length} Exercise Prescription Expert competitions`);
    console.log(`🏆 Total new elite competitions: ${manualTherapyCompetitions.length + exercisePrescriptionCompetitions.length}`);
    
    console.log('\n🔥 Elite competition offerings now include:');
    console.log('• Manual Therapy Mastery (spine, shoulder, cervical, lower extremity)');
    console.log('• Exercise Prescription Expert (athletic recovery, chronic pain, geriatric, post-surgical)');
    console.log('• Red Flag Detective');
    console.log('• Differential Diagnosis Duel');
    console.log('• Emergency Room Simulator');
    console.log('• Diagnosis Duel Tournaments');

  } catch (error) {
    console.error('❌ Error adding manual therapy competitions:', error);
    throw error;
  }
}

// Run the script
addManualTherapyCompetitions()
  .then(() => {
    console.log('\n🎉 Manual Therapy and Exercise Prescription competitions added successfully!');
    process.exit(0);
  })
  .catch((error) => {
    console.error('❌ Failed to add competitions:', error);
    process.exit(1);
  });