import { db } from '../db.js';
import { competitions, gameContent } from '@shared/schema';
import { gameContentGenerator } from '../gameContentGenerator.js';

const progressiveDiagnosticChallenges = [
  {
    title: "Progressive Diagnostic Challenge: Shoulder Mystery",
    description: "Work as a clinical detective to uncover the shoulder diagnosis through strategic questioning and testing",
    bodyPart: "shoulder",
    difficulty: "intermediate",
    timeLimit: 25, // 25 minutes
  },
  {
    title: "Progressive Diagnostic Challenge: Knee Investigation", 
    description: "Use your clinical reasoning skills to diagnose complex knee conditions step by step",
    bodyPart: "knee",
    difficulty: "advanced",
    timeLimit: 30, // 30 minutes
  },
  {
    title: "Progressive Diagnostic Challenge: Back Pain Detective",
    description: "Navigate through symptoms and tests to identify serious spinal pathology",
    bodyPart: "back", 
    difficulty: "advanced",
    timeLimit: 35, // 35 minutes
  },
  {
    title: "Progressive Diagnostic Challenge: Hip Puzzle",
    description: "Solve complex hip pain cases through systematic clinical investigation",
    bodyPart: "hip",
    difficulty: "intermediate", 
    timeLimit: 25, // 25 minutes
  },
  {
    title: "Progressive Diagnostic Challenge: Ankle Investigation",
    description: "Uncover ankle and foot pathology through strategic diagnostic approach",
    bodyPart: "ankle",
    difficulty: "beginner",
    timeLimit: 20, // 20 minutes
  }
];

async function addProgressiveDiagnosticChallenges() {
  try {
    console.log('Adding Progressive Diagnostic Challenge competitions...');
    
    for (const challenge of progressiveDiagnosticChallenges) {
      // Create competition
      const [competition] = await db.insert(competitions).values({
        title: challenge.title,
        description: challenge.description,
        type: "daily_challenge",
        gameType: "progressive_diagnostic_challenge",
        status: "active",
        bodyPart: challenge.bodyPart as any,
        difficulty: challenge.difficulty,
        timeLimit: challenge.timeLimit,
        maxParticipants: 25, // Smaller groups for complex challenges
        currentParticipants: 0,
        entryFee: 0,
        prizePool: 0,
        startTime: new Date(),
        endTime: new Date(Date.now() + 72 * 60 * 60 * 1000), // 72 hours from now
        caseStudyIds: [],
        caseType: "simple",
        isAutoGenerated: false,
        rules: {
          scoringWeights: {
            efficiency: 25,
            thoroughness: 25,
            safety: 30,
            accuracy: 20
          },
          allowedAttempts: 1, // One attempt only for challenge
          showLeaderboard: true,
          revealAnswers: true,
          stageTimeLimit: challenge.timeLimit
        }
      }).returning();

      console.log(`Created competition: ${competition.title}`);

      // Generate AI content for this challenge
      const generatedContent = await gameContentGenerator.generateGameContent({
        gameType: 'progressive_diagnostic_challenge',
        bodyPart: challenge.bodyPart,
        difficulty: challenge.difficulty
      });

      // Store game content
      await db.insert(gameContent).values({
        competitionId: competition.id,
        gameType: 'progressive_diagnostic_challenge',
        content: { progressiveDiagnosticChallenge: generatedContent }
      });

      console.log(`✓ Added content for: ${competition.title}`);
    }

    console.log('✓ Successfully added all Progressive Diagnostic Challenge competitions');
    
  } catch (error) {
    console.error('Error adding Progressive Diagnostic Challenges:', error);
    throw error;
  }
}

// Run the function
addProgressiveDiagnosticChallenges()
  .then(() => {
    console.log('Progressive Diagnostic Challenge setup complete');
    process.exit(0);
  })
  .catch((error) => {
    console.error('Failed to setup Progressive Diagnostic Challenges:', error);
    process.exit(1);
  });

export { addProgressiveDiagnosticChallenges };