import { db } from '../db.js';
import { competitions } from '@shared/schema';

const remainingChallenges = [
  {
    title: "Progressive Diagnostic Challenge: Knee Investigation", 
    description: "Use your clinical reasoning skills to diagnose complex knee conditions step by step",
    bodyPart: "knee",
    difficulty: "advanced",
    timeLimit: 30,
  },
  {
    title: "Progressive Diagnostic Challenge: Back Pain Detective",
    description: "Navigate through symptoms and tests to identify serious spinal pathology",
    bodyPart: "back", 
    difficulty: "advanced",
    timeLimit: 35,
  },
  {
    title: "Progressive Diagnostic Challenge: Hip Puzzle",
    description: "Solve complex hip pain cases through systematic clinical investigation",
    bodyPart: "hip",
    difficulty: "intermediate", 
    timeLimit: 25,
  },
  {
    title: "Progressive Diagnostic Challenge: Ankle Investigation",
    description: "Uncover ankle and foot pathology through strategic diagnostic approach",
    bodyPart: "ankle",
    difficulty: "beginner",
    timeLimit: 20,
  }
];

async function addRemainingProgressiveCompetitions() {
  try {
    console.log('Adding remaining Progressive Diagnostic Challenge competitions...');
    
    for (const challenge of remainingChallenges) {
      // Create competition
      const [competition] = await db.insert(competitions).values({
        title: challenge.title,
        description: challenge.description,
        type: "daily_challenge",
        gameType: "progressive_diagnostic_challenge",
        status: "active",
        bodyPart: challenge.bodyPart as any,
        difficulty: challenge.difficulty,
        timeLimit: challenge.timeLimit,
        maxParticipants: 25,
        currentParticipants: 0,
        entryFee: 0,
        prizePool: 0,
        startTime: new Date(),
        endTime: new Date(Date.now() + 72 * 60 * 60 * 1000), // 72 hours from now
        caseStudyIds: [],
        caseType: "simple",
        isAutoGenerated: false,
        rules: {
          scoringWeights: {
            efficiency: 25,
            thoroughness: 25,
            safety: 30,
            accuracy: 20
          },
          allowedAttempts: 1,
          showLeaderboard: true,
          revealAnswers: true,
          stageTimeLimit: challenge.timeLimit
        }
      }).returning();

      console.log(`✓ Created: ${competition.title}`);
    }

    console.log('✓ Successfully added all remaining Progressive Diagnostic Challenge competitions');
    
  } catch (error) {
    console.error('Error adding remaining Progressive Diagnostic Challenges:', error);
    throw error;
  }
}

addRemainingProgressiveCompetitions()
  .then(() => {
    console.log('Remaining Progressive Diagnostic Challenge setup complete');
    process.exit(0);
  })
  .catch((error) => {
    console.error('Failed to setup remaining Progressive Diagnostic Challenges:', error);
    process.exit(1);
  });