import { db } from '../db.js';
import { competitions } from '@shared/schema';
import { limit } from 'drizzle-orm';

async function checkCompetitions() {
  try {
    const existingCompetitions = await db.select().from(competitions).limit(3);
    console.log('Existing competitions:');
    existingCompetitions.forEach((comp, index) => {
      console.log(`\n=== Competition ${index + 1} ===`);
      console.log(`Title: ${comp.title}`);
      console.log(`Type: ${comp.type}`);
      console.log(`Game Type: ${comp.gameType}`);
      console.log(`Status: ${comp.status}`);
      console.log(`Body Part: ${comp.bodyPart}`);
      console.log(`Difficulty: ${comp.difficulty}`);
      console.log(`Case Type: ${comp.caseType}`);
      console.log(`Max Participants: ${comp.maxParticipants}`);
      console.log(`Current Participants: ${comp.currentParticipants}`);
      console.log(`Entry Fee: ${comp.entryFee}`);
      console.log(`Prize Pool: ${comp.prizePool}`);
      console.log(`Start Time: ${comp.startTime}`);
      console.log(`End Time: ${comp.endTime}`);
      console.log(`Is Auto Generated: ${comp.isAutoGenerated}`);
    });
  } catch (error) {
    console.error('Error checking competitions:', error);
  }
}

checkCompetitions()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error('Failed to check competitions:', error);
    process.exit(1);
  });