import { db } from '../db';
import { competitions, gameContent } from '../../shared/schema';

/**
 * Quick add remaining Manual Therapy and Exercise Prescription competitions
 */

async function quickAddEliteCompetitions() {
  console.log('🚀 Quick adding remaining elite competitions...');
  
  try {
    // Check existing competitions
    const existing = await db
      .select()
      .from(competitions)
      .where((table) => table.gameType.in(['manual_therapy_mastery', 'exercise_prescription_expert']));
    
    console.log(`Found ${existing.length} existing elite competitions`);

    // Remaining Manual Therapy competitions to add
    const remainingManualTherapy = [
      {
        title: 'Manual Therapy Mastery: Shoulder Complex',
        description: 'Elite manual therapy techniques for shoulder and upper extremity conditions',
        gameType: 'manual_therapy_mastery',
        bodyPart: 'shoulder'
      },
      {
        title: 'Manual Therapy Mastery: Cervical Spine',
        description: 'Expert-level cervical spine manual therapy with safety considerations',
        gameType: 'manual_therapy_mastery',
        bodyPart: 'neck'
      },
      {
        title: 'Manual Therapy Mastery: Lower Extremity',
        description: 'Advanced manual therapy for hip, knee, and ankle complex conditions',
        gameType: 'manual_therapy_mastery',
        bodyPart: 'hip'
      }
    ];

    // Exercise Prescription competitions to add
    const exerciseCompetitions = [
      {
        title: 'Exercise Prescription Expert: Athletic Recovery',
        description: 'Advanced exercise prescription for return-to-sport scenarios',
        gameType: 'exercise_prescription_expert',
        bodyPart: 'knee'
      },
      {
        title: 'Exercise Prescription Expert: Chronic Pain Management',
        description: 'Evidence-based exercise prescription for complex chronic conditions',
        gameType: 'exercise_prescription_expert',
        bodyPart: 'back'
      },
      {
        title: 'Exercise Prescription Expert: Geriatric Rehabilitation',
        description: 'Specialized exercise programming for older adult populations',
        gameType: 'exercise_prescription_expert',
        bodyPart: 'general'
      },
      {
        title: 'Exercise Prescription Expert: Post-Surgical Protocols',
        description: 'Progressive exercise design for post-operative rehabilitation',
        gameType: 'exercise_prescription_expert',
        bodyPart: 'shoulder'
      }
    ];

    const allCompetitions = [...remainingManualTherapy, ...exerciseCompetitions];

    for (const comp of allCompetitions) {
      // Check if already exists
      const exists = existing.some(e => e.title === comp.title);
      if (exists) {
        console.log(`⏭️ Skipping existing: ${comp.title}`);
        continue;
      }

      console.log(`➕ Adding: ${comp.title}`);
      
      // Create competition with basic content
      const [newCompetition] = await db.insert(competitions).values({
        title: comp.title,
        description: comp.description,
        type: "daily_challenge",
        gameType: comp.gameType as any,
        status: "active",
        bodyPart: comp.bodyPart as any,
        difficulty: "advanced",
        timeLimit: comp.gameType === 'manual_therapy_mastery' ? 20 : 25,
        maxParticipants: 15,
        currentParticipants: 0,
        entryFee: 0,
        prizePool: 0,
        startTime: new Date(),
        endTime: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
        caseStudyIds: [],
        caseType: "simple",
        isAutoGenerated: false,
        rules: {}
      }).returning();

      // Create placeholder content (will be generated later by AI)
      const placeholderContent = comp.gameType === 'manual_therapy_mastery' ? {
        challenges: [{
          id: "placeholder_001",
          scenario: `Advanced ${comp.bodyPart} manual therapy scenario`,
          challenge: "Select appropriate manual therapy techniques",
          options: [],
          timeLimit: 180,
          difficulty: "advanced"
        }]
      } : {
        challenges: [{
          id: "placeholder_001",
          patientProfile: {
            condition: `Complex ${comp.bodyPart} rehabilitation case`,
            challenge: "Design evidence-based exercise program"
          },
          options: [],
          timeLimit: 300,
          difficulty: "advanced"
        }]
      };

      await db.insert(gameContent).values({
        competitionId: newCompetition.id,
        gameType: comp.gameType as any,
        content: placeholderContent,
        createdAt: new Date(),
        updatedAt: new Date()
      });

      console.log(`✅ Added: ${comp.title}`);
    }

    // Final count
    const final = await db
      .select()
      .from(competitions)
      .where((table) => table.gameType.in(['manual_therapy_mastery', 'exercise_prescription_expert']));

    console.log(`\n🎯 Elite competition summary:`);
    console.log(`🏆 Total Manual Therapy Mastery competitions: ${final.filter(c => c.gameType === 'manual_therapy_mastery').length}`);
    console.log(`🏃‍♂️ Total Exercise Prescription Expert competitions: ${final.filter(c => c.gameType === 'exercise_prescription_expert').length}`);
    console.log(`📊 Total elite competitions added: ${final.length}`);

  } catch (error) {
    console.error('❌ Error:', error);
    throw error;
  }
}

// Run the script
quickAddEliteCompetitions()
  .then(() => {
    console.log('\n🎉 Elite competitions setup complete!');
    process.exit(0);
  })
  .catch((error) => {
    console.error('❌ Failed:', error);
    process.exit(1);
  });