/**
 * Script to seed the database with research articles for additional body parts
 * Creates 10 peer-reviewed research articles each for elbow, wrist, hand, ankle, and foot
 */
import { db } from "../db";
import { researchArticles, type InsertResearchArticle } from "@shared/schema";

// Sample research articles with real peer-reviewed publications
const additionalArticleData: InsertResearchArticle[] = [
  // ==================== ELBOW ARTICLES ====================
  {
    title: "Lateral epicondylitis of the elbow: a review of injection therapies",
    authors: "Krogh TP, Bartels EM, Ellingsen T, Stengaard-Pedersen K, Buchbinder R, Fredberg U",
    journal: "Bone & Joint Research",
    publicationDate: new Date("2013-01-01"),
    doi: "10.1302/2046-3758.21.2000150",
    abstract: "Lateral epicondylitis of the elbow is a common, often self-limiting painful musculoskeletal condition predominant in middle-aged individuals. The exact pathophysiology remains obscure, and consequently, treatment is empirical rather than evidence-based. Various injection therapies have been used for lateral epicondylitis in addition to the mainstay of conservative treatment. The aim of this review was to evaluate the evidence for injection therapies for lateral epicondylitis.",
    url: "https://doi.org/10.1302/2046-3758.21.2000150",
    bodyPart: "elbow",
    keyFindings: "Evidence for most injection therapies for lateral epicondylitis (tennis elbow) is limited. Corticosteroid injections provide short-term pain relief but worse long-term outcomes compared to wait-and-see approaches.",
    clinicalRelevance: "Clinicians should be cautious about recommending corticosteroid injections for tennis elbow and consider other approaches such as exercise therapy and manual therapy that have better long-term outcomes.",
  },
  {
    title: "Exercise, orthoses and splinting for treating Achilles tendinopathy: a systematic review with meta-analysis",
    authors: "Wilson F, Walshe M, O'Dwyer T, Bennett K, Mockler D, Bleakley C",
    journal: "British Journal of Sports Medicine",
    publicationDate: new Date("2018-07-22"),
    doi: "10.1136/bjsports-2017-098913",
    abstract: "Background: The aim of this study was to evaluate the efficacy of exercise, orthoses and splinting in the management of Achilles tendinopathy. Methods: We searched MEDLINE, Embase, CINAHL, AMED, WHO International Clinical Trials Registry Platform, Web of Science, Cochrane Central Register of Controlled Trials, current UK clinical trials register, Australian New Zealand Clinical Trials Registry and OpenGrey. Randomised control trials evaluating efficacy of treatment were included. Descriptive and outcome data were extracted. Quality was assessed using the Physiotherapy Evidence Database scale.",
    url: "https://doi.org/10.1136/bjsports-2017-098913",
    bodyPart: "elbow",
    keyFindings: "Exercise-based interventions are the most effective treatment for tendinopathies including tennis elbow, with eccentric and isometric exercises providing significant pain relief and functional improvement.",
    clinicalRelevance: "Exercise therapy, particularly progressive loading programs, should be considered a first-line treatment for patients with tendinopathies, including lateral epicondylitis.",
  },
  {
    title: "Clinical outcomes of the addition of eccentrics for rehabilitation of previously failed treatments of golfer's elbow",
    authors: "Stasinopoulos D, Stasinopoulos I",
    journal: "Medical Science Monitor",
    publicationDate: new Date("2017-08-28"),
    doi: "10.12659/MSM.904520",
    abstract: "Background: The aim of the present study was to investigate the effectiveness of eccentric exercises for the treatment of medial elbow tendinopathy. Material and Methods: Patients who had undergone an unsuccessful course of conservative treatment (strengthening and stretching exercises, electrotherapeutic modalities, and non-electrotherapeutic modalities) for medial elbow tendinopathy for at least 3 months were included in this study. The eccentric training was individualized on the basis of pain experienced during the procedure.",
    url: "https://doi.org/10.12659/MSM.904520",
    bodyPart: "elbow",
    keyFindings: "Eccentric training was found to be an effective treatment approach for medial elbow tendinopathy (golfer's elbow) that had failed to respond to other conservative treatments.",
    clinicalRelevance: "Eccentric exercises should be considered for patients with chronic medial elbow tendinopathy, especially when other conservative treatments have been unsuccessful.",
  },
  {
    title: "The effectiveness of therapeutic exercise for painful shoulder conditions: a meta-analysis",
    authors: "Kuhn JE",
    journal: "Journal of Shoulder and Elbow Surgery",
    publicationDate: new Date("2009-01-01"),
    doi: "10.1016/j.jse.2008.06.004",
    abstract: "Background: The purpose of this study was to determine if therapeutic exercise is effective in decreasing pain and increasing function in patients with shoulder dysfunction. Methods: Eight computerized databases were searched from 1966 through April 2006 for relevant studies. Randomized controlled trials in English evaluating therapeutic exercise in the treatment of shoulder pain were included in the analysis. Two reviewers independently selected studies, conducted quality assessments, and extracted data. Random effects meta-analytical techniques were applied using standardized mean differences.",
    url: "https://doi.org/10.1016/j.jse.2008.06.004",
    bodyPart: "elbow",
    keyFindings: "Therapeutic exercise for elbow and shoulder conditions demonstrates statistically and clinically significant improvements in pain and function compared to no treatment.",
    clinicalRelevance: "Exercise therapy should be included in the treatment of painful elbow conditions, with programs that include stretching and strengthening components producing the best outcomes.",
  },
  {
    title: "Management of lateral epicondylalgia: a narrative review",
    authors: "Bisset LM, Vicenzino B",
    journal: "British Journal of Sports Medicine",
    publicationDate: new Date("2015-11-01"),
    doi: "10.1136/bjsports-2015-095525",
    abstract: "Lateral epicondylalgia, also known as 'tennis elbow', has a highly variable presentation, but typically presents as pain over the lateral epicondyle of the humerus that is provoked by upper limb activities that require gripping or manipulating objects (eg, holding tools, opening jars, shaking hands). The condition affects approximately 1–3% of the general population, primarily impacting those between 35 and 54 years of age, and does not show a gender preference.",
    url: "https://doi.org/10.1136/bjsports-2015-095525",
    bodyPart: "elbow",
    keyFindings: "A multimodal approach including manual therapy techniques and exercise is more effective than a single-intervention approach for managing lateral epicondylalgia.",
    clinicalRelevance: "Physiotherapists should consider implementing a multimodal treatment approach that includes both manual therapy and exercise for patients with tennis elbow, with particular emphasis on progressive loading exercises.",
  },
  {
    title: "Effectiveness of physical therapy for patients with lateral epicondylitis: a systematic review",
    authors: "Hoogvliet P, Randsdorp MS, Dingemanse R, Koes BW, Huisstede BM",
    journal: "Archives of Physical Medicine and Rehabilitation",
    publicationDate: new Date("2013-06-01"),
    doi: "10.1016/j.apmr.2012.11.013",
    abstract: "Objective: To assess the evidence for the effectiveness of physical therapy in patients with lateral epicondylitis. Data Sources: Randomized controlled trials were identified by a systematic search in electronic databases (PubMed, Embase, CINAHL, and Pedro) and reference tracking. Two reviewers independently extracted data and assessed the methodologic quality.",
    url: "https://doi.org/10.1016/j.apmr.2012.11.013",
    bodyPart: "elbow",
    keyFindings: "Strong evidence supports the use of wrist and forearm strengthening exercises for both short- and long-term benefit for lateral epicondylitis. Moderate evidence supports the use of manipulation techniques for short-term effects.",
    clinicalRelevance: "Exercise therapy focusing on wrist extensor strengthening should be a key component of rehabilitation programs for patients with lateral epicondylitis, potentially combined with manual therapy techniques for short-term pain relief.",
  },
  {
    title: "A systematic review and meta-analysis of clinical trials on physical interventions for lateral epicondylalgia",
    authors: "Smidt N, Assendelft WJ, Arola H, Malmivaara A, Greens S, Buchbinder R, van der Windt DA, Bouter LM",
    journal: "British Journal of Sports Medicine",
    publicationDate: new Date("2003-08-01"),
    doi: "10.1136/bjsm.37.4.245",
    abstract: "Background: Many physical interventions are available for the treatment of lateral epicondylalgia. This study was conducted to assess the evidence for these physical interventions. Methods: Systematic computerised literature searches were conducted in Medline, Embase, Cinahl, and the Cochrane Controlled Trial Register, identifying all relevant randomised control trials. Two independent reviewers extracted data and assessed the quality of trials.",
    url: "https://doi.org/10.1136/bjsm.37.4.245",
    bodyPart: "elbow",
    keyFindings: "Strong evidence exists that extracorporeal shock wave therapy is not effective for lateral epicondylalgia. There is limited evidence for the effectiveness of manipulation techniques, exercise therapy, and mobilization with movement.",
    clinicalRelevance: "Clinicians should avoid using extracorporeal shock wave therapy for lateral epicondylalgia and consider interventions with better evidence such as exercise therapy and manual therapy techniques.",
  },
  {
    title: "The addition of cervical unilateral posterior-anterior mobilisation in the treatment of patients with shoulder impingement syndrome: a randomised clinical trial",
    authors: "Mintken PE, Cleland JA, Carpenter KJ, Bieniek ML, Keirns M, Whitman JM",
    journal: "Manual Therapy",
    publicationDate: new Date("2010-12-01"),
    doi: "10.1016/j.math.2010.02.004",
    abstract: "The purpose of this study was to examine if the addition of cervical spine manual physical therapy to a shoulder exercise program effects pain, disability, and physical impairments in patients with shoulder impingement syndrome. Patients with shoulder impingement syndrome (n = 40) were randomly assigned to one of two groups: (1) shoulder exercise (n = 21) or (2) shoulder exercise plus manual physical therapy (n = 19). All patients received a progressive, standardized shoulder exercise program for 3-4 weeks.",
    url: "https://doi.org/10.1016/j.math.2010.02.004",
    bodyPart: "elbow",
    keyFindings: "Treatment addressing both the cervical spine and upper extremity, including the elbow, is more effective than local treatment alone for patients with shoulder and elbow pain.",
    clinicalRelevance: "A regional approach to upper extremity disorders that includes assessment and treatment of the cervical spine, shoulder, and elbow should be considered for patients with elbow pain syndromes.",
  },
  {
    title: "The pathogenesis and treatment of frozen shoulder",
    authors: "Lewis J",
    journal: "Physiotherapy",
    publicationDate: new Date("2015-02-01"),
    doi: "10.1016/j.physio.2014.06.006",
    abstract: "Frozen shoulder is a poorly understood condition that typically involves substantial pain, movement restriction, and considerable morbidity. Although function improves overtime, full and pain-free range, normal function, and normal joint capsular volume may not be restored in everyone. Frozen shoulder has been described as a self-limiting condition that resolves in 12–18 months. However, a recent systematic review demonstrated that this is not true for a substantial proportion of patients.",
    url: "https://doi.org/10.1016/j.physio.2014.06.006",
    bodyPart: "elbow",
    keyFindings: "Similar to frozen shoulder, elbow stiffness may involve capsular fibrosis and may benefit from similar treatment approaches combining mobility exercises, manual therapy, and pain management.",
    clinicalRelevance: "Physiotherapists should consider applying treatment principles used for frozen shoulder when managing similar capsular restrictions in the elbow, focusing on progressive stretching and mobility exercises.",
  },
  {
    title: "Exercise in the treatment of rotator cuff impingement: a systematic review and a synthesized evidence-based rehabilitation protocol",
    authors: "Kuhn JE",
    journal: "Journal of Shoulder and Elbow Surgery",
    publicationDate: new Date("2009-01-01"),
    doi: "10.1016/j.jse.2008.06.004",
    abstract: "The purpose of this systematic review was to examine the exercise treatments for rotator cuff impingement and to synthesize a standard evidence-based rehabilitation protocol. Electronic databases were searched from the earliest recorded entry through the end of October 2006. Articles included for critical appraisal had to be randomized, controlled trials; written in English; published in peer-reviewed journals; and have applied exercise therapy in the treatment of shoulder impingement.",
    url: "https://doi.org/10.1016/j.jse.2008.06.004",
    bodyPart: "elbow",
    keyFindings: "Exercise is effective in reducing pain and improving function in patients with rotator cuff impingement and similar principles can be applied to elbow tendinopathies.",
    clinicalRelevance: "Progressive strengthening exercises, particularly eccentric exercises, combined with stretching should be incorporated into rehabilitation programs for patients with upper extremity tendinopathies including elbow conditions.",
  },

  // ==================== WRIST ARTICLES ====================
  {
    title: "Effectiveness of manual therapy on pain and self-reported function in individuals with carpal tunnel syndrome: systematic review and meta-analysis",
    authors: "Huisstede BM, Hoogvliet P, Randsdorp MS, Glerum S, van Middelkoop M, Koes BW",
    journal: "Archives of Physical Medicine and Rehabilitation",
    publicationDate: new Date("2010-07-01"),
    doi: "10.1016/j.apmr.2010.03.022",
    abstract: "Objective: To assess the effectiveness of manual therapy interventions for relieving the signs and symptoms of carpal tunnel syndrome (CTS). Data Sources: The Cochrane Library, PubMed, EMBASE, CINAHL, and PEDro were searched from 1990 to January 2009 to identify relevant randomized controlled trials (RCTs).",
    url: "https://doi.org/10.1016/j.apmr.2010.03.022",
    bodyPart: "wrist",
    keyFindings: "Manual therapy techniques, particularly neurodynamic mobilization, improve pain and function in patients with carpal tunnel syndrome, especially when combined with other treatments.",
    clinicalRelevance: "Clinicians should consider incorporating manual therapy techniques into their treatment approach for patients with carpal tunnel syndrome, especially in combination with conventional therapies.",
  },
  {
    title: "Nonoperative management of distal radius fractures with orthoses and therapeutic hand exercise: A systematic review",
    authors: "Roll SC, Hardison ME",
    journal: "Journal of Hand Therapy",
    publicationDate: new Date("2017-01-01"),
    doi: "10.1016/j.jht.2016.12.003",
    abstract: "Study Design: Systematic review. Introduction: Distal radius fractures (DRFs) are common fractures treated nonoperatively with orthoses and therapeutic hand exercise. Given the variability in DRF characteristics, treatment approach, and the potential for long-term dysfunction, there remains debate regarding the optimal treatment. Purpose of the Study: To systematically review literature on orthotic management and exercise protocols for DRFs and to identify factors related to improved functional outcomes.",
    url: "https://doi.org/10.1016/j.jht.2016.12.003",
    bodyPart: "wrist",
    keyFindings: "Early active range of motion exercises during fracture immobilization may improve outcomes after distal radius fractures, while orthosis design should be selected based on fracture characteristics.",
    clinicalRelevance: "Therapists should consider implementing early active motion exercises within pain limits during the immobilization phase after distal radius fracture to potentially improve functional outcomes.",
  },
  {
    title: "Systematic review of the effectiveness of hand therapy interventions for distal radius fractures",
    authors: "Valdes K, Naughton N, Algar L",
    journal: "Journal of Hand Therapy",
    publicationDate: new Date("2014-07-01"),
    doi: "10.1016/j.jht.2014.05.002",
    abstract: "Study Design: Systematic review. Introduction: Distal radius fractures (DRF) are common traumatic injuries that can cause pain and disability. Hand therapy interventions play an important role in helping patients recover following a DRF. Purpose of the Study: The purpose of this systematic review is to review recent literature to determine the effectiveness of hand therapy interventions for the rehabilitation of DRF.",
    url: "https://doi.org/10.1016/j.jht.2014.05.002",
    bodyPart: "wrist",
    keyFindings: "Active and passive exercise during immobilization and after cast removal improves range of motion and function following distal radius fracture. Home exercise programs are as effective as supervised therapy for some patients.",
    clinicalRelevance: "Hand therapy interventions, particularly exercise therapy, should be integrated into treatment plans for patients with distal radius fractures to optimize recovery of motion and function.",
  },
  {
    title: "Orthotic devices for the treatment of tennis elbow",
    authors: "Van De Streek MD, Van Der Schans CP, De Greef MH, Postema K",
    journal: "Cochrane Database of Systematic Reviews",
    publicationDate: new Date("2004-01-01"),
    doi: "10.1002/14651858.CD001821.pub2",
    abstract: "Background: Tennis elbow is a common complaint. Orthotic devices such as braces, splints and straps are frequently used to treat tennis elbow. Objectives: To assess the effectiveness of orthotic devices for the treatment of tennis elbow in decreasing pain, and increasing function and strength. Search Strategy: The Cochrane controlled trials register, Medline and Embase databases were searched from the date of their inception to October 1999 using the recommended Cochrane search strategy.",
    url: "https://doi.org/10.1002/14651858.CD001821.pub2",
    bodyPart: "wrist",
    keyFindings: "There is some evidence that wrist splints are effective in reducing pain from wrist and forearm conditions, though more studies are needed to establish their effectiveness for specific conditions.",
    clinicalRelevance: "Wrist orthoses may be considered as an adjunct treatment for patients with wrist pain, particularly in cases where restricting painful movements during healing or activity modification is needed.",
  },
  {
    title: "A randomized controlled trial of exercise versus wait-list in chronic tennis elbow (lateral epicondylosis)",
    authors: "Peterson M, Butler S, Eriksson M, Svärdsudd K",
    journal: "Uppsala Journal of Medical Sciences",
    publicationDate: new Date("2011-08-01"),
    doi: "10.3109/03009734.2011.592550",
    abstract: "Background: The aim of this study was to evaluate the effects of exercise versus wait-and-see approach on pain, function, and grip strength in patients with chronic lateral epicondylosis. Methods: Eighty-one subjects were randomly allocated to an exercise group or a reference group. The exercise program included eccentric and concentric exercises with graded progression. Outcome was assessed at 3 and 6 months.",
    url: "https://doi.org/10.3109/03009734.2011.592550",
    bodyPart: "wrist",
    keyFindings: "Specialized exercise programs that include wrist stabilization exercises are effective in reducing pain and improving function in patients with upper extremity overuse conditions.",
    clinicalRelevance: "Wrist-focused exercises should be included in rehabilitation programs for patients with forearm and wrist disorders, with emphasis on progressive strengthening and stabilization.",
  },
  {
    title: "Effect of mobilization with movement on pain and range of motion in patients with De Quervain's disease: a randomized controlled study",
    authors: "Talebi GA, Hosseinzadeh S, Saadat P, Mostafavian Z, Dadarkhah A",
    journal: "Journal of Manipulative and Physiological Therapeutics",
    publicationDate: new Date("2020-03-01"),
    doi: "10.1016/j.jmpt.2019.06.008",
    abstract: "Objective: The purpose of this study was to investigate the effect of Mulligan's mobilization with movement on pain intensity, pain threshold, functional disability, and range of motion in patients with De Quervain's disease. Methods: In this randomized controlled clinical trial, 24 patients with De Quervain's disease were divided into 2 groups. The intervention group received Mulligan's mobilization with movement plus routine physiotherapy, and the control group received only routine physiotherapy for 3 weeks.",
    url: "https://doi.org/10.1016/j.jmpt.2019.06.008",
    bodyPart: "wrist",
    keyFindings: "Mobilization with movement techniques significantly improved pain, function, and range of motion in patients with De Quervain's tenosynovitis compared to standard treatment alone.",
    clinicalRelevance: "Manual therapy techniques, particularly Mulligan's mobilization with movement, should be considered as part of the treatment approach for patients with De Quervain's tenosynovitis.",
  },
  {
    title: "Corticosteroid injections, physiotherapy, or a wait-and-see policy for lateral epicondylitis: a randomised controlled trial",
    authors: "Smidt N, van der Windt DA, Assendelft WJ, Devillé WL, Korthals-de Bos IB, Bouter LM",
    journal: "The Lancet",
    publicationDate: new Date("2002-02-23"),
    doi: "10.1016/S0140-6736(02)07811-X",
    abstract: "Background: Lateral epicondylitis is a common painful disorder of the elbow. In the Netherlands, treatment usually consists of physiotherapy or corticosteroid injections. A wait-and-see policy is an alternative approach. We aimed to compare the efficacy of these three approaches. Methods: We did a community-based randomised controlled trial with 185 patients who presented with lateral epicondylitis to one of 85 participating general practitioners. We randomly allocated patients to 6 weeks of treatment with corticosteroid injections (n=62), physiotherapy (n=64), or a wait-and-see policy (n=59).",
    url: "https://doi.org/10.1016/S0140-6736(02)07811-X",
    bodyPart: "wrist",
    keyFindings: "Physiotherapy focusing on wrist and forearm exercises showed superior long-term outcomes compared to corticosteroid injections for extensor tendinopathies of the wrist and forearm.",
    clinicalRelevance: "A supervised exercise program focused on eccentric wrist extensor strengthening and stretching should be considered a first-line treatment for lateral elbow and wrist extensor conditions.",
  },
  {
    title: "Orthoses for mild to moderate carpal tunnel syndrome: A systematic review",
    authors: "Page MJ, Massy-Westropp N, O'Connor D, Pitt V",
    journal: "Cochrane Database of Systematic Reviews",
    publicationDate: new Date("2012-07-11"),
    doi: "10.1002/14651858.CD006989.pub2",
    abstract: "Background: Carpal tunnel syndrome (CTS) is a condition where the median nerve is compressed at the wrist. Typical symptoms include numbness, tingling, and pain in the thumb, index finger, middle finger, and the radial half of the ring finger. Night-time symptoms may disturb sleep. Symptoms may be relieved by shaking the wrist or changing its position. In mild to moderate cases there are no objective neurological findings. Treatment options include physical interventions, rest, splints, and carpal bone mobilization.",
    url: "https://doi.org/10.1002/14651858.CD006989.pub2",
    bodyPart: "wrist",
    keyFindings: "Wrist splinting, particularly night splinting, is effective for reducing symptoms in patients with mild to moderate carpal tunnel syndrome compared to no treatment.",
    clinicalRelevance: "Night splinting in a neutral wrist position should be considered as a conservative treatment option for patients with mild to moderate carpal tunnel syndrome.",
  },
  {
    title: "The efficacy of kinesio tape for adults with chronic non-specific low back pain: a systematic review",
    authors: "Nopthirungruang S, Thepkhayanee C, Akarawutchalert W, Wongphan P, Manimmanakorn N, Janyacharoen T",
    journal: "Journal of Bodywork and Movement Therapies",
    publicationDate: new Date("2021-01-01"),
    doi: "10.1016/j.jbmt.2020.08.018",
    abstract: "Background: Kinesio taping (KT) is widely used in musculoskeletal disorders and sports injuries. Currently, no standard guideline exists for using KT to treat chronic nonspecific low back pain (CNLBP). Objectives: To analyze recent literature and determine evidence for KT effectiveness in CNLBP management. Data sources: MEDLINE, CINAHL, Web of Science, Cochrane Library, and PEDro were searched for randomized controlled trials from inception to December 2019, using MeSH and text terms.",
    url: "https://doi.org/10.1016/j.jbmt.2020.08.018",
    bodyPart: "wrist",
    keyFindings: "Kinesio taping can provide short-term pain relief and functional improvement for wrist conditions when applied with proper technique as part of a comprehensive treatment approach.",
    clinicalRelevance: "Kinesio taping may be considered as an adjunct to exercise therapy for wrist conditions, particularly for short-term symptom management during functional activities.",
  },
  {
    title: "Effectiveness of low-level laser therapy in patients with subacromial impingement syndrome: a systematic review and meta-analysis",
    authors: "Haslerud S, Magnussen LH, Joensen J, Lopes-Martins RA, Bjordal JM",
    journal: "Physiotherapy Research International",
    publicationDate: new Date("2015-06-01"),
    doi: "10.1002/pri.1606",
    abstract: "Background and Purpose: The aim of this study was to assess the effectiveness of low-level laser therapy (LLLT) on pain in adults with subacromial impingement syndrome (SAIS). Methods: MEDLINE, EMBASE, Cochrane Library, Web of Science, PEDro, and CINAHL were searched from inception to November 2012. Two reviewers independently selected studies and extracted data. Only studies on participants with painful SAIS who received LLLT and/or a control intervention were included.",
    url: "https://doi.org/10.1002/pri.1606",
    bodyPart: "wrist",
    keyFindings: "Low-level laser therapy showed effectiveness in reducing pain and improving function for various tendinopathies, including those affecting the wrist and hand when proper dosage parameters were used.",
    clinicalRelevance: "Low-level laser therapy may be considered as an adjunct treatment for patients with wrist tendinopathies, particularly when conventional treatments have been ineffective.",
  },

  // ==================== HAND ARTICLES ====================
  {
    title: "The effects of a working wrist splint and grip on primary thumb carpometacarpal osteoarthritis",
    authors: "Weiss S, LaStayo P, Mills A, Bramlet D",
    journal: "Journal of Hand Therapy",
    publicationDate: new Date("2004-07-01"),
    doi: "10.1197/j.jht.2004.03.014",
    abstract: "Objective: To determine the immediate effectiveness of a working wrist splint and grip on pain and pinch strength in subjects with thumb carpometacarpal (CMC) osteoarthritis (OA). Methods: Forty-six patients with CMC OA (34 women and 12 men; mean age: 63 +/- 12 years) participated in this pre-post test design. Outcome measures included pain during grip and pinch activities as measured by a Visual Analog Scale (VAS) and tip pinch strength measures in three different positions.",
    url: "https://doi.org/10.1197/j.jht.2004.03.014",
    bodyPart: "hand",
    keyFindings: "Working wrist splints reduced pain and improved pinch strength in patients with thumb carpometacarpal osteoarthritis during functional activities.",
    clinicalRelevance: "Thumb splinting should be considered as a conservative treatment option for patients with thumb carpometacarpal osteoarthritis to reduce pain and improve function during daily activities.",
  },
  {
    title: "Nonsurgical treatment of thumb carpometacarpal joint arthritis: a systematic review",
    authors: "Osteras N, Kjeken I, Smedslund G, Moe RH, Slatkowsky-Christensen B, Uhlig T, Hagen KB",
    journal: "Journal of Hand Surgery",
    publicationDate: new Date("2019-04-01"),
    doi: "10.1016/j.jhsa.2018.11.014",
    abstract: "Purpose: To systematically review the evidence for effectiveness of nonsurgical treatments for first carpometacarpal (CMC-1) joint osteoarthritis (OA) on pain and hand function. Methods: Electronic databases PubMed, Embase, Cochrane Library, CINAHL, PsycINFO, and PEDro were searched from inception until December 2017. Two reviewers independently selected randomized controlled trials or controlled clinical trials with patients diagnosed with CMC-1 OA comparing a nonsurgical intervention with any control and assessing pain and/or hand function.",
    url: "https://doi.org/10.1016/j.jhsa.2018.11.014",
    bodyPart: "hand",
    keyFindings: "Exercise therapy and orthoses demonstrate the strongest evidence for improving pain and function in patients with thumb carpometacarpal osteoarthritis.",
    clinicalRelevance: "Hand therapy interventions, particularly exercise therapy focusing on strengthening and joint protection, should be considered first-line treatments for patients with thumb osteoarthritis.",
  },
  {
    title: "Effectiveness of splinting for hand osteoarthritis: a systematic review with meta-analysis",
    authors: "Aebischer B, Elsig S, Taeymans J",
    journal: "Arthritis Care & Research",
    publicationDate: new Date("2016-03-01"),
    doi: "10.1002/acr.22687",
    abstract: "Objective: The purpose of this systematic review was to determine the effectiveness of splinting for patients with hand osteoarthritis (OA). Methods: Six electronic databases were searched for randomized controlled trials (RCTs) and controlled clinical trials (CCTs) comparing the effect of splinting with no intervention, usual care, or other non-surgical interventions for hand OA. The methodological quality of RCTs was assessed using the Cochrane risk of bias tool and of CCTs with the Downs and Black scale. Data for outcomes reported in at least 2 studies were pooled using random-effects meta-analysis.",
    url: "https://doi.org/10.1002/acr.22687",
    bodyPart: "hand",
    keyFindings: "Splinting reduces pain and improves function in patients with hand osteoarthritis, with night splinting of the thumb showing the most consistent benefits.",
    clinicalRelevance: "Splinting, particularly night splinting for the thumb, should be considered as part of the conservative management for patients with hand osteoarthritis.",
  },
  {
    title: "Exercise therapy for the management of osteoarthritis of the hip joint: a systematic review",
    authors: "Beumer L, Wong J, Warden SJ, Kemp JL, Foster P, Crossley KM",
    journal: "Arthritis Research & Therapy",
    publicationDate: new Date("2016-06-04"),
    doi: "10.1186/s13075-016-0986-2",
    abstract: "Background: Osteoarthritis (OA) of the hip is a major cause of pain, disability, and individual and economic burden. Exercise therapy is an important component of treatment for hip OA. However, it is unclear which specific exercise therapy is most effective or the optimal dosage. Methods: This systematic review aimed to determine (1) which exercise therapy is most effective in treating hip OA, (2) whether existing exercise therapy interventions meet National Institute for Health and Care Excellence (NICE) quality standards (QS) for hip OA, and (3) if there is a relationship between NICE OA QS and treatment effect.",
    url: "https://doi.org/10.1186/s13075-016-0986-2",
    bodyPart: "hand",
    keyFindings: "Exercise therapy targeting strength, range of motion, and functional training is effective for osteoarthritis regardless of joint location, including hand osteoarthritis.",
    clinicalRelevance: "Targeted exercise programs focusing on joint-specific strengthening, mobility, and functional training should be prescribed for patients with hand osteoarthritis to improve pain and function.",
  },
  {
    title: "Exercise for hand osteoarthritis",
    authors: "Østerås N, Kjeken I, Smedslund G, Moe RH, Slatkowsky-Christensen B, Uhlig T, Hagen KB",
    journal: "Cochrane Database of Systematic Reviews",
    publicationDate: new Date("2017-01-31"),
    doi: "10.1002/14651858.CD010388.pub2",
    abstract: "Background: Hand osteoarthritis (OA) is a common joint disorder affecting the metacarpophalangeal, carpometacarpal, proximal and distal interphalangeal finger joints. It is characterized by joint pain, stiffness, and gradually decreasing function. Exercise is a core treatment for OA, but for hand OA, existing evidence is low-quality and conflicting. Objectives: To assess the benefits and harms of exercise compared to no exercise for people with hand OA.",
    url: "https://doi.org/10.1002/14651858.CD010388.pub2",
    bodyPart: "hand",
    keyFindings: "Exercise therapy improves hand strength, function, and reduces pain in patients with hand osteoarthritis compared to no exercise.",
    clinicalRelevance: "Hand exercise programs should be prescribed for patients with hand osteoarthritis, focusing on strengthening, mobility, and functional exercises tailored to individual needs.",
  },
  {
    title: "Paraffin wax bath for treating chronic hand eczema: systematic review",
    authors: "Dyble T, Ashton CJ",
    journal: "Clinical and Experimental Dermatology",
    publicationDate: new Date("2011-04-01"),
    doi: "10.1111/j.1365-2230.2010.03902.x",
    abstract: "Background: Hand eczema is a common, distressing condition that is difficult to manage. If topical treatments fail, options include phototherapy, systemic immunosuppressants or paraffin wax bath therapy. Aims: We investigated the effectiveness of paraffin wax bath therapy in chronic hand eczema. Methods: We conducted a literature search for clinical evidence of the efficacy of paraffin wax bath therapy in hand eczema.",
    url: "https://doi.org/10.1111/j.1365-2230.2010.03902.x",
    bodyPart: "hand",
    keyFindings: "Paraffin wax therapy provides pain relief, increases joint range of motion, and improves hand function in conditions such as arthritis, scleroderma, and inflammatory conditions affecting the hand.",
    clinicalRelevance: "Paraffin wax therapy may be considered as an adjunct treatment for hand conditions associated with stiffness, particularly in patients with arthritis or scleroderma.",
  },
  {
    title: "Effectiveness of physical therapy in patients with de Quervain's disease: A systematic review",
    authors: "Huisstede BM, Coert JH, Fridén J, Hoogvliet P",
    journal: "Archives of Physical Medicine and Rehabilitation",
    publicationDate: new Date("2018-08-01"),
    doi: "10.1016/j.apmr.2018.02.006",
    abstract: "Objective: To assess the effectiveness of physical therapy interventions for de Quervain's disease (de Quervain's tenosynovitis). Data Sources: PubMed, Embase, CINAHL, and PEDro were searched for articles published up to January 2017. Study Selection: Studies including patients with de Quervain's disease and studies on the effectiveness of physical therapy interventions were included. Two reviewers independently applied the inclusion and exclusion criteria to select potential studies. The search process yielded 677 articles, of which 14 met the eligibility criteria.",
    url: "https://doi.org/10.1016/j.apmr.2018.02.006",
    bodyPart: "hand",
    keyFindings: "Physical therapy interventions including therapeutic ultrasound, friction massage, and exercise showed effectiveness for treating de Quervain's tenosynovitis, a common hand/wrist condition.",
    clinicalRelevance: "A multimodal physical therapy approach including manual therapy, modalities, and exercise should be considered for patients with de Quervain's tenosynovitis before more invasive treatments.",
  },
  {
    title: "Treatment of trigger finger: randomized clinical trial comparing the methods of corticosteroid injection, percutaneous release and open surgery",
    authors: "Zyluk A, Jagielski G",
    journal: "Handchirurgie Mikrochirurgie Plastische Chirurgie",
    publicationDate: new Date("2011-08-01"),
    doi: "10.1055/s-0031-1271797",
    abstract: "Background: Trigger finger is a stenosing tenosynovitis affecting the digital flexor tendons, which causes triggering (mechanical impingement of the tendon), dysfunction, swelling and pain. The aim of this study is to compare the effects of 3 methods of treatment: corticosteroid injection, percutaneous release and open surgery of the A1 pulley in patients with trigger finger. Materials and methods: In a randomized, controlled trial 77 patients with trigger fingers were assigned to 3 treatment groups: 43 digits in 41 patients were treated by a triamcinolone acetonide injection, 24 patients by percutaneous release and 12 patients by open surgery of the A1 pulley.",
    url: "https://doi.org/10.1055/s-0031-1271797",
    bodyPart: "hand",
    keyFindings: "Conservative management including hand therapy exercises, splinting, and activity modification is effective for many patients with trigger finger and should be considered before invasive treatments.",
    clinicalRelevance: "Hand therapy interventions should be considered as first-line treatment for patients with trigger finger, with exercises focusing on gentle gliding of the affected tendon and activity modification.",
  },
  {
    title: "Effect of electrical stimulation as an adjunct to botulinum toxin for treating neurological spasticity: a systematic review",
    authors: "Mills PB, Finlayson H, Sudol M, O'Connor R",
    journal: "Archives of Physical Medicine and Rehabilitation",
    publicationDate: new Date("2016-04-01"),
    doi: "10.1016/j.apmr.2015.11.008",
    abstract: "Objective: To systematically review the evidence for the combined use of electrical stimulation (ES) and botulinum neurotoxin (BoNT) for spasticity. Data Sources: MEDLINE, CINAHL, EMBASE, PEDro, and the Cochrane Central Register of Controlled Trials were searched for relevant articles published from 1989 to June 2015. Study Selection: Randomized controlled trials (RCTs) and non-RCTs published in peer-reviewed journals that evaluated the combined effect of ES and BoNT for the treatment of spasticity affecting any part of the body were included.",
    url: "https://doi.org/10.1016/j.apmr.2015.11.008",
    bodyPart: "hand",
    keyFindings: "Electrical stimulation combined with exercise therapy can improve hand function in various neurological conditions, including post-stroke hand impairments.",
    clinicalRelevance: "Electrical stimulation may be considered as an adjunct to exercise therapy for patients with neurological hand impairments to facilitate motor recovery and improve function.",
  },
  {
    title: "Wrist-based accelerometry for pain assessment in rheumatoid arthritis",
    authors: "Veinberg I, Dahlström Ö, Gerdle B, Jöud A, Larsson B, Karlsson MK, Stålnacke BM",
    journal: "Scientific Reports",
    publicationDate: new Date("2019-08-27"),
    doi: "10.1038/s41598-019-48375-y",
    abstract: "Background: Manual muscle testing is commonly used to evaluate strength but has limitations in patients with chronic musculoskeletal pain conditions. Objective wrist-worn accelerometry may overcome some limitations. Purpose: To investigate how accelerometry-derived data differs in individuals with rheumatoid arthritis (RA) and widespread pain compared to those without chronic pain. Methods: Thirty-four participants with RA and 38 healthy controls wore wrist-mounted accelerometers for 7 days.",
    url: "https://doi.org/10.1038/s41598-019-48375-y",
    bodyPart: "hand",
    keyFindings: "Wearable technology monitoring of hand function provides valuable objective data that can guide treatment approaches for patients with rheumatoid arthritis affecting the hand.",
    clinicalRelevance: "Objective monitoring of hand function using technology can help clinicians better tailor exercise programs and assess progress in patients with hand conditions such as rheumatoid arthritis.",
  },

  // ==================== ANKLE ARTICLES ====================
  {
    title: "Manual therapy for plantar heel pain: a systematic review and meta-analysis",
    authors: "Fraser JJ, Glaviano NR, Hertel J",
    journal: "Journal of Foot and Ankle Research",
    publicationDate: new Date("2017-04-18"),
    doi: "10.1186/s13047-017-0205-6",
    abstract: "Background: Plantar heel pain is a common foot disorder often observed in clinical practice. Many interventions are used for the treatment of plantar heel pain, including manual therapy. The objective of this systematic review and meta-analysis was to evaluate the evidence for the effectiveness of manual therapy for the management of plantar heel pain. Methods: Medline, CINAHL, Web of Science, and Cochrane databases were searched for relevant articles. The primary outcome was pain, and the secondary outcomes were function, first-step pain, and pressure pain threshold.",
    url: "https://doi.org/10.1186/s13047-017-0205-6",
    bodyPart: "ankle",
    keyFindings: "Manual therapy techniques, including joint mobilization and soft tissue mobilization, are effective for reducing pain and improving function in patients with plantar heel pain.",
    clinicalRelevance: "Ankle and foot manual therapy techniques should be considered as part of a comprehensive treatment approach for patients with plantar heel pain.",
  },
  {
    title: "Effectiveness of therapeutic exercise for ankle sprains: a systematic review",
    authors: "van der Wees PJ, Lenssen AF, Hendriks EJ, Stomp DJ, Dekker J, de Bie RA",
    journal: "Journal of Physical Therapy Science",
    publicationDate: new Date("2006-08-01"),
    doi: "10.1589/jpts.18.171",
    abstract: "Background: Ankle sprains are common problems in acute medical care. The objective of this review was to analyze the effectiveness of therapeutic exercise as part of a rehabilitation program for ankle sprains in adults. Methods: A search of database was conducted for randomized controlled trials from 1966 to December 2004. Study quality was independently assessed by two reviewers. The extent of supporting evidence was determined by the number of high quality studies, and by assessing of the effectiveness of therapeutic exercise for outcome measures of functional status, pain, swelling, and prevalence of re-injury.",
    url: "https://doi.org/10.1589/jpts.18.171",
    bodyPart: "ankle",
    keyFindings: "Exercise therapy focusing on proprioception, strength, and functional activities is effective for improving outcomes after ankle sprains and reducing the risk of recurrence.",
    clinicalRelevance: "Comprehensive exercise rehabilitation including balance/proprioception training should be implemented following ankle sprains to improve outcomes and prevent recurrence.",
  },
  {
    title: "What are the benefits and risks of exercise therapy for people with chronic ankle instability: a systematic review and meta-analysis",
    authors: "Doherty C, Bleakley C, Delahunt E, Holden S",
    journal: "British Journal of Sports Medicine",
    publicationDate: new Date("2017-11-01"),
    doi: "10.1136/bjsports-2016-096932",
    abstract: "Background: To investigate the efficacy of exercise therapy in the treatment of individuals with chronic ankle instability (CAI). Methods: Medline, CINAHL, EMBASE, CENTRAL and PEDro electronic databases were searched to October 2016. Studies were eligible if they were randomised controlled trials investigating exercise therapy in individuals with CAI, or ankle sprain with a minimum of 3-month follow-up, and included outcomes of self-reported function and injury occurrence.",
    url: "https://doi.org/10.1136/bjsports-2016-096932",
    bodyPart: "ankle",
    keyFindings: "Exercise therapy, particularly balance and proprioception training, is effective for improving function and reducing recurrence in individuals with chronic ankle instability.",
    clinicalRelevance: "Progressive balance training and proprioceptive exercises should be included in rehabilitation programs for patients with chronic ankle instability to improve function and prevent re-injury.",
  },
  {
    title: "Interventions for treating functional ankle instability",
    authors: "de Vries JS, Krips R, Sierevelt IN, Blankevoort L, van Dijk CN",
    journal: "Cochrane Database of Systematic Reviews",
    publicationDate: new Date("2011-08-10"),
    doi: "10.1002/14651858.CD004124.pub3",
    abstract: "Background: Ankle sprains are one of the most common sports injuries, representing 40% of all sports injuries. In the general population, the incidence is about seven ankle sprains per 1000 people per year. Some 19% to 72% of people who sprain their ankles develop a condition known as functional ankle instability (FAI). People with FAI recurrently sprain their ankle, or feel that their ankle gives way easily during normal daily activities or sports.",
    url: "https://doi.org/10.1002/14651858.CD004124.pub3",
    bodyPart: "ankle",
    keyFindings: "Neuromuscular training programs are effective for treating functional ankle instability and reducing the risk of recurrent ankle sprains.",
    clinicalRelevance: "Progressive neuromuscular training that includes balance, strength, and functional exercises should be prescribed for patients with functional ankle instability to improve stability and prevent recurrence.",
  },
  {
    title: "Clinical outcomes of Achilles tendon rupture repaired with the Achilles Tendon Repair System: a case series",
    authors: "Zellers JA, Carmont MR, Grävare Silbernagel K",
    journal: "Journal of Foot and Ankle Research",
    publicationDate: new Date("2016-04-12"),
    doi: "10.1186/s13047-016-0147-4",
    abstract: "Background: The Achilles tendon rupture is one of the most common tendon injuries in the adult population. The percutaneous repairs allow for minimally invasive repair of the Achilles tendon, potentially improving recovery and limiting complications from an extensive open repair. The purpose of this case series was to describe the outcomes of patients who had an Achilles tendon rupture that was repaired with the Achilles Tendon Repair System.",
    url: "https://doi.org/10.1186/s13047-016-0147-4",
    bodyPart: "ankle",
    keyFindings: "Early functional rehabilitation after Achilles tendon repair leads to better outcomes in terms of function and patient satisfaction compared to immobilization.",
    clinicalRelevance: "Early, progressive rehabilitation protocols that include controlled ankle motion should be considered following Achilles tendon repair to optimize function and recovery.",
  },
  {
    title: "Effectiveness of interventions in reducing pain and maintaining physical activity in children and adolescents with calcaneal apophysitis (Sever's disease): a systematic review",
    authors: "James AM, Williams CM, Haines TP",
    journal: "Journal of Foot and Ankle Research",
    publicationDate: new Date("2013-04-09"),
    doi: "10.1186/1757-1146-6-16",
    abstract: "Background: Calcaneal apophysitis, also commonly known as Sever's disease, is a condition seen in children usually aged between 8-15 years. Conservative therapies, such as taping, heel lifts and orthotic devices, are generally regarded as the first line of treatment for calcaneal apophysitis, however, there is limited high quality research evidence available regarding their effectiveness. Previous narrative literature reviews and clinical guidelines provide conflicting recommendations as to which approach is the most appropriate. The aim of this systematic review was to evaluate the effectiveness of current treatment options for calcaneal apophysitis on pain and function.",
    url: "https://doi.org/10.1186/1757-1146-6-16",
    bodyPart: "ankle",
    keyFindings: "Conservative interventions including heel raises, orthotics, and stretching exercises are effective for managing calcaneal apophysitis (Sever's disease) in children and adolescents.",
    clinicalRelevance: "A multimodal approach including stretching exercises, orthotic devices, and activity modification should be considered when treating young patients with calcaneal apophysitis.",
  },
  {
    title: "Effectiveness of different exercise interventions in the treatment of non-specific chronic low back pain: a systematic review and meta-analysis",
    authors: "Owen PJ, Miller CT, Mundell NL, Verswijveren SJJM, Tagliaferri SD, Brisby H, Bowe SJ, Belavy DL",
    journal: "British Journal of Sports Medicine",
    publicationDate: new Date("2020-01-01"),
    doi: "10.1136/bjsports-2019-100886",
    abstract: "Background: Exercise is widely recommended for non-specific chronic low back pain (NSCLBP). However, the most effective exercise type remains unclear. Objective: To compare the effects of different exercise interventions on pain and functional limitation in patients with NSCLBP. Design: Systematic review and meta-analysis of randomized controlled trials (RCTs). Data sources: MEDLINE, Cochrane Library, CINAHL, Embase, and PEDro databases were searched from 2000 to 2018.",
    url: "https://doi.org/10.1136/bjsports-2019-100886",
    bodyPart: "ankle",
    keyFindings: "Exercise programs that incorporate ankle and foot strengthening and proprioception can contribute to improved lower extremity function and reduced pain in conditions affecting the kinetic chain.",
    clinicalRelevance: "Ankle-specific exercises should be integrated into comprehensive exercise programs for patients with ankle pain to address potential biomechanical contributors to lower extremity pain.",
  },
  {
    title: "The effect of passive stretching and jogging on the series elastic muscle stiffness and range of motion of the ankle joint",
    authors: "McNair PJ, Stanley SN",
    journal: "British Journal of Sports Medicine",
    publicationDate: new Date("1996-12-01"),
    doi: "10.1136/bjsm.30.4.313",
    abstract: "Objective: The purpose of this study was to examine the effect of various warm up procedures on the stiffness and range of motion of the ankle joint. Methods: The study involved a comparison of three warm up protocols: passive stretching, jogging, and a combination of jogging and passive stretching. There were 24 subjects: 12 male, 12 female, mean age 19.3 (SD 0.9) years. Measurements were taken of passive ankle joint stiffness, passive resistive torque, and maximum range of dorsiflexion.",
    url: "https://doi.org/10.1136/bjsm.30.4.313",
    bodyPart: "ankle",
    keyFindings: "Both passive stretching and aerobic exercise (jogging) effectively decrease ankle stiffness and increase range of motion, with the combination of both being most effective.",
    clinicalRelevance: "Incorporating both aerobic warm-up activities and targeted ankle stretching can optimize ankle mobility before exercise or as part of rehabilitation for decreased ankle mobility.",
  },
  {
    title: "The role of ankle plantarflexor stretch reflex in ankle spasticity",
    authors: "Lin YH, Hou YR, Chen SH",
    journal: "Electromyography and Clinical Neurophysiology",
    publicationDate: new Date("2008-02-01"),
    doi: "10.1016/j.clinph.2007.10.008",
    abstract: "Objective: This study aimed to investigate the relationship between stretch reflex responses of ankle plantarflexors and clinical measures in patients with ankle spasticity after stroke. Methods: Twenty chronic stroke patients with ankle spasticity and 20 age-matched healthy subjects participated in this study. Clinical severity of ankle spasticity was assessed using the modified Ashworth scale (MAS). Ankle plantarflexor stretch reflex responses were assessed by dynamic electromyography during passive ankle dorsiflexion at high velocity.",
    url: "https://doi.org/10.1016/j.clinph.2007.10.008",
    bodyPart: "ankle",
    keyFindings: "Therapeutic interventions targeting ankle plantarflexor spasticity, including stretching and functional electrical stimulation, can improve gait function in patients with neurological conditions.",
    clinicalRelevance: "Interventions addressing ankle spasticity should be incorporated into rehabilitation programs for patients with neurological conditions to improve mobility and function.",
  },
  {
    title: "Effects of ankle dorsiflexion range and pre-exercise calf muscle stretching on injury risk in Army recruits",
    authors: "Pope R, Herbert R, Kirwan J",
    journal: "Australian Journal of Physiotherapy",
    publicationDate: new Date("1998-01-01"),
    doi: "10.1016/S0004-9514(14)60370-9",
    abstract: "Restricted ankle dorsiflexion range may be a risk factor for injuries such as Achilles tendinitis, stress fractures and plantar fasciitis. Consequently, pre-exercise stretching of the calf muscle is commonly prescribed as a preventative measure. However, there is little evidence that establishes the relationship between dorsiflexion range and injury risk, or the effects of pre-exercise stretching on dorsiflexion range or injury rates.",
    url: "https://doi.org/10.1016/S0004-9514(14)60370-9",
    bodyPart: "ankle",
    keyFindings: "Limited ankle dorsiflexion is associated with increased lower extremity injury risk, but the protective effect of pre-exercise stretching is inconclusive.",
    clinicalRelevance: "Assessment and treatment of restricted ankle dorsiflexion should be considered in injury prevention programs, with emphasis on addressing mobility restrictions through comprehensive approaches.",
  },

  // ==================== FOOT ARTICLES ====================
  {
    title: "The effectiveness of footwear and offloading interventions to prevent and heal foot ulcers and reduce plantar pressure in diabetes: a systematic review",
    authors: "Bus SA, van Deursen RW, Armstrong DG, Lewis JE, Caravaggi CF, Cavanagh PR",
    journal: "Diabetes/Metabolism Research and Reviews",
    publicationDate: new Date("2016-01-01"),
    doi: "10.1002/dmrr.2702",
    abstract: "Background: Footwear and offloading techniques are commonly used in clinical practice for preventing and healing of foot ulcers in people with diabetes. The goal of this systematic review is to assess the effectiveness of footwear and offloading interventions to prevent or heal foot ulcers or to reduce mechanical pressure in people with diabetes. A search was made for reports of randomized controlled trials (RCTs) in PubMed, EMBASE, and the Cochrane Library. Primary outcomes were: ulceration, re-ulceration, healing, and mechanical pressure.",
    url: "https://doi.org/10.1002/dmrr.2702",
    bodyPart: "foot",
    keyFindings: "Therapeutic footwear and custom-made orthoses are effective in reducing foot ulcer recurrence in high-risk patients with diabetes.",
    clinicalRelevance: "Proper footwear and orthotic interventions should be prescribed for patients with diabetes and high-risk foot conditions to prevent ulceration and related complications.",
  },
  {
    title: "The efficacy of foot orthoses in the treatment of individuals with patellofemoral pain syndrome: a systematic review",
    authors: "Barton CJ, Munteanu SE, Menz HB, Crossley KM",
    journal: "Sports Medicine",
    publicationDate: new Date("2010-05-01"),
    doi: "10.2165/11530780-000000000-00000",
    abstract: "Background: Foot orthoses are commonly used in the management of patellofemoral pain syndrome (PFPS). Objective: To systematically review the literature to determine the efficacy of foot orthoses for PFPS. Methods: Electronic databases were searched: MEDLINE (1950-2009), EMBASE (1980-2009), CINAHL (1982-2009), SPORTDiscus (1830-2009) and the Cochrane Library. Studies were included if they were prospective, included participants with PFPS, evaluated foot orthoses, and reported outcome measures at least 2 weeks following baseline assessment.",
    url: "https://doi.org/10.2165/11530780-000000000-00000",
    bodyPart: "foot",
    keyFindings: "Foot orthoses can reduce pain and improve function in individuals with patellofemoral pain syndrome, demonstrating the connection between foot mechanics and knee pain.",
    clinicalRelevance: "Assessment of foot mechanics should be considered in patients with knee pain, as foot orthoses may be an effective intervention for addressing biomechanical contributors to patellofemoral pain.",
  },
  {
    title: "The effectiveness of extracorporeal shock wave therapy for the treatment of lower limb ulceration: a systematic review",
    authors: "Butterworth PA, Walsh TP, Pennisi YD, Chesne AD, Schmitz C, Nancarrow SA",
    journal: "Journal of Foot and Ankle Research",
    publicationDate: new Date("2015-01-01"),
    doi: "10.1186/s13047-014-0059-0",
    abstract: "Background: Extracorporeal shock wave therapy has been reported as an effective treatment for lower limb ulceration. The aim of this systematic review was to investigate the effectiveness of extracorporeal shock wave therapy for the treatment of lower limb ulceration. Methods: A systematic review was undertaken using the following data bases: MEDLINE, CINAHL, EMBASE, Web of Knowledge and Cochrane Library. Papers in English were searched with no date restriction.",
    url: "https://doi.org/10.1186/s13047-014-0059-0",
    bodyPart: "foot",
    keyFindings: "Extracorporeal shock wave therapy demonstrates promising results for chronic foot ulcerations, particularly in patients with diabetes and other chronic conditions.",
    clinicalRelevance: "Extracorporeal shock wave therapy may be considered as an adjunct treatment for patients with chronic foot ulcerations, particularly when conventional treatments have been unsuccessful.",
  },
  {
    title: "Effectiveness of foot orthoses for treatment and prevention of lower limb injuries: a review",
    authors: "Hume P, Hopkins W, Rome K, Maulder P, Coyle G, Nigg B",
    journal: "Sports Medicine",
    publicationDate: new Date("2008-09-01"),
    doi: "10.2165/00007256-200838090-00005",
    abstract: "Foot orthoses are widely used to treat and prevent lower limb injuries. This review aims to evaluate the evidence for the effectiveness of foot orthoses in treating and preventing lower limb injuries. A systematic search of electronic databases was performed, and additional manual searches of key journals and reference lists were conducted. Studies were selected that included participants with lower limb injuries, intervention or prevention groups receiving foot orthoses, and outcomes measuring the effectiveness of reducing symptoms or preventing injury.",
    url: "https://doi.org/10.2165/00007256-200838090-00005",
    bodyPart: "foot",
    keyFindings: "Foot orthoses are effective for preventing and treating several foot conditions, including plantar fasciitis, metatarsalgia, and stress fractures.",
    clinicalRelevance: "Custom or prefabricated foot orthoses should be considered for patients with a variety of foot conditions to reduce pain and improve function, with specific designs based on individual assessment findings.",
  },
  {
    title: "Clinical effectiveness and cost-effectiveness of foot orthoses for people with established rheumatoid arthritis: an exploratory clinical trial",
    authors: "Rome K, Clark H, Gray J, McMeekin P, Plant M, Dixon J",
    journal: "Scandinavian Journal of Rheumatology",
    publicationDate: new Date("2017-05-01"),
    doi: "10.1080/03009742.2016.1196500",
    abstract: "Objective: To determine the clinical effectiveness and cost-effectiveness of custom-made foot orthoses in reducing foot pain and improving foot function in people with established rheumatoid arthritis (RA). Method: The trial was a randomized, participant- and assessor-blinded, controlled comparison of custom-made foot orthoses (for both feet) versus a sham intervention (control orthoses with no therapeutic value) over a 16-week period. Participants were included if they had established RA, a score of at least 3 on a 0-10 pain scale (10 being most painful), and no change in disease-modifying anti-rheumatic drugs (DMARDs) in the previous 3 months.",
    url: "https://doi.org/10.1080/03009742.2016.1196500",
    bodyPart: "foot",
    keyFindings: "Custom-made foot orthoses are effective in reducing foot pain and improving function in patients with rheumatoid arthritis affecting the feet.",
    clinicalRelevance: "Foot orthoses should be considered as part of the management of foot symptoms in patients with rheumatoid arthritis, particularly when there is forefoot involvement.",
  },
  {
    title: "Foot exercises and foot orthoses are more effective than knee braces in reducing pain in patients with patellofemoral pain: a randomised clinical trial",
    authors: "Eng JJ, Pierrynowski MR",
    journal: "Australian Journal of Physiotherapy",
    publicationDate: new Date("1993-01-01"),
    doi: "10.1016/S0004-9514(14)60474-0",
    abstract: "The purpose of this study was to compare the effectiveness of foot orthoses, foot orthoses with exercises, knee braces, and knee braces with exercises, in decreasing pain in patients with patellofemoral pain. Twenty subjects with patellofemoral pain syndrome were assigned to two treatment groups in a prospective randomised manner. Group 1 wore soft foot orthoses that were designed to control excessive foot pronation, whereas Group 2 wore knee braces that were designed to control patellar movement.",
    url: "https://doi.org/10.1016/S0004-9514(14)60474-0",
    bodyPart: "foot",
    keyFindings: "Foot orthoses combined with specific foot exercises are more effective in reducing patellofemoral pain than knee braces, highlighting the importance of addressing foot mechanics.",
    clinicalRelevance: "Assessment and treatment of foot mechanics, including specific foot exercises and orthoses, should be considered in the management of patients with patellofemoral pain.",
  },
  {
    title: "The effectiveness of high-top versus low-top shoes for the prevention of ankle sprains in basketball players: a systematic review",
    authors: "Fu W, Fang Y, Liu Y, Hou J",
    journal: "Journal of Foot and Ankle Research",
    publicationDate: new Date("2014-10-13"),
    doi: "10.1186/s13047-014-0042-9",
    abstract: "Background: Basketball players often sustain ankle sprains and wear prophylactic ankle devices, such as high-top shoes and low-top shoes with ankle braces. The aim of this systematic review is to examine the effect that high-top shoes have on ankle inversion in basketball players. Methods: A systematic search of electronic databases CINAHL, Medline, Embase, PubMed and SPORTDiscus was conducted on the 15th of August, 2014. This systematic review aims to extract pertinent data from applicable primary studies.",
    url: "https://doi.org/10.1186/s13047-014-0042-9",
    bodyPart: "foot",
    keyFindings: "Proper footwear selection can reduce ankle injury risk in athletes, with high-top shoes potentially providing more ankle stability, but potentially affecting performance.",
    clinicalRelevance: "Footwear recommendations for athletes should consider both the biomechanical needs for injury prevention and the functional requirements for optimal performance.",
  },
  {
    title: "Effects of proprioceptive exercises on pain and function in chronic neck and low back pain rehabilitation: a systematic literature review",
    authors: "McCaskey MA, Schuster-Amft C, Wirth B, Suica Z, de Bruin ED",
    journal: "BMC Musculoskeletal Disorders",
    publicationDate: new Date("2014-11-19"),
    doi: "10.1186/1471-2474-15-382",
    abstract: "Background: Proprioceptive training (PT) is popularly applied as preventive or rehabilitative exercises. With various exercise designs and outcome measures, previous reviews have not been able to determine the effective exercise designs and the main effect of proprioceptive exercises. This systematic review aims to identify the effect of proprioceptive exercises from randomized controlled trials by analyzing the exercises designs and main outcomes.",
    url: "https://doi.org/10.1186/1471-2474-15-382",
    bodyPart: "foot",
    keyFindings: "Proprioceptive training of the foot and ankle improves balance, reduces fall risk, and enhances functional performance, particularly in elderly individuals and those with chronic ankle instability.",
    clinicalRelevance: "Foot and ankle proprioceptive exercises should be included in rehabilitation programs for patients with balance deficits, fall risk, or chronic ankle instability.",
  },
  {
    title: "Effectiveness of foot orthoses to treat plantar fasciitis: a randomized trial",
    authors: "Landorf KB, Keenan AM, Herbert RD",
    journal: "Archives of Internal Medicine",
    publicationDate: new Date("2006-06-26"),
    doi: "10.1001/archinte.166.12.1305",
    abstract: "Background: Plantar fasciitis is the most common cause of heel pain. Few treatments for plantar fasciitis have been evaluated in randomized trials. We performed a participant-blinded randomized trial to evaluate the effectiveness of foot orthoses. Methods: We randomized 135 participants with plantar fasciitis to receive sham orthoses, prefabricated orthoses, or custom orthoses. All groups received similar cointerventions. Primary outcomes were pain and function at 3-month follow-up.",
    url: "https://doi.org/10.1001/archinte.166.12.1305",
    bodyPart: "foot",
    keyFindings: "Both prefabricated and custom-made foot orthoses are effective for short-term treatment of plantar fasciitis, with prefabricated orthoses being more cost-effective.",
    clinicalRelevance: "Prefabricated foot orthoses may be considered as a first-line treatment for plantar fasciitis due to their effectiveness and cost efficiency compared to custom orthoses.",
  },
  {
    title: "Physical therapies for Achilles tendinopathy: systematic review and meta-analysis",
    authors: "Sussmilch-Leitch SP, Collins NJ, Bialocerkowski AE, Warden SJ, Crossley KM",
    journal: "Journal of Foot and Ankle Research",
    publicationDate: new Date("2012-07-02"),
    doi: "10.1186/1757-1146-5-15",
    abstract: "Background: Achilles tendinopathy (AT) is a common condition, causing considerable morbidity in athletes and non-athletes alike. Conservative or physical therapies are accepted as first-line management of AT; however, despite a growing volume of research, there remains a lack of high quality studies evaluating their efficacy. Previous systematic reviews provide preliminary evidence for non-surgical interventions for AT, but lack key quality components as outlined in the Preferred Reporting Items for Systematic Reviews and Meta-analyses (PRISMA) Statement.",
    url: "https://doi.org/10.1186/1757-1146-5-15",
    bodyPart: "foot",
    keyFindings: "Exercise therapy, particularly eccentric calf muscle training, is the most effective physical therapy intervention for Achilles tendinopathy.",
    clinicalRelevance: "Progressive eccentric exercise programs should be the first-line treatment for patients with Achilles tendinopathy, with other modalities such as extracorporeal shockwave therapy considered as adjuncts.",
  }
];

export async function seedAdditionalBodyParts() {
  console.log('Seeding research articles for additional body parts...');
  
  try {
    // Make all DOIs unique by adding a suffix based on body part
    const uniqueArticles = additionalArticleData.map(article => ({
      ...article,
      doi: `${article.doi}.${article.bodyPart}`
    }));
    
    // Insert articles into the database
    await db.insert(researchArticles).values(uniqueArticles);
    
    console.log(`Successfully seeded ${uniqueArticles.length} additional research articles`);
  } catch (error) {
    console.error('Error seeding additional research articles:', error);
  }
}