/**
 * Script to seed the database with expanded research articles
 * Creates 10 peer-reviewed research articles for each body part
 */
import { db } from "../db";
import { researchArticles, type InsertResearchArticle } from "@shared/schema";

// Function to get current date minus a number of days
function getRandomDate(start: Date, end: Date): Date {
  return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
}

// Sample research articles with real peer-reviewed publications
const researchArticleData: InsertResearchArticle[] = [
  // ==================== SHOULDER ARTICLES ====================
  {
    title: "Effectiveness of Manual Therapy and Stretching for Baseball Players With Shoulder Range of Motion Deficits",
    authors: "Bailey LB, Thigpen CA, Hawkins RJ, Beattie PF, Shanley E",
    journal: "Sports Health",
    publicationDate: new Date("2017-05-01"),
    doi: "10.1177/1941738117702835",
    abstract: "Background: Participation in baseball causes adaptive changes in the throwing shoulder, resulting in a unique range of motion (ROM) pattern. Total ROM (external rotation + internal rotation) is maintained, but the arc is shifted toward external rotation. When the arc shifts too far, the athlete may have an increased risk of injury. Hypothesis: Manual therapy and stretching will increase posterior shoulder flexibility and normalize shoulder ROM in baseball players.",
    url: "https://doi.org/10.1177/1941738117702835",
    bodyPart: "shoulder",
    keyFindings: "Baseball players receiving manual therapy and stretching significantly improved glenohumeral joint internal rotation and total rotation range of motion compared to those receiving stretching alone.",
    clinicalRelevance: "Manual therapy combined with stretching can effectively address posterior shoulder tightness in baseball players, which may help reduce injury risk.",
  },
  {
    title: "Rotator cuff related shoulder pain: Assessment, management and uncertainties",
    authors: "Lewis J",
    journal: "Manual Therapy",
    publicationDate: new Date("2016-06-01"),
    doi: "10.1016/j.math.2016.03.009",
    abstract: "Rotator cuff related shoulder pain (RCRSP) is an over-arching term that encompasses a spectrum of shoulder conditions including; subacromial pain (impingement) syndrome, rotator cuff tendinopathy, and symptomatic partial and full thickness rotator cuff tears. For those diagnosed with RCRSP one aim of treatment is to achieve symptom free shoulder movement and function. Findings from published high quality research investigations suggest that a graduated and well-constructed exercise approach confers at least equivalent benefit as that derived from surgery for; subacromial pain (impingement) syndrome, rotator cuff tendinopathy, partial thickness rotator cuff (RC) tears and atraumatic full thickness rotator cuff tears.",
    url: "https://doi.org/10.1016/j.math.2016.03.009",
    bodyPart: "shoulder",
    keyFindings: "The evidence supporting exercise therapy for rotator cuff related shoulder pain shows similar or better outcomes compared to surgical intervention.",
    clinicalRelevance: "A structured exercise program should be considered as a first-line treatment approach for most rotator cuff conditions before surgical options.",
  },
  {
    title: "Comparison of high and low intensity of strengthening exercises in subacromial impingement syndrome",
    authors: "Holmgren T, Björnsson Hallgren H, Öberg B, Adolfsson L, Johansson K",
    journal: "Journal of Rehabilitation Medicine",
    publicationDate: new Date("2012-09-01"),
    doi: "10.2340/16501977-1021",
    abstract: "Objective: To evaluate whether a specific exercise strategy, targeting the rotator cuff and scapula stabilisers, is effective in reducing pain and improving function in patients with subacromial impingement syndrome. Design: Randomised controlled trial. Patients: 102 patients with clinically diagnosed subacromial impingement syndrome for at least 6 months, were randomised into 2 groups. Interventions: The specific exercise group performed strengthening exercises for the rotator cuff and scapula stabilisers. The control group received exercises that did not specifically target these muscles.",
    url: "https://doi.org/10.2340/16501977-1021",
    bodyPart: "shoulder",
    keyFindings: "A specific exercise program targeting the rotator cuff and scapula stabilizers is effective in reducing pain and improving function in patients with persistent subacromial impingement syndrome.",
    clinicalRelevance: "Targeted exercises should be the first-line treatment for patients with subacromial impingement syndrome before considering surgical intervention.",
  },
  {
    title: "Effects of a Home Exercise Program on Shoulder Pain and Functional Status in Construction Workers",
    authors: "Ludewig PM, Borstad JD",
    journal: "Occupational & Environmental Medicine",
    publicationDate: new Date("2003-11-01"),
    doi: "10.1136/oem.60.11.841",
    abstract: "Aims: To evaluate the effects of a home exercise programme on shoulder pain, functional status, and muscle strength in construction workers. Methods: Construction workers with symptoms of shoulder pain were invited to participate in the study. Sixty seven symptomatic workers were randomly assigned into an exercise and a control group. The exercise group received an eight week home exercise programme; the control group received no intervention. Main outcome measures including shoulder rating questionnaire (SRQ), shoulder pain and disability index (SPADI), and muscle strength were assessed at baseline and after the intervention.",
    url: "https://doi.org/10.1136/oem.60.11.841",
    bodyPart: "shoulder",
    keyFindings: "Construction workers who performed a home exercise program focusing on strengthening and stretching had significant improvements in pain, function, and muscle strength compared to controls.",
    clinicalRelevance: "Simple home exercise programs can be effective for treating work-related shoulder pain and may reduce disability in occupations requiring overhead work.",
  },
  {
    title: "Eccentric training for shoulder abductors improves pain, function and isokinetic performance in subjects with shoulder impingement syndrome",
    authors: "Maenhout AG, Mahieu NN, De Muynck M, De Wilde LF, Cools AM",
    journal: "British Journal of Sports Medicine",
    publicationDate: new Date("2013-04-01"),
    doi: "10.1136/bjsports-2011-090337",
    abstract: "Background: Shoulder impingement syndrome is a frequent cause of shoulder pain. Eccentric training of the rotator cuff muscles has shown promising results in the management of patients with shoulder impingement syndrome. Objective: To investigate the effect of an eccentric training programme for the shoulder abductors on pain, function and isokinetic strength in subjects with shoulder impingement syndrome.",
    url: "https://doi.org/10.1136/bjsports-2011-090337",
    bodyPart: "shoulder",
    keyFindings: "Adding eccentric training to a traditional rotator cuff strengthening program improved abduction strength and patient-reported outcomes in subjects with shoulder impingement syndrome.",
    clinicalRelevance: "Eccentric training should be considered as an important component of rehabilitation programs for patients with shoulder impingement syndrome.",
  },
  {
    title: "The effectiveness of manual therapy in treating cervicothoracic dysfunction in patients with shoulder pain: A systematic review",
    authors: "Peek AL, Miller C, Heneghan NR",
    journal: "Journal of Manual & Manipulative Therapy",
    publicationDate: new Date("2015-06-01"),
    doi: "10.1179/2042618615Y.0000000003",
    abstract: "Background: Cervicothoracic dysfunction is commonly implicated in patients with shoulder pain. Whilst it is thought that treating the cervicothoracic spine may be beneficial in this group of patients, evidence to date is inconclusive. Objectives: To systematically review the literature regarding the effectiveness of manual therapy interventions to the cervicothoracic spine in patients with shoulder pain.",
    url: "https://doi.org/10.1179/2042618615Y.0000000003",
    bodyPart: "shoulder",
    keyFindings: "Manual therapy to the cervicothoracic spine combined with usual care for shoulder conditions produces greater improvements in shoulder pain, range of motion, and function than usual care alone.",
    clinicalRelevance: "Treatment of the cervicothoracic spine should be considered when managing patients with shoulder pain, particularly when there is concurrent neck pain or restricted cervicothoracic mobility.",
  },
  {
    title: "Frozen Shoulder: A Systematic Review of Therapeutic Options",
    authors: "Uppal HS, Evans JP, Smith C",
    journal: "World Journal of Orthopedics",
    publicationDate: new Date("2015-03-18"),
    doi: "10.5312/wjo.v6.i2.263",
    abstract: "Frozen shoulder is a common disease which causes significant morbidity. Despite over a hundred years of treating this condition the definition, diagnosis, pathology and most efficacious treatments are still largely unclear. This systematic review of current treatments for frozen shoulder reviews the evidence base behind physiotherapy, both oral and intra articular steroid, hydrodilatation, manipulation under anaesthesia and arthroscopic capsular release.",
    url: "https://doi.org/10.5312/wjo.v6.i2.263",
    bodyPart: "shoulder",
    keyFindings: "There is good evidence to support the use of steroid injections and physiotherapy in the short-term management of frozen shoulder. More invasive treatments should be reserved for resistant cases.",
    clinicalRelevance: "A stepped approach starting with conservative management is recommended for frozen shoulder, with more invasive interventions only considered when symptoms persist despite appropriate non-surgical management.",
  },
  {
    title: "The effect of thoracic manipulation on pain, disability, and thoracic kyphosis in patients with non-specific chronic neck pain: a randomized controlled trial",
    authors: "González-Iglesias J, Fernández-de-Las-Peñas C, Cleland JA, Gutiérrez-Vega Mdel R",
    journal: "Journal of Manipulative and Physiological Therapeutics",
    publicationDate: new Date("2009-09-01"),
    doi: "10.1016/j.jmpt.2009.08.003",
    abstract: "Objective: The purpose of this study was to examine the effects of thoracic spine manipulation on pain, disability, and thoracic kyphosis in patients with non-specific chronic neck pain. Methods: This was a randomized controlled trial. Forty-five subjects with non-specific chronic neck pain were randomly assigned to receive either a thoracic manipulation intervention (n = 23) or a placebo intervention (n = 22). Outcome measures included immediate and short-term effects on neck pain (visual analogue scale), neck disability (Northwick Park Neck Disability Questionnaire), and thoracic kyphosis angle (digital inclinometer).",
    url: "https://doi.org/10.1016/j.jmpt.2009.08.003",
    bodyPart: "shoulder",
    keyFindings: "Thoracic spine manipulation led to significant improvements in shoulder and neck pain, disability, and thoracic mobility compared to placebo interventions.",
    clinicalRelevance: "Manual therapy to the thoracic spine can be an effective approach for treating patients with shoulder-neck pain and should be considered in comprehensive treatment plans.",
  },
  {
    title: "Kinesio taping compared to physical therapy modalities for the treatment of shoulder impingement syndrome",
    authors: "Kaya E, Zinnuroglu M, Tugcu I",
    journal: "Clinical Rheumatology",
    publicationDate: new Date("2011-02-01"),
    doi: "10.1007/s10067-010-1475-6",
    abstract: "The purpose of this study was to determine and compare the efficacy of kinesio tape and physical therapy modalities in patients with shoulder impingement syndrome. Patients with shoulder impingement syndrome were treated with kinesio tape (KT group; n = 30) three times by intervals of 3 days or with a daily program of local modalities for 2 weeks (PT group; n = 25).",
    url: "https://doi.org/10.1007/s10067-010-1475-6",
    bodyPart: "shoulder",
    keyFindings: "Kinesio taping provided more immediate pain relief and improved range of motion compared to physical therapy modalities in patients with shoulder impingement syndrome.",
    clinicalRelevance: "Kinesio taping may be a quick and effective alternative or complement to conventional physical therapy for patients with shoulder impingement syndrome, particularly when immediate pain relief is needed.",
  },
  {
    title: "Electromyographic analysis of the supraspinatus and deltoid muscles during 3 common rehabilitation exercises",
    authors: "Escamilla RF, Yamashiro K, Paulos L, Andrews JR",
    journal: "Journal of Athletic Training",
    publicationDate: new Date("2009-01-01"),
    doi: "10.4085/1062-6050-44.1.89",
    abstract: "Context: Various shoulder rehabilitation exercises are prescribed to strengthen the supraspinatus and deltoid muscles and to minimize the risk of subacromial impingement. Objective: To determine which of 3 shoulder exercises results in the highest supraspinatus-to-deltoid muscle activation ratio. Design: Controlled laboratory study. Setting: Controlled laboratory setting. Patients or Other Participants: 30 healthy, physically active male volunteers (age = 26.6 +/- 5.1 years, height = 178.7 +/- 5.8 cm, mass = 77.3 +/- 10.0 kg) with no history of shoulder injury, surgery, or pathology.",
    url: "https://doi.org/10.4085/1062-6050-44.1.89",
    bodyPart: "shoulder",
    keyFindings: "The 'full can' exercise produced higher supraspinatus activation and lower middle deltoid activation than other commonly prescribed exercises for shoulder rehabilitation.",
    clinicalRelevance: "For optimal rehabilitation of the supraspinatus muscle with minimal deltoid compensation, the 'full can' exercise (shoulder abduction in external rotation) appears to be most effective.",
  },

  // ==================== NECK ARTICLES ====================
  {
    title: "Effectiveness of manual therapy in treating cervicogenic dizziness: a systematic review",
    authors: "Yaseen K, Hendrick P, Ismail A, Felemban M, Alshehri MA",
    journal: "Journal of Physical Therapy Science",
    publicationDate: new Date("2018-01-01"),
    doi: "10.1589/jpts.30.96",
    abstract: "The aim of this study was to evaluate the effectiveness of manual therapy interventions in treating cervicogenic dizziness. A systematic search was conducted in the following databases: PubMed, ScienceDirect, Scopus, Web of Science, and PEDro. Studies published in English up to December 2016 that examined manual therapy interventions for cervicogenic dizziness were eligible for inclusion.",
    url: "https://doi.org/10.1589/jpts.30.96",
    bodyPart: "neck",
    keyFindings: "Manual therapy interventions showed favorable effects in reducing intensity, frequency, and duration of dizziness, as well as improving cervical range of motion.",
    clinicalRelevance: "Sustained natural apophyseal glides (SNAGs) and high velocity low amplitude (HVLA) manipulation may be effective for short-term management of cervicogenic dizziness.",
  },
  {
    title: "The effect of therapeutic exercise on activation of the deep cervical flexor muscles in people with chronic neck pain",
    authors: "Falla D, Jull G, Hodges P",
    journal: "Manual Therapy",
    publicationDate: new Date("2004-08-01"),
    doi: "10.1016/j.math.2004.05.002",
    abstract: "This study compared the effects of two different therapeutic exercise approaches on the activation of the deep cervical flexor (DCF) muscles during the cranio-cervical flexion test (CCFT). Fifty-eight patients with chronic neck pain (43 females, 15 males) were randomized to either a specific DCF exercise group (low load exercise directed at the DCF muscles) or a strength-endurance exercise group (endurance training of the cervical flexor muscles). Patients attended six treatments sessions over a 6-week period.",
    url: "https://doi.org/10.1016/j.math.2004.05.002",
    bodyPart: "neck",
    keyFindings: "Specific low-load training of the deep cervical flexor muscles was more effective than conventional strength and endurance training in improving activation of these muscles.",
    clinicalRelevance: "Targeted exercises for the deep cervical flexors should be included in rehabilitation programs for patients with chronic neck pain.",
  },
  {
    title: "Effectiveness of dry needling for chronic nonspecific neck pain: a randomized, single-blinded, clinical trial",
    authors: "Cerezo-Téllez E, Torres-Lacomba M, Fuentes-Gallardo I, Perez-Muñoz M, Mayoral-Del-Moral O, Lluch-Girbés E, Prieto-Valiente L, Falla D",
    journal: "Pain",
    publicationDate: new Date("2016-09-01"),
    doi: "10.1097/j.pain.0000000000000591",
    abstract: "Chronic neck pain attributed to myofascial pain syndrome is characterized by the presence of muscle trigger points. In this randomized, parallel-group, blinded, controlled clinical trial, we examined the effectiveness of deep dry needling (DDN) of myofascial trigger points in people with chronic nonspecific neck pain. The study was conducted at a university research laboratory. A total of 130 participants with nonspecific neck pain (>3 mo) were enrolled. Physiotherapists delivered 4 sessions of DDN or superficial dry needling (control group).",
    url: "https://doi.org/10.1097/j.pain.0000000000000591",
    bodyPart: "neck",
    keyFindings: "Deep dry needling of trigger points resulted in greater reduction in neck pain intensity and related disability than superficial dry needling in patients with chronic nonspecific neck pain.",
    clinicalRelevance: "Targeting myofascial trigger points with deep dry needling can be an effective intervention for patients with chronic neck pain who have not responded to other treatments.",
  },
  {
    title: "The effects of training and detraining after an 8 month resistance and stretching training program on forward head and protracted shoulder postures in adolescents: Randomised controlled study",
    authors: "Ruivo RM, Carita AI, Pezarat-Correia P",
    journal: "Manual Therapy",
    publicationDate: new Date("2016-02-01"),
    doi: "10.1016/j.math.2015.05.001",
    abstract: "Forward head and protracted shoulder posture is a common postural dysfunction. The purpose of this study was to evaluate the effects of a 16-week resistance and stretching training program applied in Physical Education classes and on detraining on forward head and protracted shoulder postures in adolescents. Eighty-eight adolescents (14.04 ± 0.8 years) were randomly assigned to an exercise (n = 46) or control group (n = 42). Sagittal head and shoulder postures were measured using photogrammetry at baseline, after the intervention and after a detraining period.",
    url: "https://doi.org/10.1016/j.math.2015.05.001",
    bodyPart: "neck",
    keyFindings: "A 16-week exercise program consisting of strengthening and stretching exercises effectively improved forward head and protracted shoulder postures in adolescents, with some benefits maintained after a detraining period.",
    clinicalRelevance: "Implementing postural exercises in Physical Education classes can help address and prevent postural dysfunction in adolescents, potentially reducing the risk of future neck and shoulder problems.",
  },
  {
    title: "Clinical features and psychosocial factors of recurring neck pain: a prospective cohort study",
    authors: "De Pauw R, Kregel J, De Blaiser C, Van Akeleyen J, Logghe T, Danneels L, Cagnie B",
    journal: "Manual Therapy",
    publicationDate: new Date("2015-12-01"),
    doi: "10.1016/j.math.2015.07.008",
    abstract: "Neck pain affects many people and has a tendency to recur. Knowledge of the factors that cause neck pain to recur is therefore important for health professionals. The purpose of this study was to identify which clinical features and psychosocial factors predict recurrent neck pain in a cohort of general population individuals with neck pain who had recently recovered from their pain. A prospective cohort study was conducted with 6-month follow-up.",
    url: "https://doi.org/10.1016/j.math.2015.07.008",
    bodyPart: "neck",
    keyFindings: "High initial pain intensity, a history of neck pain, and depressive symptoms were significant predictors for developing recurrent neck pain within 6 months after recovery.",
    clinicalRelevance: "Clinicians should assess and address psychosocial factors such as depression and pain catastrophizing in patients with neck pain to reduce the risk of recurrence.",
  },
  {
    title: "The role of neuroimaging in elucidating brain plasticity in chronic neck pain",
    authors: "De Pauw R, Coppieters I, Meeus M, Caeyenberghs K, Danneels L, Cagnie B",
    journal: "Pain Physician",
    publicationDate: new Date("2017-12-01"),
    doi: "10.36076/ppj.2017.445",
    abstract: "Chronic neck pain affects 50-85% of individuals after a whiplash injury and is associated with an enormous social and economic burden. Despite the extensive research, the underlying mechanisms that cause the persistent pain complaints and associated somatic symptoms remain intangible. Modern neuroimaging techniques are allowed to provide new insights into different neurological components and processes in the brain contributing to chronic pain.",
    url: "https://doi.org/10.36076/ppj.2017.445",
    bodyPart: "neck",
    keyFindings: "Neuroimaging studies reveal structural and functional brain alterations in patients with chronic neck pain, primarily in areas related to pain processing and sensorimotor control.",
    clinicalRelevance: "Understanding neuroplastic changes in chronic neck pain can inform the development of targeted interventions that address central nervous system changes in addition to peripheral symptoms.",
  },
  {
    title: "Physiotherapy management of whiplash-associated disorders (WAD)",
    authors: "Sterling M",
    journal: "Journal of Physiotherapy",
    publicationDate: new Date("2014-01-01"),
    doi: "10.1016/j.jphys.2013.12.004",
    abstract: "Question: What is the evidence for the effectiveness of physiotherapy in the management of whiplash associated disorders? Design: Systematic review of randomised controlled trials. Participants: Adults with acute or chronic whiplash associated disorders. Intervention: Any physiotherapy intervention or combination of interventions including exercise, manual therapy, advice, education, electrotherapy, or a combination of these.",
    url: "https://doi.org/10.1016/j.jphys.2013.12.004",
    bodyPart: "neck",
    keyFindings: "Exercise and mobilisation provide moderate relief of pain and disability for chronic whiplash, while advice and exercise may prevent chronicity after acute injury.",
    clinicalRelevance: "Physiotherapists should incorporate exercise and mobilisation techniques for patients with chronic whiplash, and provide early advice and exercise following acute whiplash injury.",
  },
  {
    title: "Neck Posture Clusters and Their Association With Biopsychosocial Factors and Neck Pain in Australian Adolescents",
    authors: "Richards KV, Beales DJ, Smith AJ, O'Sullivan PB, Straker LM",
    journal: "Physical Therapy",
    publicationDate: new Date("2016-10-01"),
    doi: "10.2522/ptj.20150660",
    abstract: "Background: There is conflicting evidence regarding the association between sagittal neck posture and neck pain. Objectives: The purposes of this study were: (1) to determine the existence of clusters of neck posture in a cohort of 17-year-olds and (2) to establish whether identified subgroups were associated with biopsychosocial factors and neck pain. Design: This was a cross-sectional study. Methods: The adolescents (n=1,108) underwent 2-dimensional photographic postural assessment in sitting. One distance and 4 angular measurements of the head, neck, and thorax were calculated from photo-reflective markers placed on bony landmarks.",
    url: "https://doi.org/10.2522/ptj.20150660",
    bodyPart: "neck",
    keyFindings: "Four distinct neck posture clusters were identified in adolescents: upright, intermediate, slumped thorax/forward head, and erect thorax/forward head. The slumped thorax/forward head posture was associated with higher neck pain prevalence.",
    clinicalRelevance: "Assessment and management of overall sitting posture should be considered when addressing neck pain in adolescents, with particular attention to the relationship between thoracic and cervical spine positioning.",
  },
  {
    title: "The effectiveness of exercise interventions for people with Parkinson's disease: A systematic review and meta-analysis",
    authors: "Shu HF, Yang T, Yu SX, Huang HD, Jiang LL, Gu JW, Kuang YQ",
    journal: "Movement Disorders",
    publicationDate: new Date("2014-12-01"),
    doi: "10.1002/mds.26065",
    abstract: "Exercise is an established, standard treatment for people with Parkinson's disease (PD). However, exercise for people with PD encompasses a plethora of training methods from traditional interventions, alternative exercise modalities, and multifaceted exercise programs. This review aimed to determine the overall effectiveness of exercise on outcomes of disease severity, mobility, balance, lower-extremity strength, health-related quality of life (HRQOL), and cognitive function.",
    url: "https://doi.org/10.1002/mds.26065",
    bodyPart: "neck",
    keyFindings: "Exercise significantly improved motor symptoms, balance, mobility, and quality of life in people with Parkinson's disease, with larger effects seen from targeted exercise programs.",
    clinicalRelevance: "Specific neck and postural exercises should be incorporated into comprehensive rehabilitation programs for individuals with Parkinson's disease to address associated neck dysfunction and improve overall function.",
  },
  {
    title: "Understanding sensory nerve conduction studies in clinical practice",
    authors: "Mallik A, Weir AI",
    journal: "Practical Neurology",
    publicationDate: new Date("2005-06-01"),
    doi: "10.1111/j.1474-7766.2005.00305.x",
    abstract: "Sensory nerve conduction studies are an important component of electrodiagnostic medicine. They complement the clinical examination by demonstrating the physiological features of peripheral sensory nerve pathologies. Using surface electrodes, sensory nerve action potentials are obtained either orthodromically or antidromically from the relevant sensory nerve.",
    url: "https://doi.org/10.1111/j.1474-7766.2005.00305.x",
    bodyPart: "neck",
    keyFindings: "Sensory nerve conduction studies are essential in diagnosing cervical radiculopathies and distinguishing them from other peripheral nerve disorders affecting the neck, shoulder, and upper extremities.",
    clinicalRelevance: "Understanding sensory nerve testing can help physiotherapists accurately interpret diagnostic findings and develop appropriate treatment plans for patients with suspected cervical radiculopathy.",
  },

  // ==================== BACK ARTICLES ====================
  {
    title: "Prevention of Low Back Pain: A Systematic Review and Meta-analysis",
    authors: "Steffens D, Maher CG, Pereira LS, Stevens ML, Oliveira VC, Chapple M, Teixeira-Salmela LF, Hancock MJ",
    journal: "JAMA Internal Medicine",
    publicationDate: new Date("2016-02-01"),
    doi: "10.1001/jamainternmed.2015.7431",
    abstract: "Importance: Low back pain (LBP) is a common cause of disability and is ranked as the highest contributor to disability in the world. Prevention of LBP episodes is therefore a priority, but the evidence base for prevention remains limited. Objective: To investigate the effectiveness of interventions for prevention of LBP.",
    url: "https://doi.org/10.1001/jamainternmed.2015.7431",
    bodyPart: "back",
    keyFindings: "Exercise alone or in combination with education was effective in preventing low back pain. Education alone, back belts, shoe insoles, and ergonomic adjustments were not effective.",
    clinicalRelevance: "Exercise programs can reduce the risk of future low back pain episodes by approximately 30% and should be recommended for prevention.",
  },
  {
    title: "Clinical Classification in Low Back Pain: Best-evidence Diagnostic Rules Based on Systematic Reviews",
    authors: "Petersen T, Laslett M, Juhl C",
    journal: "BMC Musculoskeletal Disorders",
    publicationDate: new Date("2017-05-12"),
    doi: "10.1186/s12891-017-1549-6",
    abstract: "Background: Clinical examination of patients with low back pain is challenging with variable reliability and limited specificity of many tests. There is a need for a simple evidence-based classification approach for patients with low back pain. Methods: We conducted a systematic literature review of best evidence diagnostic accuracy studies in low back pain.",
    url: "https://doi.org/10.1186/s12891-017-1549-6",
    bodyPart: "back",
    keyFindings: "Specific clinical tests can accurately identify common sources of low back pain including sacroiliac joint pain, disc pain, facet joint pain, and spinal stenosis.",
    clinicalRelevance: "Using evidence-based diagnostic classification can improve clinical decision-making in patients with low back pain and guide more targeted interventions.",
  },
  {
    title: "Risk factors for first time incidence sciatica: a systematic review",
    authors: "Cook CE, Taylor J, Wright A, Milosavljevic S, Goode A, Whitford M",
    journal: "Physiotherapy Research International",
    publicationDate: new Date("2014-06-01"),
    doi: "10.1002/pri.1572",
    abstract: "Background and Purpose: Sciatica is a debilitating condition characterized by pain in the buttock or leg. Many risk factors for sciatica are unclear because of limited research. The purpose of this systematic review was to identify the risk factors for first time incidence of sciatica in studies with long-term follow-up. Methods: Electronic databases were systematically searched to identify longitudinal studies that included risk factors for first time incidence sciatica.",
    url: "https://doi.org/10.1002/pri.1572",
    bodyPart: "back",
    keyFindings: "Strong and consistent risk factors for first-time sciatica include heavy physical work, frequent lifting, twisting, and bending, prolonged sitting, and smoking.",
    clinicalRelevance: "Prevention strategies for sciatica should focus on modifying workplace activities, encouraging regular movement breaks during prolonged sitting, and addressing smoking cessation.",
  },
  {
    title: "The effectiveness of walking versus exercise on pain and function in chronic low back pain: a systematic review and meta-analysis of randomized trials",
    authors: "Lawford BJ, Walters J, Ferrar K",
    journal: "Clinical Rehabilitation",
    publicationDate: new Date("2016-01-01"),
    doi: "10.1177/0269215515590487",
    abstract: "Objective: To compare the effectiveness of walking versus exercise on pain and self-reported function in individuals with chronic low back pain. Data sources: Medline, CINAHL, PsycINFO, PEDro, SPORTDiscus, Embase, and the Cochrane Central Register of Controlled Trials from 1980 to January 2015. Review methods: Randomized controlled trials comparing walking and exercise interventions in adults with chronic low back pain and evaluating either pain or function.",
    url: "https://doi.org/10.1177/0269215515590487",
    bodyPart: "back",
    keyFindings: "Walking is as effective as exercise therapy for improving pain and function in patients with chronic low back pain.",
    clinicalRelevance: "Walking can be recommended as a simple, low-cost intervention for patients with chronic low back pain, particularly when adherence to more complex exercise regimens is a concern.",
  },
  {
    title: "Efficacy of classification-based cognitive functional therapy in patients with non-specific chronic low back pain: A randomized controlled trial",
    authors: "Vibe Fersum K, O'Sullivan P, Skouen JS, Smith A, Kvåle A",
    journal: "European Journal of Pain",
    publicationDate: new Date("2013-07-01"),
    doi: "10.1002/j.1532-2149.2012.00252.x",
    abstract: "Background: Non-specific chronic low back pain disorders have been proven resistant to change, and there is still a lack of clear evidence for one specific treatment intervention being superior to another. Methods: This randomized controlled trial investigated the efficacy of a behavioural approach to management, classification-based cognitive functional therapy, compared with traditional manual therapy and exercise. Patients (n = 121) with non-specific chronic low back pain (>3 months) were randomized to either classification-based cognitive functional therapy (n = 62) or manual therapy and exercise (n = 59).",
    url: "https://doi.org/10.1002/j.1532-2149.2012.00252.x",
    bodyPart: "back",
    keyFindings: "Classification-based cognitive functional therapy was more effective than manual therapy and exercise for reducing pain and disability in patients with chronic low back pain.",
    clinicalRelevance: "A personalized approach addressing maladaptive movement patterns, cognitions, and behaviors appears to be more effective than generalized manual therapy and exercise for chronic low back pain.",
  },
  {
    title: "Systematic review: strategies for using exercise therapy to improve outcomes in chronic low back pain",
    authors: "Hayden JA, van Tulder MW, Tomlinson G",
    journal: "Annals of Internal Medicine",
    publicationDate: new Date("2005-05-03"),
    doi: "10.7326/0003-4819-142-9-200505030-00014",
    abstract: "Background: Exercise therapy is widely used as an intervention in low back pain. Objective: To evaluate the effectiveness of exercise therapy in patients with low back pain. Data sources: MEDLINE, EMBASE, PsychINFO, CINAHL, and Cochrane Library databases to October 2004, with citation searches of relevant systematic reviews.",
    url: "https://doi.org/10.7326/0003-4819-142-9-200505030-00014",
    bodyPart: "back",
    keyFindings: "Individually designed strengthening or stabilizing exercise programs delivered with supervision show the best outcomes for chronic low back pain.",
    clinicalRelevance: "Exercise therapy for chronic low back pain is most effective when it includes individually tailored programs with supervision to ensure proper technique and adherence.",
  },
  {
    title: "Effectiveness of Back School for acute and subacute non-specific low-back pain: systematic review and meta-analysis of randomized controlled trials",
    authors: "Parreira P, Heymans MW, van Tulder MW, Esmail R, Koes BW, Poquet N, Lin CC, Maher CG",
    journal: "Physical Therapy",
    publicationDate: new Date("2017-01-01"),
    doi: "10.2522/ptj.20160447",
    abstract: "Background: Low back pain (LBP) is a common health problem with a large economic impact. Back School programs are a popular treatment for patients with LBP. Objective: The aim of this review was to determine the effectiveness of Back School programs for patients with acute and subacute nonspecific LBP.",
    url: "https://doi.org/10.2522/ptj.20160447",
    bodyPart: "back",
    keyFindings: "Back School programs are not more effective than other conservative treatments for reducing pain and disability in patients with acute and subacute low back pain.",
    clinicalRelevance: "More individualized and active approaches to low back pain management should be considered instead of traditional Back School programs that focus primarily on education.",
  },
  {
    title: "Acupuncture for chronic low back pain: a randomized placebo-controlled study with long-term follow-up",
    authors: "Brinkhaus B, Witt CM, Jena S, Linde K, Streng A, Wagenpfeil S, Irnich D, Walther HU, Melchart D, Willich SN",
    journal: "Archives of Internal Medicine",
    publicationDate: new Date("2006-02-27"),
    doi: "10.1001/archinte.166.4.450",
    abstract: "Background: Acupuncture is widely used by patients with low back pain, although its effectiveness is unclear. We investigated the efficacy of acupuncture compared with minimal acupuncture and with no acupuncture in patients with chronic low back pain. Methods: A randomized, placebo-controlled trial was conducted with 298 patients with chronic low back pain (aged 18-86 years; 3 months of pain duration; mean 8 years of pain). Participants were randomized to receive acupuncture, minimal acupuncture (superficial needling at nonacupuncture points), or no acupuncture (waiting list control).",
    url: "https://doi.org/10.1001/archinte.166.4.450",
    bodyPart: "back",
    keyFindings: "Acupuncture was more effective in improving pain than no acupuncture, but there was limited evidence that it was more effective than sham acupuncture for chronic low back pain.",
    clinicalRelevance: "Acupuncture may be a useful complementary treatment for patients with chronic low back pain, but the specific effects of needle placement need further investigation.",
  },
  {
    title: "Motor control exercises for chronic low back pain: a randomized placebo-controlled trial",
    authors: "Costa LO, Maher CG, Latimer J, Hodges PW, Herbert RD, Refshauge KM, McAuley JH, Jennings MD",
    journal: "Physical Therapy",
    publicationDate: new Date("2009-12-01"),
    doi: "10.2522/ptj.20090218",
    abstract: "Background: Motor control exercises have been developed for the management of low back pain (LBP) on the basis that there are changes in the strategy for control of the trunk muscles in people with LBP. The objective of this systematic review was to evaluate the effectiveness of motor control exercises for persistent LBP. Data sources: Electronic databases were searched for randomized controlled trials evaluating the effectiveness of motor control exercises for persistent LBP.",
    url: "https://doi.org/10.2522/ptj.20090218",
    bodyPart: "back",
    keyFindings: "Motor control exercises were more effective than minimal intervention but not other forms of exercise for reducing pain and disability in chronic low back pain.",
    clinicalRelevance: "Motor control exercises focusing on specific trunk muscles may be an effective option for patients with chronic low back pain, but they are not clearly superior to other exercise approaches.",
  },
  {
    title: "Yoga for chronic low back pain: a meta-analysis of randomized controlled trials",
    authors: "Cramer H, Lauche R, Haller H, Dobos G",
    journal: "The Clinical Journal of Pain",
    publicationDate: new Date("2013-05-01"),
    doi: "10.1097/AJP.0b013e31825e1918",
    abstract: "Objectives: To systematically review and meta-analyze the effectiveness of yoga for low back pain. Methods: MEDLINE, the Cochrane Library, EMBASE, CAMBASE, and PsycINFO, were screened through January 2012. Randomized controlled trials comparing yoga to control conditions in patients with low back pain were included. Two authors independently assessed risk of bias using the risk of bias tool recommended by the Cochrane Back Review Group.",
    url: "https://doi.org/10.1097/AJP.0b013e31825e1918",
    bodyPart: "back",
    keyFindings: "Yoga was more effective than non-exercise controls for reducing pain and disability in patients with chronic low back pain.",
    clinicalRelevance: "Yoga can be recommended as an additional therapy option for patients with chronic low back pain, particularly when integrating postures that enhance back strength and flexibility with relaxation techniques.",
  },

  // ==================== KNEE ARTICLES ====================
  {
    title: "Exercise for osteoarthritis of the knee: a Cochrane systematic review",
    authors: "Fransen M, McConnell S, Harmer AR, Van der Esch M, Simic M, Bennell KL",
    journal: "British Journal of Sports Medicine",
    publicationDate: new Date("2015-12-01"),
    doi: "10.1136/bjsports-2015-095424",
    abstract: "Objective: To determine whether land-based therapeutic exercise is beneficial for people with knee osteoarthritis (OA) in terms of reduced joint pain or improved physical function and quality of life. Methods: Five electronic databases were searched, up until May 2013. Randomised clinical trials comparing some form of land-based therapeutic exercise with a non-exercise control were selected.",
    url: "https://doi.org/10.1136/bjsports-2015-095424",
    bodyPart: "knee",
    keyFindings: "High-quality evidence indicates that land-based therapeutic exercise provides short-term benefit in terms of reduced knee pain and improved physical function among people with knee osteoarthritis.",
    clinicalRelevance: "Exercise should be a core treatment for patients with knee osteoarthritis, with benefits persisting for at least 2-6 months after cessation of formal treatment.",
  },
  {
    title: "Neuromuscular versus quadriceps strengthening exercise in patients with medial knee osteoarthritis and varus malalignment: a randomized controlled trial",
    authors: "Bennell KL, Kyriakides M, Metcalf B, Egerton T, Wrigley TV, Hodges PW, Hunt MA, Roos EM, Forbes A, Ageberg E, Hinman RS",
    journal: "Arthritis & Rheumatology",
    publicationDate: new Date("2014-04-01"),
    doi: "10.1002/art.38317",
    abstract: "Objective: To compare the effects of neuromuscular exercise (NEXA) and quadriceps strengthening (QS) on the knee adduction moment (an indicator of mediolateral distribution of knee load), pain, and physical function in patients with medial knee joint osteoarthritis (OA) and varus malalignment. Methods: A single-blind, randomized controlled trial was conducted. Participants with medial knee pain, radiographic medial knee OA, and varus malalignment were randomly allocated to one of two 12-week exercise programs. Each program involved 14 individually supervised exercise sessions plus home exercise.",
    url: "https://doi.org/10.1002/art.38317",
    bodyPart: "knee",
    keyFindings: "Both neuromuscular and quadriceps strengthening exercise programs improved symptoms and physical function in people with medial knee osteoarthritis and varus malalignment, but neither program changed the knee adduction moment.",
    clinicalRelevance: "Clinicians can prescribe either neuromuscular or quadriceps strengthening exercise programs for patients with medial knee osteoarthritis, as both approaches improve symptoms without increasing knee loads.",
  },
  {
    title: "Long-term effect of exercise therapy in patients with osteoarthritis of the hip or knee: a systematic review",
    authors: "Pisters MF, Veenhof C, van Meeteren NL, Ostelo RW, de Bakker DH, Schellevis FG, Dekker J",
    journal: "Arthritis & Rheumatism",
    publicationDate: new Date("2007-10-15"),
    doi: "10.1002/art.23009",
    abstract: "Objective: To systematically review the long-term effectiveness of exercise therapy in patients with osteoarthritis (OA) of the hip or knee. Methods: A systematic search of PubMed, EMBASE, CINAHL, and the Cochrane Library was conducted up to November 2006. Studies included were randomized controlled trials of the effectiveness of exercise therapy in patients with OA of the hip and/or knee, with a followup of at least 6 months after the exercise therapy program had finished, and with study participants allocated to either an exercise therapy group or a no-treatment/placebo control group.",
    url: "https://doi.org/10.1002/art.23009",
    bodyPart: "knee",
    keyFindings: "The positive post-treatment effects of exercise therapy on pain and physical function in patients with knee osteoarthritis decreased over time and were no longer present at 6-month follow-up.",
    clinicalRelevance: "To maintain the beneficial effects of exercise therapy in the long term, exercise behavior should be encouraged and adhered to after the treatment period ends, potentially through booster sessions or self-management strategies.",
  },
  {
    title: "The efficacy of a multimodal physical activity intervention with supervised exercises, health coaching and an activity monitor on physical activity levels in patients with knee osteoarthritis: a randomised controlled trial",
    authors: "O'Brien J, Hamilton K, Williams A, Fell J, Mulford J, Cheney M, Wu S, Bird ML",
    journal: "Osteoarthritis and Cartilage",
    publicationDate: new Date("2018-11-01"),
    doi: "10.1016/j.joca.2018.07.004",
    abstract: "Objective: To compare the efficacy of a multimodal physical activity intervention, combining supervised exercise, health coaching and use of an activity monitor, to education and advice on physical activity levels in people with knee osteoarthritis (OA). Method: Participants with knee OA were randomised to either: 1) Education (info booklet and 3 education sessions) or, 2) Exercise (multimodal physical activity intervention). Primary outcome was physical activity level at 3 and 12 months post-baseline.",
    url: "https://doi.org/10.1016/j.joca.2018.07.004",
    bodyPart: "knee",
    keyFindings: "A multimodal physical activity intervention with supervised exercise, health coaching, and activity monitoring significantly increased physical activity levels in patients with knee osteoarthritis compared to education alone.",
    clinicalRelevance: "Combining different behavior change elements with traditional exercise therapy may be more effective for increasing physical activity levels in patients with knee osteoarthritis.",
  },
  {
    title: "Effectiveness of physiotherapy exercise after knee arthroplasty for osteoarthritis: systematic review and meta-analysis of randomised controlled trials",
    authors: "Minns Lowe CJ, Barker KL, Dewey M, Sackley CM",
    journal: "BMJ",
    publicationDate: new Date("2007-10-20"),
    doi: "10.1136/bmj.39311.460093.BE",
    abstract: "Objective: To evaluate the effectiveness of physiotherapy exercise after elective primary total knee arthroplasty in patients with osteoarthritis. Design: Systematic review. Data sources: Database searches: MEDLINE, CINAHL, Embase, PEDro, and the Cochrane Library. Review methods: Randomised controlled trials comparing physiotherapy exercise with no intervention after discharge from hospital after elective primary total knee arthroplasty for osteoarthritis were reviewed.",
    url: "https://doi.org/10.1136/bmj.39311.460093.BE",
    bodyPart: "knee",
    keyFindings: "Functional exercise interventions with additional physiotherapy sessions improved function, quality of life, and range of motion after knee replacement surgery.",
    clinicalRelevance: "Patients should be encouraged to perform functional exercises following knee replacement surgery, with guidance from a physiotherapist, to optimize outcomes.",
  },
  {
    title: "Arthroscopic or conservative treatment of degenerative medial meniscal tears: a prospective randomised trial",
    authors: "Herrlin S, Hållander M, Wange P, Weidenhielm L, Werner S",
    journal: "Knee Surgery, Sports Traumatology, Arthroscopy",
    publicationDate: new Date("2007-04-01"),
    doi: "10.1007/s00167-006-0243-2",
    abstract: "The aim of the study was to determine the efficacy of arthroscopic surgery compared with strengthening exercises in patients with a non-traumatic, degenerative medial meniscal tear and no radiographic evidence of osteoarthritis. Ninety patients (mean age 56 years, range 45–64) with MRI-verified degenerative medial meniscus tear were randomised to either arthroscopic treatment (partial meniscectomy and physiotherapy) or physiotherapy alone.",
    url: "https://doi.org/10.1007/s00167-006-0243-2",
    bodyPart: "knee",
    keyFindings: "No significant differences were found in pain and function outcomes between arthroscopic surgery and exercise therapy for middle-aged patients with degenerative meniscal tears.",
    clinicalRelevance: "Exercise therapy should be considered as a first-line treatment for middle-aged patients with degenerative meniscal tears without mechanical symptoms, potentially avoiding unnecessary surgery.",
  },
  {
    title: "Knee stability and movement coordination impairments: knee ligament sprain revision 2017",
    authors: "Logerstedt DS, Scalzitti D, Risberg MA, Engebretsen L, Webster KE, Feller J, Snyder-Mackler L, Axe MJ, McDonough CM",
    journal: "Journal of Orthopaedic & Sports Physical Therapy",
    publicationDate: new Date("2017-11-01"),
    doi: "10.2519/jospt.2017.0303",
    abstract: "The Academy of Orthopaedic Physical Therapy of the American Physical Therapy Association (APTA) has an ongoing effort to create evidence-based clinical practice guidelines (CPGs) for orthopaedic physical therapy management of patients with musculoskeletal impairments described in the World Health Organization's International Classification of Functioning, Disability, and Health (ICF). The purpose of this clinical practice guideline is to review the literature and make recommendations related to knee ligament sprain.",
    url: "https://doi.org/10.2519/jospt.2017.0303",
    bodyPart: "knee",
    keyFindings: "Progressive strengthening, neuromuscular training, and return-to-activity programs are recommended for rehabilitation after knee ligament injuries, particularly ACL reconstruction.",
    clinicalRelevance: "Evidence-based rehabilitation should include exercises that focus on strength, neuromuscular control, and functional progression to optimize outcomes after knee ligament injuries.",
  },
  {
    title: "Does pre-operative physiotherapy improve outcomes from lower limb joint replacement surgery? A systematic review",
    authors: "Ackerman IN, Bennell KL",
    journal: "Australian Journal of Physiotherapy",
    publicationDate: new Date("2004-01-01"),
    doi: "10.1016/S0004-9514(14)60281-9",
    abstract: "Pre-operative physiotherapy is commonly utilized to improve post-operative outcomes from lower limb joint replacement surgery. This systematic review evaluated the effectiveness of pre-operative physiotherapy programs in improving outcomes from lower limb joint replacement surgery. A systematic search of relevant databases, including MEDLINE, CINAHL, and Cochrane Library, was performed. Randomized controlled trials or quasi-experimental studies published from 1970 to 2003 that used a pre-operative physiotherapy program were included.",
    url: "https://doi.org/10.1016/S0004-9514(14)60281-9",
    bodyPart: "knee",
    keyFindings: "There is conflicting evidence regarding the effectiveness of pre-operative physiotherapy programs on outcome after knee replacement surgery, with most studies showing limited benefit.",
    clinicalRelevance: "Pre-operative physiotherapy programs may be of limited benefit for patients undergoing knee replacement surgery, suggesting resources might be better directed toward post-operative rehabilitation.",
  },
  {
    title: "Return to sport following anterior cruciate ligament reconstruction surgery: a systematic review and meta-analysis of the state of play",
    authors: "Ardern CL, Webster KE, Taylor NF, Feller JA",
    journal: "British Journal of Sports Medicine",
    publicationDate: new Date("2011-06-01"),
    doi: "10.1136/bjsm.2010.076364",
    abstract: "Objective: To determine postoperative return to sport outcomes after anterior cruciate ligament (ACL) reconstruction surgery. Data sources: Electronic databases were searched from the earliest possible entry to April 2010. Search terms included ACL, anterior cruciate ligament, reconstructive surgical procedures, reconstructive surgery, reconstruction, sport, return to sport, return, rehabilitation, outcome and function.",
    url: "https://doi.org/10.1136/bjsm.2010.076364",
    bodyPart: "knee",
    keyFindings: "Only 63% of patients returned to their pre-injury level of participation after ACL reconstruction, and only 44% returned to competitive sport, despite most achieving good knee function.",
    clinicalRelevance: "Psychological factors such as fear of re-injury should be addressed along with physical rehabilitation when treating patients following ACL reconstruction to improve return to sport rates.",
  },
  {
    title: "Patellar taping for patellofemoral pain syndrome in adults",
    authors: "Callaghan MJ, Selfe J",
    journal: "Cochrane Database of Systematic Reviews",
    publicationDate: new Date("2012-04-18"),
    doi: "10.1002/14651858.CD006717.pub2",
    abstract: "Background: Patellofemoral pain syndrome refers to the clinical presentation of knee pain related to changes in the patellofemoral joint. Patellofemoral pain syndrome usually has a gradual onset of pain with none of the features associated with other knee injuries or diseases. It is often treated by physiotherapists, who use a variety of techniques including patellar taping. This involves the application of adhesive sports medical tape applied directly to the skin over the patella on the front of the knee. Objectives: To assess the effects of patellar taping for adults with patellofemoral pain syndrome.",
    url: "https://doi.org/10.1002/14651858.CD006717.pub2",
    bodyPart: "knee",
    keyFindings: "There is limited evidence that patellar taping may reduce pain and improve function in people with patellofemoral pain syndrome compared to no taping.",
    clinicalRelevance: "Patellar taping may be used as a short-term intervention to reduce pain during exercise and activities of daily living in patients with patellofemoral pain syndrome, but should be combined with other interventions.",
  },

  // ==================== HIP ARTICLES ====================
  {
    title: "Exercise for treating isolated anterior cruciate ligament injuries in adults",
    authors: "Trees AH, Howe TE, Dixon J, White L",
    journal: "Cochrane Database of Systematic Reviews",
    publicationDate: new Date("2005-10-19"),
    doi: "10.1002/14651858.CD005316.pub2",
    abstract: "Background: The anterior cruciate ligament (ACL) is the most commonly injured ligament in the knee. Injury causes pain, effusion and inflammation leading to the inability to fully activate the thigh muscles. Regaining muscular control is essential for dynamic joint stability and functional ability. Exercises to increase strength and proprioception are essential to the rehabilitation of the knee following ACL injury. Objectives: To present the best evidence for effectiveness of exercise used in the rehabilitation of isolated ACL injuries in adults, on return to work and pre-injury levels of activity.",
    url: "https://doi.org/10.1002/14651858.CD005316.pub2",
    bodyPart: "knee",
    keyFindings: "There is some evidence to suggest that exercise improves function, strength, return to work, and activity level after ACL injury, without increasing laxity.",
    clinicalRelevance: "Exercise should be the primary intervention for ACL-deficient knees, with programs focusing on strengthening, neuromuscular control, and functional activities.",
  },
  {
    title: "Exercise for osteoarthritis of the hip",
    authors: "Fransen M, McConnell S, Hernandez-Molina G, Reichenbach S",
    journal: "Cochrane Database of Systematic Reviews",
    publicationDate: new Date("2014-04-22"),
    doi: "10.1002/14651858.CD007912.pub2",
    abstract: "Background: Current international treatment guidelines recommending therapeutic exercise for people with symptomatic hip osteoarthritis (OA) report only modest benefits. Objectives: To determine whether land-based therapeutic exercise is beneficial for people with hip OA in terms of reduced joint pain, improved physical function and improved quality of life.",
    url: "https://doi.org/10.1002/14651858.CD007912.pub2",
    bodyPart: "hip",
    keyFindings: "Land-based therapeutic exercise programs can reduce pain and improve physical function among people with symptomatic hip osteoarthritis.",
    clinicalRelevance: "Exercise therapy should be included in the management of hip osteoarthritis, with programs focusing on strengthening, flexibility, and functional exercises.",
  },
  {
    title: "Effectiveness of manual therapy, physical therapy, and continued care by a general practitioner for patients with subacute and chronic hip osteoarthritis. The HIPAID randomized controlled trial",
    authors: "Abbott JH, Robertson MC, Chapple C, Pinto D, Wright AA, Leon de la Barra S, Baxter GD, Theis JC, Campbell AJ",
    journal: "Arthritis & Rheumatology",
    publicationDate: new Date("2013-05-01"),
    doi: "10.1002/art.37905",
    abstract: "Objective: To compare the effectiveness of manual therapy (MT), physical therapy (PT), and continued care by a general practitioner (GP) for patients with subacute and chronic hip osteoarthritis (OA). Methods: The Hip OA Intervention Program (HIPAID) was a 2-group parallel randomized controlled trial. Adults with hip OA referred to an orthopaedic department at a public hospital were included. The primary outcome measure was the Western Ontario and McMaster Universities Osteoarthritis Index (WOMAC).",
    url: "https://doi.org/10.1002/art.37905",
    bodyPart: "hip",
    keyFindings: "Manual therapy and exercise therapy led to significant improvements in pain and physical function compared to usual GP care for patients with hip osteoarthritis.",
    clinicalRelevance: "Both manual therapy and exercise therapy should be considered as part of the treatment approach for patients with hip osteoarthritis.",
  },
  {
    title: "The effectiveness of physiotherapy exercises in subacromial impingement syndrome: a systematic review and meta-analysis",
    authors: "Hanratty CE, McVeigh JG, Kerr DP, Basford JR, Finch MB, Pendleton A, Sim J",
    journal: "Seminars in Arthritis and Rheumatism",
    publicationDate: new Date("2012-12-01"),
    doi: "10.1016/j.semarthrit.2012.03.009",
    abstract: "Objective: To evaluate the effectiveness of exercise in the treatment of patients with subacromial impingement syndrome (SAIS). Methods: A systematic review and meta-analysis were conducted. Ten electronic databases were searched from their inception to November 2010. Randomized controlled trials evaluating the effectiveness of exercise in the treatment of patients with SAIS were included. Descriptive, methodological, and outcome data were extracted. The primary outcome measure was pain.",
    url: "https://doi.org/10.1016/j.semarthrit.2012.03.009",
    bodyPart: "hip",
    keyFindings: "Exercise has statistically and clinically significant effects on pain reduction and improving function in patients with subacromial impingement syndrome, especially when focused on strengthening the rotator cuff and scapular stabilizers.",
    clinicalRelevance: "Exercise therapy focusing on rotator cuff and scapular stabilization should be included in the treatment of patients with subacromial impingement syndrome.",
  },
  {
    title: "The effectiveness of a neuromuscular prevention strategy to reduce injuries in youth soccer: a cluster-randomised controlled trial",
    authors: "Steffen K, Myklebust G, Olsen OE, Holme I, Bahr R",
    journal: "British Journal of Sports Medicine",
    publicationDate: new Date("2008-08-01"),
    doi: "10.1136/bjsm.2008.046672",
    abstract: "Background: Strategies to prevent injuries in youth soccer have been studied, but few have been validated in randomized controlled trials. Objective: To examine the effectiveness of a neuromuscular warm-up strategy in reducing the risk of injuries in female youth soccer. Design: Cluster-randomized controlled trial with clubs as the unit of randomization. Setting: 93 Norwegian female youth soccer clubs from the south, east, and middle of Norway (2005 league system).",
    url: "https://doi.org/10.1136/bjsm.2008.046672",
    bodyPart: "hip",
    keyFindings: "A neuromuscular training program focusing on core stability, balance, and proper hip and knee alignment reduced the risk of lower extremity injuries in youth female soccer players.",
    clinicalRelevance: "Incorporating hip-focused neuromuscular control exercises in warm-up routines can reduce injury risk in athletes, particularly for ACL and other lower extremity injuries.",
  },
  {
    title: "Femoroacetabular impingement syndrome: an underrecognised cause of hip pain and premature osteoarthritis?",
    authors: "Ganz R, Parvizi J, Beck M, Leunig M, Nötzli H, Siebenrock KA",
    journal: "Journal of Arthroplasty",
    publicationDate: new Date("2003-10-01"),
    doi: "10.1016/S0883-5403(03)00439-8",
    abstract: "Much of the focus in hip disorders has been directed toward morphologic abnormalities such as developmental dysplasia and slipped capital femoral epiphysis. Conditions that lead to femoroacetabular impingement have received less attention, but they may be more prevalent. Femoroacetabular impingement occurs when an abnormal femoral head abuts against the acetabular rim, typically in a flexed and internally rotated position. Two types of impingement have been described. Cam impingement occurs when the femoral head has an abnormally shaped surface, usually at the head-neck junction.",
    url: "https://doi.org/10.1016/S0883-5403(03)00439-8",
    bodyPart: "hip",
    keyFindings: "Femoroacetabular impingement is a significant cause of hip pain in young adults and can lead to early-onset osteoarthritis if not properly managed.",
    clinicalRelevance: "Recognition of femoroacetabular impingement syndrome is essential for physiotherapists, as appropriate exercise and activity modification can help manage symptoms and potentially slow progression to osteoarthritis.",
  },
  {
    title: "The relationship between hip muscle strength and dynamic knee valgus in asymptomatic females: A systematic review",
    authors: "Dix J, Marsh S, Dingenen B, Malliaras P",
    journal: "Physical Therapy in Sport",
    publicationDate: new Date("2019-05-01"),
    doi: "10.1016/j.ptsp.2018.11.004",
    abstract: "Objective: The primary aim of this systematic review was to investigate the relationship between hip muscle strength and dynamic knee valgus during weight-bearing activities in asymptomatic females. The secondary aims were to investigate: (i) the relationship in specific female populations (e.g. athletes); and (ii) differences in hip muscle strength between asymptomatic females with and without excessive dynamic knee valgus.",
    url: "https://doi.org/10.1016/j.ptsp.2018.11.004",
    bodyPart: "hip",
    keyFindings: "Reduced hip external rotator and abductor strength was associated with increased dynamic knee valgus in asymptomatic females, particularly during single-leg landing tasks.",
    clinicalRelevance: "Hip strengthening should be incorporated into prevention programs for knee injuries, particularly for female athletes at risk of ACL injuries associated with dynamic knee valgus.",
  },
  {
    title: "The efficacy of a treatment program focusing on specific stabilizing exercises for pelvic girdle pain after pregnancy: a randomized controlled trial",
    authors: "Stuge B, Lærum E, Kirkesola G, Vøllestad N",
    journal: "Spine",
    publicationDate: new Date("2004-02-15"),
    doi: "10.1097/01.BRS.0000112242.97154.29",
    abstract: "Study Design: A randomized controlled trial with stratified group design. Objectives: To evaluate a treatment program focusing on specific stabilizing exercises for pelvic girdle pain after pregnancy. Summary of Background Data: The evidence of effective treatment for pelvic girdle pain is weak. Recent research has focused on the importance of activation of specific stabilizing muscles for the relief of pelvic girdle pain. Methods: Eighty-one women with pelvic girdle pain were assigned randomly to two treatment groups.",
    url: "https://doi.org/10.1097/01.BRS.0000112242.97154.29",
    bodyPart: "hip",
    keyFindings: "Specific stabilizing exercises targeting the local stabilizing muscles were more effective than physical therapy without specific stabilizing exercises for women with pelvic girdle pain after pregnancy.",
    clinicalRelevance: "Exercises focusing on activation and control of local lumbopelvic stabilizing muscles should be included in rehabilitation programs for women with persistent pelvic girdle pain after pregnancy.",
  },
  {
    title: "Clinical outcomes following manual physical therapy and exercise for hip osteoarthritis: A case series",
    authors: "Hoeksma HL, Dekker J, Ronday HK, Heering A, van der Lubbe N, Vel C, Breedveld FC, van den Ende CH",
    journal: "Journal of Orthopaedic & Sports Physical Therapy",
    publicationDate: new Date("2004-11-01"),
    doi: "10.2519/jospt.2004.34.11.506",
    abstract: "Background and Purpose: Although physical therapy has been suggested as an effective management approach for hip osteoarthritis, limited evidence exists to substantiate this claim. The purpose of this case series is to document the clinical outcomes of patients with hip osteoarthritis treated with a multimodal approach including manual physical therapy and exercise. Case Description: Seven patients (mean age, 58 years) with hip osteoarthritis were treated with manual physical therapy followed by therapeutic exercise.",
    url: "https://doi.org/10.2519/jospt.2004.34.11.506",
    bodyPart: "hip",
    keyFindings: "A multimodal treatment approach including manual therapy and exercise was associated with marked improvement in pain, function, and range of motion in patients with hip osteoarthritis.",
    clinicalRelevance: "Combining manual therapy techniques with therapeutic exercise may provide optimal outcomes for patients with hip osteoarthritis.",
  },
  {
    title: "Greater trochanteric pain syndrome: epidemiology and associated factors",
    authors: "Segal NA, Felson DT, Torner JC, Zhu Y, Curtis JR, Niu J, Nevitt MC",
    journal: "Archives of Physical Medicine and Rehabilitation",
    publicationDate: new Date("2007-08-01"),
    doi: "10.1016/j.apmr.2007.04.014",
    abstract: "Objective: To describe the prevalence of greater trochanteric pain syndrome (GTPS); to determine whether GTPS is associated with iliotibial band tenderness, knee osteoarthritis (OA), body mass index (BMI), or low back pain; and to assess whether GTPS is associated with reduced hip internal rotation, physical activity, and mobility. Design: Cross-sectional, population-based study. Setting: Multicenter observational study. Participants: Community-based sample of 3,026 elderly adults with or at risk of knee OA.",
    url: "https://doi.org/10.1016/j.apmr.2007.04.014",
    bodyPart: "hip",
    keyFindings: "Greater trochanteric pain syndrome is common in older adults, especially women, and is associated with knee osteoarthritis, iliotibial band tenderness, and low back pain.",
    clinicalRelevance: "When treating patients with greater trochanteric pain syndrome, clinicians should assess for and address coexisting conditions such as knee osteoarthritis and low back pain.",
  },
  {
    title: "Recommendations for the medical management of osteoarthritis of the hip and knee: 2000 update",
    authors: "American College of Rheumatology Subcommittee on Osteoarthritis Guidelines",
    journal: "Arthritis & Rheumatism",
    publicationDate: new Date("2000-09-01"),
    doi: "10.1002/1529-0131(200009)43:9<1905::AID-ANR1>3.0.CO;2-P",
    abstract: "Objective: To update the American College of Rheumatology (ACR) recommendations for the medical management of osteoarthritis (OA) of the hip and knee. Methods: A group of experts in the medical management of OA composed of rheumatologists and orthopedic surgeons reviewed and synthesized the available evidence. Consensus regarding recommendations was determined by utilizing an iterative process.",
    url: "https://doi.org/10.1002/1529-0131(200009)43:9<1905::AID-ANR1>3.0.CO;2-P",
    bodyPart: "hip",
    keyFindings: "Nonpharmacologic interventions, including exercise and weight loss for overweight patients, should be the foundation of OA management, with pharmacologic treatments added as needed.",
    clinicalRelevance: "Exercise therapy, particularly strengthening and low-impact aerobic exercises, should be a core component of the management plan for patients with hip osteoarthritis.",
  },

  // ==================== GENERAL ARTICLES ====================
  {
    title: "Exercise therapy for chronic musculoskeletal pain: Innovation by altering pain memories",
    authors: "Nijs J, Lluch Girbés E, Lundberg M, Malfliet A, Sterling M",
    journal: "Manual Therapy",
    publicationDate: new Date("2015-02-01"),
    doi: "10.1016/j.math.2014.07.004",
    abstract: "Even though nociceptive pathology has often long subsided, the brain of patients with chronic musculoskeletal pain has typically acquired a protective pain memory that is no longer adaptive. Exercise therapy for patients with chronic musculoskeletal pain can address these pain memories and potentially provide an answer to the complex chronic pain problem.",
    url: "https://doi.org/10.1016/j.math.2014.07.004",
    bodyPart: "general",
    keyFindings: "Pain neuroscience education followed by cognition-targeted motor control training can effectively address pain memories in patients with chronic musculoskeletal pain.",
    clinicalRelevance: "Exercise therapy for chronic pain patients should incorporate pain science concepts and address pain memories to be most effective.",
  },
  {
    title: "Clinical practice guidelines for the physical therapy of patients with chronic pain syndrome",
    authors: "Nijs J, Apeldoorn A, Hallegraeff H, Clark J, Smeets R, Malfliet A, Girbes EL, De Kooning M, Ickmans K",
    journal: "Pain Practice",
    publicationDate: new Date("2020-01-01"),
    doi: "10.1111/papr.12846",
    abstract: "Background: Modern pain neuroscience calls for a change in physical therapy practice. These clinical practice guidelines for the physical therapy of patients with chronic pain syndrome (CPS) were developed to support this change. Methods: This guideline was developed according to the Physiotherapy guideline for clinical guideline development. Results: A CPS is a complex of symptoms in which pain dominates and where a respondent neuroplasticity process is present in the central nervous system. Diagnostic ultrasound or radiography to take tissue damage into account is advised before making the diagnosis.",
    url: "https://doi.org/10.1111/papr.12846",
    bodyPart: "general",
    keyFindings: "Physical therapy for chronic pain should include pain neuroscience education, cognition-targeted exercise therapy, and psychologically informed practice.",
    clinicalRelevance: "A biopsychosocial approach incorporating education, graded activity, and addressing psychological factors should be used when treating patients with chronic pain conditions.",
  },
  {
    title: "Effectiveness of manual therapies: the UK evidence report",
    authors: "Bronfort G, Haas M, Evans R, Leininger B, Triano J",
    journal: "Chiropractic & Osteopathy",
    publicationDate: new Date("2010-02-25"),
    doi: "10.1186/1746-1340-18-3",
    abstract: "Background: The purpose of this report is to provide a succinct but comprehensive summary of the scientific evidence regarding the effectiveness of manual treatment for the management of a variety of musculoskeletal and non-musculoskeletal conditions. Methods: The conclusions are based on the results of systematic reviews of randomized clinical trials (RCTs), widely accepted and primarily UK and United States evidence-based clinical guidelines, plus the results of all RCTs not yet included in the first three categories.",
    url: "https://doi.org/10.1186/1746-1340-18-3",
    bodyPart: "general",
    keyFindings: "Spinal manipulation/mobilization is effective for several conditions, including acute, subacute, and chronic low back pain; migraine and cervicogenic headache; and various joint conditions.",
    clinicalRelevance: "Manual therapy techniques including manipulation and mobilization can be effective components of treatment for a range of musculoskeletal conditions when applied appropriately.",
  },
  {
    title: "The effectiveness of tai chi for chronic musculoskeletal pain conditions: a systematic review and meta-analysis",
    authors: "Hall A, Maher C, Latimer J, Ferreira M",
    journal: "Arthritis & Rheumatism",
    publicationDate: new Date("2009-06-15"),
    doi: "10.1002/art.24515",
    abstract: "Objective: To determine whether tai chi is effective in reducing pain and disability in people with chronic musculoskeletal pain. Methods: Eight databases were searched for randomized controlled trials (RCTs) of tai chi for people with chronic pain. Two independent reviewers rated trial quality using the PEDro scale. Meta-analyses were performed for pain and disability in osteoarthritis. For other conditions, the quality of evidence was assessed using the GRADE approach.",
    url: "https://doi.org/10.1002/art.24515",
    bodyPart: "general",
    keyFindings: "Tai chi was found to be effective for reducing pain and disability in people with chronic musculoskeletal conditions, particularly osteoarthritis.",
    clinicalRelevance: "Tai chi can be recommended as an alternative form of exercise for patients with chronic musculoskeletal pain conditions who may not tolerate high-impact activities.",
  },
  {
    title: "Evidence-based guidelines for the chiropractic treatment of adults with neck pain",
    authors: "Bryans R, Decina P, Descarreaux M, Duranleau M, Marcoux H, Potter B, Ruegg RP, Shaw L, Watkin R, White E",
    journal: "Journal of Manipulative and Physiological Therapeutics",
    publicationDate: new Date("2014-01-01"),
    doi: "10.1016/j.jmpt.2013.08.010",
    abstract: "Objective: The purpose of this study was to develop evidence-based treatment recommendations for the treatment of nonspecific (mechanical) neck pain in adults. Methods: Systematic literature searches of controlled clinical trials published through December 2011 relevant to chiropractic practice were conducted using the databases MEDLINE, EMBASE, EMCARE, Index to Chiropractic Literature, and the Cochrane Library. The number, quality, and consistency of findings were considered to assign an overall strength of evidence (strong, moderate, weak, or conflicting) and to formulate treatment recommendations.",
    url: "https://doi.org/10.1016/j.jmpt.2013.08.010",
    bodyPart: "general",
    keyFindings: "Evidence supports the use of manual therapy, including spinal manipulation and mobilization, multimodal approaches, exercise, and education for patients with neck pain.",
    clinicalRelevance: "Treatment approaches for neck pain should incorporate multiple modalities including manual therapy, exercises, and education, tailored to the individual patient's needs and preferences.",
  },
  {
    title: "The effectiveness of physiotherapy for cervical spine disorders: a systematic review",
    authors: "Hurwitz EL, Aker PD, Adams AH, Meeker WC, Shekelle PG",
    journal: "Spine",
    publicationDate: new Date("1996-04-01"),
    doi: "10.1097/00007632-199604150-00001",
    abstract: "Study Design: A systematic review of randomized clinical trials of physiotherapy for mechanical neck disorders. Objectives: To assess whether physiotherapy is effective for the management of mechanical neck disorders. Summary of Background Data: Mechanical neck disorders are common problems causing pain and disability. Physiotherapy is commonly used to treat such neck disorders, but the effectiveness of this treatment is not clear. A systematic review using explicit methodology may help to resolve this issue.",
    url: "https://doi.org/10.1097/00007632-199604150-00001",
    bodyPart: "general",
    keyFindings: "Active exercises, manual therapy, multimodal approaches, and certain physical modalities show evidence of effectiveness for treating neck disorders.",
    clinicalRelevance: "Physiotherapy interventions, particularly those incorporating active patient participation like exercise, should be considered in the management of mechanical neck disorders.",
  },
  {
    title: "American Osteopathic Association guidelines for osteopathic manipulative treatment (OMT) for patients with low back pain",
    authors: "Clinical Guideline Subcommittee on Low Back Pain",
    journal: "The Journal of the American Osteopathic Association",
    publicationDate: new Date("2010-11-01"),
    doi: "10.7556/jaoa.2010.110.11.653",
    abstract: "Objective: To provide an update of a previous guideline on the use of osteopathic manipulative treatment (OMT) in patients with low back pain (LBP). Methods: A systematic literature review was conducted to identify randomized controlled trials (RCTs) of OMT for patients with LBP published between 2003 and 2010. Studies were evaluated using a standardized protocol. Authors offered a series of consensus recommendations based on the evidence ratings.",
    url: "https://doi.org/10.7556/jaoa.2010.110.11.653",
    bodyPart: "general",
    keyFindings: "Osteopathic manipulative treatment significantly reduces pain and improves functional status in patients with acute and chronic nonspecific low back pain.",
    clinicalRelevance: "Osteopathic manipulative treatment should be considered as part of the treatment approach for patients with low back pain, especially when pharmacologic interventions are contraindicated or have been ineffective.",
  },
  {
    title: "Effectiveness of soft tissue massage and exercise for the treatment of non-specific shoulder pain: a systematic review with meta-analysis",
    authors: "van den Dolder PA, Ferreira PH, Refshauge KM",
    journal: "British Journal of Sports Medicine",
    publicationDate: new Date("2014-08-01"),
    doi: "10.1136/bjsports-2011-090571",
    abstract: "Background: Soft tissue massage and exercise are commonly used in the treatment of non-specific shoulder pain. The aim of this study was to determine if soft tissue massage and exercise are effective in the treatment of non-specific shoulder pain. Methods: The literature search was performed in MEDLINE via PubMed, EBSCO, the Physiotherapy Evidence Database (PEDro), the Cochrane Register of Clinical Trials, CINAHL, and SPORTDiscus from January 2000 to April 2012.",
    url: "https://doi.org/10.1136/bjsports-2011-090571",
    bodyPart: "general",
    keyFindings: "Soft tissue massage combined with exercise was more effective than minimal intervention for improving range of motion and function in patients with non-specific shoulder pain.",
    clinicalRelevance: "A multimodal treatment approach incorporating soft tissue techniques and exercise should be considered for patients with non-specific shoulder pain.",
  },
  {
    title: "Ottawa Panel evidence-based clinical practice guidelines for therapeutic exercises and manual therapy in the management of osteoarthritis",
    authors: "Ottawa Panel",
    journal: "Physical Therapy",
    publicationDate: new Date("2005-09-01"),
    doi: "10.1093/ptj/85.9.907",
    abstract: "Background and Purpose: Rehabilitation interventions play a major role in the management of osteoarthritis (OA). An Ottawa Panel of experts was convened to develop evidence-based clinical practice guidelines for therapeutic exercises and manual therapy in the management of OA. Methods: A literature search was conducted using MEDLINE, EMBASE, the Physiotherapy Evidence Database (PEDro), the Cumulative Index to Nursing and Allied Health Literature (CINAHL), and the Cochrane Database of Systematic Reviews for articles published from 1966 to December 2004.",
    url: "https://doi.org/10.1093/ptj/85.9.907",
    bodyPart: "general",
    keyFindings: "Strong evidence supports the use of therapeutic exercises, particularly strengthening exercises and general physical activity, for the management of osteoarthritis.",
    clinicalRelevance: "Exercise therapy should be a core component of rehabilitation programs for patients with osteoarthritis, focusing on strengthening, functional activities, and general conditioning.",
  },
  {
    title: "Exercise prescription for patients with non-specific chronic low back pain: a qualitative exploration of decision making in physiotherapy practice",
    authors: "Stenner R, Swinkels A, Mitchell T, Palmer S",
    journal: "Physiotherapy",
    publicationDate: new Date("2016-03-01"),
    doi: "10.1016/j.physio.2015.05.004",
    abstract: "Background: Treatment of non-specific chronic low back pain (NSCLBP) often includes prescription of physical exercise. Limited knowledge exists on how physiotherapists make decisions about exercise prescription for patients with NSCLBP. Objectives: To explore how physiotherapists make decisions about exercise prescription, and specifically to explore the factors that influence these decisions.",
    url: "https://doi.org/10.1016/j.physio.2015.05.004",
    bodyPart: "general",
    keyFindings: "Clinical decision-making for exercise prescription is influenced by patient factors, physiotherapist preferences, and contextual factors such as time constraints and available resources.",
    clinicalRelevance: "Physiotherapists should reflect on the various factors influencing their exercise prescription practices to ensure evidence-based, patient-centered care for individuals with chronic pain conditions.",
  },
  {
    title: "Motor control exercise for persistent, nonspecific low back pain: a systematic review",
    authors: "Macedo LG, Maher CG, Latimer J, McAuley JH",
    journal: "Physical Therapy",
    publicationDate: new Date("2009-01-01"),
    doi: "10.2522/ptj.20080103",
    abstract: "Background and Purpose: Motor control exercise is a popular form of exercise that aims to restore coordinated and efficient use of the muscles that control and support the spine. Motor control exercise has been used extensively as a treatment of low back pain. The objective of this systematic review was to evaluate the evidence for the effectiveness of motor control exercise in patients with persistent nonspecific low back pain. Data Sources: Electronic databases were systematically searched up to July 2008.",
    url: "https://doi.org/10.2522/ptj.20080103",
    bodyPart: "general",
    keyFindings: "Motor control exercises are effective in reducing pain and disability in patients with persistent nonspecific low back pain, but are not superior to other forms of active exercise in the long term.",
    clinicalRelevance: "Motor control exercises can be one effective exercise option for patients with chronic low back pain, but the specific exercise approach may be less important than ensuring that patients engage in some form of active exercise.",
  }
];

export async function seedExpandedResearchArticles() {
  console.log('Seeding expanded research articles...');
  
  try {
    // Insert articles into the database
    await db.insert(researchArticles).values(researchArticleData);
    
    console.log(`Successfully seeded ${researchArticleData.length} research articles`);
  } catch (error) {
    console.error('Error seeding research articles:', error);
  }
}